#!/bin/bash
git checkout src/main/java/xyz/pixelatedw/mineminenomi/init/ModEntities.java
sed -i 's/public static void init() {}//g' src/main/java/xyz/pixelatedw/mineminenomi/init/ModEntities.java
sed -i '/^}$/d' src/main/java/xyz/pixelatedw/mineminenomi/init/ModEntities.java

# Register properly
cat << 'INNER_EOF' >> src/main/java/xyz/pixelatedw/mineminenomi/init/ModEntities.java
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.DesertGrandeEspadaEntity>> DESERT_GRANDE_ESPADA = ModRegistry.ENTITY_TYPES.register("desert_grande_espada", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.DesertGrandeEspadaEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.DesertGrandeEspadaEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("desert_grande_espada"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.WhiteSnakeEntity>> WHITE_SNAKE = ModRegistry.ENTITY_TYPES.register("white_snake", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.WhiteSnakeEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.WhiteSnakeEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("white_snake"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.StringPillarEntity>> STRING_PILLAR = ModRegistry.ENTITY_TYPES.register("string_pillar", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.StringPillarEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.StringPillarEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("string_pillar"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.RaigoEntity>> RAIGO = ModRegistry.ENTITY_TYPES.register("raigo", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.RaigoEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.RaigoEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("raigo"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.BreezeBreathBombEntity>> BREEZE_BREATH_BOMB = ModRegistry.ENTITY_TYPES.register("breeze_breath_bomb", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.BreezeBreathBombEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.BreezeBreathBombEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("breeze_breath_bomb"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.DarkMatterEntity>> DARK_MATTER = ModRegistry.ENTITY_TYPES.register("dark_matter", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.DarkMatterEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.DarkMatterEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("dark_matter"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.TamaitoEntity>> TAMAITO = ModRegistry.ENTITY_TYPES.register("tamaito", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.TamaitoEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.TamaitoEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("tamaito"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.YasakaniNoMagatamaEntity>> YASAKANI_NO_MAGATAMA = ModRegistry.ENTITY_TYPES.register("yasakani_no_magatama", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.YasakaniNoMagatamaEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.YasakaniNoMagatamaEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("yasakani_no_magatama"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.TsunoTokagePillarEntity>> TSUNO_TOKAGE_PILLAR = ModRegistry.ENTITY_TYPES.register("tsuno_tokage_pillar", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.TsunoTokagePillarEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.TsunoTokagePillarEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("tsuno_tokage_pillar"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.BlackBoxEntity>> BLACK_BOX = ModRegistry.ENTITY_TYPES.register("black_box", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.BlackBoxEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.BlackBoxEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("black_box"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.SablesPesadoEntity>> SABLES_PESADO = ModRegistry.ENTITY_TYPES.register("sables_pesado", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.SablesPesadoEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.SablesPesadoEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("sables_pesado"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.LiberationEntity>> LIBERATION = ModRegistry.ENTITY_TYPES.register("liberation", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.LiberationEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.LiberationEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("liberation"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.ChloroBallEntity>> CHLORO_BALL = ModRegistry.ENTITY_TYPES.register("chloro_ball", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.ChloroBallEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.ChloroBallEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("chloro_ball"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.ElThorEntity>> EL_THOR = ModRegistry.ENTITY_TYPES.register("el_thor", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.ElThorEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.ElThorEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("el_thor"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.VenomRoadEntity>> VENOM_ROAD = ModRegistry.ENTITY_TYPES.register("venom_road", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.VenomRoadEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.VenomRoadEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("venom_road"));
    public static final java.util.function.Supplier<EntityType<xyz.pixelatedw.mineminenomi.entities.projectiles.HydraEntity>> HYDRA = ModRegistry.ENTITY_TYPES.register("hydra", () -> EntityType.Builder.<xyz.pixelatedw.mineminenomi.entities.projectiles.HydraEntity>of(xyz.pixelatedw.mineminenomi.entities.projectiles.HydraEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build("hydra"));

    public static void init() {}
}
INNER_EOF
