package xyz.pixelatedw.mineminenomi.init;

import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.RegistryObject;
import xyz.pixelatedw.mineminenomi.abilities.BakudanAbility;
import xyz.pixelatedw.mineminenomi.abilities.BattoStrikeAbility;
import xyz.pixelatedw.mineminenomi.abilities.BellyFlopAbility;
import xyz.pixelatedw.mineminenomi.abilities.BombThrowAbility;
import xyz.pixelatedw.mineminenomi.abilities.ChargedCleaveAbility;
import xyz.pixelatedw.mineminenomi.abilities.CommandAbility;
import xyz.pixelatedw.mineminenomi.abilities.EmptyHandsAbility;
import xyz.pixelatedw.mineminenomi.abilities.GrabLockAbility;
import xyz.pixelatedw.mineminenomi.abilities.GunArrayAbility;
import xyz.pixelatedw.mineminenomi.abilities.HonkAbility;
import xyz.pixelatedw.mineminenomi.abilities.HookGrabAbility;
import xyz.pixelatedw.mineminenomi.abilities.KnockdownAbility;
import xyz.pixelatedw.mineminenomi.abilities.LeapAbility;
import xyz.pixelatedw.mineminenomi.abilities.MH5Ability;
import xyz.pixelatedw.mineminenomi.abilities.OneTwoJangoAbility;
import xyz.pixelatedw.mineminenomi.abilities.PearlFireAbility;
import xyz.pixelatedw.mineminenomi.abilities.ShakushiAbility;
import xyz.pixelatedw.mineminenomi.abilities.SlamAbility;
import xyz.pixelatedw.mineminenomi.abilities.StealPunchAbility;
import xyz.pixelatedw.mineminenomi.abilities.StealthFootAbility;
import xyz.pixelatedw.mineminenomi.abilities.TailSpinAbility;
import xyz.pixelatedw.mineminenomi.abilities.TakedownKickAbility;
import xyz.pixelatedw.mineminenomi.abilities.TestAbility;
import xyz.pixelatedw.mineminenomi.abilities.TestPartsAbility;
import xyz.pixelatedw.mineminenomi.abilities.WeaponSpinAbility;
import xyz.pixelatedw.mineminenomi.abilities.WeaponThrowAbility;
import xyz.pixelatedw.mineminenomi.abilities.WootzNetLauncherAbility;
import xyz.pixelatedw.mineminenomi.abilities.ZoomAbility;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.CoolBallAbility;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.GustSwordAbility;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.HeatBallAbility;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.ThunderBallAbility;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.WeatherEggAbility;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.CycloneTempo;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.FogTempo;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.HeatEggTempo;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.MirageTempo;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.RainTempo;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.ThunderLanceTempo;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.ThunderboltTempo;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.ThunderstormTempo;
import xyz.pixelatedw.mineminenomi.abilities.artofweather.tempos.WeatherCloudTempo;
import xyz.pixelatedw.mineminenomi.abilities.blackleg.AntiMannerKickCourseAbility;
import xyz.pixelatedw.mineminenomi.abilities.blackleg.BienCuitGrillShotAbility;
import xyz.pixelatedw.mineminenomi.abilities.blackleg.BlackLegPassiveBonusesAbility;
import xyz.pixelatedw.mineminenomi.abilities.blackleg.ConcasseAbility;
import xyz.pixelatedw.mineminenomi.abilities.blackleg.DiableJambeAbility;
import xyz.pixelatedw.mineminenomi.abilities.blackleg.ExtraHachisAbility;
import xyz.pixelatedw.mineminenomi.abilities.blackleg.PartyTableKickCourseAbility;
import xyz.pixelatedw.mineminenomi.abilities.blackleg.SkywalkAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.BrawlerPassiveBonusesAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.ChargedPunchAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.DamageAbsorptionAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.GenkotsuMeteorAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.HakaiHoAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.JishinHoAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.KingPunchAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.PunchRushAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.SpinningBrawlAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.SuplexAbility;
import xyz.pixelatedw.mineminenomi.abilities.brawler.TackleAbility;
import xyz.pixelatedw.mineminenomi.abilities.carnivaltricks.IchirinZashiAbility;
import xyz.pixelatedw.mineminenomi.abilities.carnivaltricks.KajiOyajiAbility;
import xyz.pixelatedw.mineminenomi.abilities.carnivaltricks.KamikazeHyakkomaGekijoAbility;
import xyz.pixelatedw.mineminenomi.abilities.cyborg.ColaBackpackBonusAbility;
import xyz.pixelatedw.mineminenomi.abilities.cyborg.ColaFuelAbility;
import xyz.pixelatedw.mineminenomi.abilities.cyborg.ColaOverdriveAbility;
import xyz.pixelatedw.mineminenomi.abilities.cyborg.CoupDeBooAbility;
import xyz.pixelatedw.mineminenomi.abilities.cyborg.CoupDeVentAbility;
import xyz.pixelatedw.mineminenomi.abilities.cyborg.CyborgPassiveBonusesAbility;
import xyz.pixelatedw.mineminenomi.abilities.cyborg.FreshFireAbility;
import xyz.pixelatedw.mineminenomi.abilities.cyborg.RadicalBeamAbility;
import xyz.pixelatedw.mineminenomi.abilities.cyborg.SouthlandSuplexAbility;
import xyz.pixelatedw.mineminenomi.abilities.cyborg.StrongRightAbility;
import xyz.pixelatedw.mineminenomi.abilities.doctor.AntidoteShotAbility;
import xyz.pixelatedw.mineminenomi.abilities.doctor.DopingAbility;
import xyz.pixelatedw.mineminenomi.abilities.doctor.FailedExperimentAbility;
import xyz.pixelatedw.mineminenomi.abilities.doctor.FirstAidAbility;
import xyz.pixelatedw.mineminenomi.abilities.doctor.MedicBagExplosionAbility;
import xyz.pixelatedw.mineminenomi.abilities.doctor.VirusZoneAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.TokudaiCandleAbility;
import xyz.pixelatedw.mineminenomi.abilities.electro.EleclawAbility;
import xyz.pixelatedw.mineminenomi.abilities.electro.ElectricalLunaAbility;
import xyz.pixelatedw.mineminenomi.abilities.electro.ElectricalMissileAbility;
import xyz.pixelatedw.mineminenomi.abilities.electro.ElectricalShowerAbility;
import xyz.pixelatedw.mineminenomi.abilities.electro.ElectricalTempestaAbility;
import xyz.pixelatedw.mineminenomi.abilities.electro.MinkPassiveBonusesAbility;
import xyz.pixelatedw.mineminenomi.abilities.electro.SulongAbility;
import xyz.pixelatedw.mineminenomi.abilities.electro.SulongCheckAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.FishmanPassiveBonusesAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.KachiageHaisokuAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.KarakusagawaraSeikenAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.MizuOsuAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.MizuShuryudanAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.MizuTaihoAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.PackOfSharksAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.SamehadaShoteiAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.SharkOnToothAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.TwoFishEngineAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.UchimizuAbility;
import xyz.pixelatedw.mineminenomi.abilities.fishmankarate.YarinamiAbility;
import xyz.pixelatedw.mineminenomi.abilities.haki.BusoshokuHakiEmissionAbility;
import xyz.pixelatedw.mineminenomi.abilities.haki.BusoshokuHakiFullBodyHardeningAbility;
import xyz.pixelatedw.mineminenomi.abilities.haki.BusoshokuHakiHardeningAbility;
import xyz.pixelatedw.mineminenomi.abilities.haki.BusoshokuHakiImbuingAbility;
import xyz.pixelatedw.mineminenomi.abilities.haki.BusoshokuHakiInternalDestructionAbility;
import xyz.pixelatedw.mineminenomi.abilities.haki.HaoshokuHakiAbility;
import xyz.pixelatedw.mineminenomi.abilities.haki.HaoshokuHakiInfusionAbility;
import xyz.pixelatedw.mineminenomi.abilities.haki.KenbunshokuHakiAuraAbility;
import xyz.pixelatedw.mineminenomi.abilities.haki.KenbunshokuHakiFutureSightAbility;
import xyz.pixelatedw.mineminenomi.abilities.ittoryu.HiryuKaenAbility;
import xyz.pixelatedw.mineminenomi.abilities.ittoryu.SanbyakurokujuPoundHoAbility;
import xyz.pixelatedw.mineminenomi.abilities.ittoryu.ShiShishiSonsonAbility;
import xyz.pixelatedw.mineminenomi.abilities.ittoryu.YakkodoriAbility;
import xyz.pixelatedw.mineminenomi.abilities.mandemontactics.DemonicDanceAbility;
import xyz.pixelatedw.mineminenomi.abilities.mandemontactics.DemonicDashAbility;
import xyz.pixelatedw.mineminenomi.abilities.mandemontactics.DemonicSmashAbility;
import xyz.pixelatedw.mineminenomi.abilities.marineloyalty.MusterAbility;
import xyz.pixelatedw.mineminenomi.abilities.marineloyalty.SmallMusterAbility;
import xyz.pixelatedw.mineminenomi.abilities.rokushiki.GeppoAbility;
import xyz.pixelatedw.mineminenomi.abilities.rokushiki.KamieAbility;
import xyz.pixelatedw.mineminenomi.abilities.rokushiki.RankyakuAbility;
import xyz.pixelatedw.mineminenomi.abilities.rokushiki.RokuoganAbility;
import xyz.pixelatedw.mineminenomi.abilities.rokushiki.ShiganAbility;
import xyz.pixelatedw.mineminenomi.abilities.rokushiki.SoruAbility;
import xyz.pixelatedw.mineminenomi.abilities.rokushiki.TekkaiAbility;
import xyz.pixelatedw.mineminenomi.abilities.santoryu.OTatsumakiAbility;
import xyz.pixelatedw.mineminenomi.abilities.sniper.HiNoToriBoshiAbility;
import xyz.pixelatedw.mineminenomi.abilities.sniper.HissatsuAbility;
import xyz.pixelatedw.mineminenomi.abilities.sniper.KaenBoshiAbility;
import xyz.pixelatedw.mineminenomi.abilities.sniper.KemuriBoshiAbility;
import xyz.pixelatedw.mineminenomi.abilities.sniper.NemuriBoshiAbility;
import xyz.pixelatedw.mineminenomi.abilities.sniper.RenpatsuNamariBoshiAbility;
import xyz.pixelatedw.mineminenomi.abilities.sniper.SakuretsuSabotenBoshiAbility;
import xyz.pixelatedw.mineminenomi.abilities.sniper.TetsuBoshiAbility;
import xyz.pixelatedw.mineminenomi.abilities.sniper.TokuyoAburaBoshiAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.GroundSeccoAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.SablesGuardAbility;
import xyz.pixelatedw.mineminenomi.abilities.supa.AtomicRushAbility;
import xyz.pixelatedw.mineminenomi.api.WyDebug;
import xyz.pixelatedw.mineminenomi.api.abilities.AbilityCore;
import xyz.pixelatedw.mineminenomi.api.abilities.AbilitySet;
import xyz.pixelatedw.mineminenomi.api.abilities.IAbility;
import xyz.pixelatedw.mineminenomi.api.helpers.AbilityGroups;

public class ModAbilities {
   public static final AbilitySet HAKI_ABILITIES;
   public static final AbilitySet MARINE_ABILITIES;
   public static final AbilitySet HUMAN_ABILITIES;
   public static final AbilitySet FISHMAN_ABILITIES;
   public static final AbilitySet CYBORG_ABILITIES;
   public static final AbilitySet MINK_ABILITIES;
   public static final AbilitySet SWORDSMAN_ABILITIES;
   public static final AbilitySet SNIPER_ABILITIES;
   public static final AbilitySet DOCTOR_ABILITIES;
   public static final AbilitySet ART_OF_WEATHER_ABILITIES;
   public static final AbilitySet BLACK_LEG_ABILITIES;
   public static final AbilitySet BRAWLER_ABILITIES;
   public static final AbilitySet EXTENDED_FISHMAN_ABILITIES;
   public static final AbilitySet MAN_DEMON_TACTICS_ABILITIES;
   public static final AbilitySet CARNIVAL_TRICKS_ABILITIES;

   public static void init() {
      addAbilityGroup("haki", HAKI_ABILITIES);
      addAbilityGroup("human", HUMAN_ABILITIES);
      addAbilityGroup("fishman", FISHMAN_ABILITIES);
      addAbilityGroup("cyborg", CYBORG_ABILITIES);
      addAbilityGroup("mink", MINK_ABILITIES);
      addAbilityGroup("swordsman", SWORDSMAN_ABILITIES);
      addAbilityGroup("sniper", SNIPER_ABILITIES);
      addAbilityGroup("doctor", DOCTOR_ABILITIES);
      addAbilityGroup("art_of_weather", ART_OF_WEATHER_ABILITIES);
      addAbilityGroup("black_leg", BLACK_LEG_ABILITIES);
      addAbilityGroup("brawler", BRAWLER_ABILITIES);
      addAbilityGroup("extended_fishman", EXTENDED_FISHMAN_ABILITIES);
      addAbilityGroup("man_demon_tactics", MAN_DEMON_TACTICS_ABILITIES);
      addAbilityGroup("carnival_tricks", CARNIVAL_TRICKS_ABILITIES);
      registerAbility(TestPartsAbility.INSTANCE);
      registerAbility(CommandAbility.INSTANCE);
      registerAbility(KnockdownAbility.INSTANCE);
      registerAbility(EmptyHandsAbility.INSTANCE);
      registerAbility(TakedownKickAbility.INSTANCE);
      registerAbility(ZoomAbility.INSTANCE);
      registerAbility(GunArrayAbility.INSTANCE);
      registerAbility(MH5Ability.INSTANCE);
      registerAbility(WootzNetLauncherAbility.INSTANCE);
      registerAbility(PearlFireAbility.INSTANCE);
      registerAbility(ColaBackpackBonusAbility.INSTANCE);
      registerAbility(PunchRushAbility.INSTANCE);
      registerAbility(ChargedPunchAbility.INSTANCE);
      registerAbility(ChargedCleaveAbility.INSTANCE);
      registerAbility(AtomicRushAbility.INSTANCE);
      registerAbility(TokudaiCandleAbility.INSTANCE);
      registerAbility(KaenBoshiAbility.INSTANCE);
      registerAbility(DamageAbsorptionAbility.INSTANCE);
      registerAbility(TackleAbility.INSTANCE);
      registerAbility(BellyFlopAbility.INSTANCE);
      registerAbility(SlamAbility.INSTANCE);
      registerAbility(WeaponThrowAbility.INSTANCE);
      registerAbility(LeapAbility.INSTANCE);
      registerAbility(StealPunchAbility.INSTANCE);
      registerAbility(WeaponSpinAbility.INSTANCE);
      registerAbility(TailSpinAbility.INSTANCE);
      registerAbility(StealthFootAbility.INSTANCE);
      registerAbility(ShakushiAbility.INSTANCE);
      registerAbility(BakudanAbility.INSTANCE);
      registerAbility(SablesGuardAbility.INSTANCE);
      registerAbility(GroundSeccoAbility.INSTANCE);
      registerAbility(GrabLockAbility.INSTANCE);
      registerAbility(HookGrabAbility.INSTANCE);
      registerAbility(BombThrowAbility.INSTANCE);
      registerAbility(HonkAbility.INSTANCE);
      registerAbility(OneTwoJangoAbility.INSTANCE);
      registerAbility(BattoStrikeAbility.INSTANCE);
      if (WyDebug.isDebug()) {
         registerAbility(TestAbility.INSTANCE);
      }

   }

   private static void addAbilityGroup(String name, AbilitySet set) {
      AbilityGroups.addStandaloneGroup(ResourceLocation.fromNamespaceAndPath("mineminenomi", name), set);
   }

   private static <A extends IAbility> void registerAbility(RegistryObject<AbilityCore<A>> core) {
   }

   static {
      HAKI_ABILITIES = new AbilitySet(new RegistryObject[]{BusoshokuHakiHardeningAbility.INSTANCE, BusoshokuHakiFullBodyHardeningAbility.INSTANCE, BusoshokuHakiEmissionAbility.INSTANCE, BusoshokuHakiInternalDestructionAbility.INSTANCE, BusoshokuHakiImbuingAbility.INSTANCE, KenbunshokuHakiAuraAbility.INSTANCE, KenbunshokuHakiFutureSightAbility.INSTANCE, HaoshokuHakiAbility.INSTANCE, HaoshokuHakiInfusionAbility.INSTANCE});
      MARINE_ABILITIES = new AbilitySet(new RegistryObject[]{SmallMusterAbility.INSTANCE, MusterAbility.INSTANCE});
      HUMAN_ABILITIES = new AbilitySet(new RegistryObject[]{SoruAbility.INSTANCE, TekkaiAbility.INSTANCE, ShiganAbility.INSTANCE, RankyakuAbility.INSTANCE, KamieAbility.INSTANCE, GeppoAbility.INSTANCE, RokuoganAbility.INSTANCE});
      FISHMAN_ABILITIES = new AbilitySet(new RegistryObject[]{UchimizuAbility.INSTANCE, SamehadaShoteiAbility.INSTANCE, PackOfSharksAbility.INSTANCE, KarakusagawaraSeikenAbility.INSTANCE, KachiageHaisokuAbility.INSTANCE, TwoFishEngineAbility.INSTANCE, YarinamiAbility.INSTANCE, FishmanPassiveBonusesAbility.INSTANCE});
      CYBORG_ABILITIES = new AbilitySet(new RegistryObject[]{StrongRightAbility.INSTANCE, RadicalBeamAbility.INSTANCE, FreshFireAbility.INSTANCE, CoupDeBooAbility.INSTANCE, CoupDeVentAbility.INSTANCE, ColaOverdriveAbility.INSTANCE, SouthlandSuplexAbility.INSTANCE, ColaFuelAbility.INSTANCE, CyborgPassiveBonusesAbility.INSTANCE});
      MINK_ABILITIES = new AbilitySet(new RegistryObject[]{EleclawAbility.INSTANCE, ElectricalMissileAbility.INSTANCE, ElectricalTempestaAbility.INSTANCE, ElectricalShowerAbility.INSTANCE, ElectricalLunaAbility.INSTANCE, SulongAbility.INSTANCE, SulongCheckAbility.INSTANCE, MinkPassiveBonusesAbility.INSTANCE});
      SWORDSMAN_ABILITIES = new AbilitySet(new RegistryObject[]{ShiShishiSonsonAbility.INSTANCE, YakkodoriAbility.INSTANCE, SanbyakurokujuPoundHoAbility.INSTANCE, OTatsumakiAbility.INSTANCE, HiryuKaenAbility.INSTANCE});
      SNIPER_ABILITIES = new AbilitySet(new RegistryObject[]{HiNoToriBoshiAbility.INSTANCE, KemuriBoshiAbility.INSTANCE, RenpatsuNamariBoshiAbility.INSTANCE, SakuretsuSabotenBoshiAbility.INSTANCE, TetsuBoshiAbility.INSTANCE, TokuyoAburaBoshiAbility.INSTANCE, NemuriBoshiAbility.INSTANCE, HissatsuAbility.INSTANCE});
      DOCTOR_ABILITIES = new AbilitySet(new RegistryObject[]{FirstAidAbility.INSTANCE, MedicBagExplosionAbility.INSTANCE, FailedExperimentAbility.INSTANCE, DopingAbility.INSTANCE, AntidoteShotAbility.INSTANCE, VirusZoneAbility.INSTANCE});
      ART_OF_WEATHER_ABILITIES = new AbilitySet(new RegistryObject[]{HeatBallAbility.INSTANCE, CoolBallAbility.INSTANCE, WeatherCloudTempo.INSTANCE, ThunderBallAbility.INSTANCE, ThunderboltTempo.INSTANCE, ThunderstormTempo.INSTANCE, ThunderLanceTempo.INSTANCE, FogTempo.INSTANCE, MirageTempo.INSTANCE, RainTempo.INSTANCE, WeatherEggAbility.INSTANCE, GustSwordAbility.INSTANCE, HeatEggTempo.INSTANCE, CycloneTempo.INSTANCE});
      BLACK_LEG_ABILITIES = new AbilitySet(new RegistryObject[]{DiableJambeAbility.INSTANCE, SkywalkAbility.INSTANCE, AntiMannerKickCourseAbility.INSTANCE, ExtraHachisAbility.INSTANCE, PartyTableKickCourseAbility.INSTANCE, ConcasseAbility.INSTANCE, BienCuitGrillShotAbility.INSTANCE, BlackLegPassiveBonusesAbility.INSTANCE});
      BRAWLER_ABILITIES = new AbilitySet(new RegistryObject[]{GenkotsuMeteorAbility.INSTANCE, KingPunchAbility.INSTANCE, HakaiHoAbility.INSTANCE, JishinHoAbility.INSTANCE, SpinningBrawlAbility.INSTANCE, SuplexAbility.INSTANCE, BrawlerPassiveBonusesAbility.INSTANCE});
      EXTENDED_FISHMAN_ABILITIES = new AbilitySet(new RegistryObject[]{SharkOnToothAbility.INSTANCE, MizuTaihoAbility.INSTANCE, MizuOsuAbility.INSTANCE, MizuShuryudanAbility.INSTANCE});
      MAN_DEMON_TACTICS_ABILITIES = new AbilitySet(new RegistryObject[]{DemonicDanceAbility.INSTANCE, DemonicSmashAbility.INSTANCE, DemonicDashAbility.INSTANCE});
      CARNIVAL_TRICKS_ABILITIES = new AbilitySet(new RegistryObject[]{IchirinZashiAbility.INSTANCE, KamikazeHyakkomaGekijoAbility.INSTANCE, KajiOyajiAbility.INSTANCE});
   }
}
