package xyz.pixelatedw.mineminenomi.init;

import net.minecraft.resources.ResourceLocation;

public class ModLootTables {
   public static final ResourceLocation SMALL_PIRATE_SHIP_SUPPLIES_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/pirate_small_ship/supplies");
   public static final ResourceLocation MEDIUM_PIRATE_SHIP_SUPPLIES_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/pirate_medium_ship/supplies");
   public static final ResourceLocation MEDIUM_PIRATE_SHIP_FOOD_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/pirate_medium_ship/food");
   public static final ResourceLocation MEDIUM_PIRATE_SHIP_CAPTAIN_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/pirate_medium_ship/captain");
   public static final ResourceLocation LARGE_PIRATE_SHIP_SUPPLIES_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/pirate_large_ship/supplies");
   public static final ResourceLocation LARGE_PIRATE_SHIP_WEAPONS_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/pirate_large_ship/weapons");
   public static final ResourceLocation LARGE_PIRATE_SHIP_CAPTAIN_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/pirate_large_ship/captain");
   public static final ResourceLocation LARGE_PIRATE_SHIP_TREASURE_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/pirate_large_ship/treasure");
   public static final ResourceLocation GHOST_SHIP_SUPPLIES_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/ghost_ship/supplies");
   public static final ResourceLocation GHOST_SHIP_CAPTAIN_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/ghost_ship/captain");
   public static final ResourceLocation MARINE_CAMP_SMALL_TENT_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_camp/small_tent");
   public static final ResourceLocation MARINE_CAMP_LARGE_TENT_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_camp/large_tent");
   public static final ResourceLocation BANDIT_CAMP_SMALL_TENT_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_camp/small_tent");
   public static final ResourceLocation BANDIT_CAMP_LARGE_TENT_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_camp/large_tent");
   public static final ResourceLocation SMALL_BANDIT_BASE_GOLD_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_small_base/gold");
   public static final ResourceLocation SMALL_BANDIT_BASE_MINE_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_small_base/mine");
   public static final ResourceLocation SMALL_BANDIT_BASE_LAB_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_small_base/lab");
   public static final ResourceLocation SMALL_BANDIT_BASE_ORES_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_small_base/ores");
   public static final ResourceLocation SMALL_MARINE_BASE_CAPTAIN_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_small_base/captain");
   public static final ResourceLocation SMALL_MARINE_BASE_FOOD_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_small_base/food");
   public static final ResourceLocation SMALL_MARINE_BASE_DORM_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_small_base/dorm");
   public static final ResourceLocation LARGE_MARINE_BASE_CAPTAIN_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_large_base/captain");
   public static final ResourceLocation LARGE_MARINE_BASE_FOOD_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_large_base/food");
   public static final ResourceLocation LARGE_MARINE_BASE_GENERIC_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_large_base/generic");
   public static final ResourceLocation LARGE_MARINE_BASE_LAB_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_large_base/lab");
   public static final ResourceLocation LARGE_MARINE_SHIP_CAPTAIN_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_battleship/captain");
   public static final ResourceLocation LARGE_MARINE_SHIP_SUPPLIES_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_battleship/supplies");
   public static final ResourceLocation LARGE_MARINE_SHIP_RUM_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/marine_battleship/rum");
   public static final ResourceLocation LARGE_BANDIT_BASE_TOWER_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_large_base/tower");
   public static final ResourceLocation LARGE_BANDIT_BASE_TENT_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_large_base/tent");
   public static final ResourceLocation LARGE_BANDIT_BASE_FOOD_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_large_base/food");
   public static final ResourceLocation LARGE_BANDIT_BASE_DORM_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_large_base/dorm");
   public static final ResourceLocation LARGE_BANDIT_BASE_SECRET_STASH_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/bandit_large_base/secret_stash");
   public static final ResourceLocation CARAVAN_EASY_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/caravan/easy");
   public static final ResourceLocation CARAVAN_HARD_CHEST = ResourceLocation.fromNamespaceAndPath("mineminenomi", "chests/caravan/hard");
   public static final ResourceLocation SKYPIEAN_TRADER = ResourceLocation.fromNamespaceAndPath("mineminenomi", "entities/trader/skypiean_trader");
   public static final ResourceLocation PIRATE_TRADER = ResourceLocation.fromNamespaceAndPath("mineminenomi", "entities/trader/pirate_trader");
   public static final ResourceLocation MARINE_TRADER = ResourceLocation.fromNamespaceAndPath("mineminenomi", "entities/trader/marine_trader");
   public static final ResourceLocation WOODEN_BOX = ResourceLocation.fromNamespaceAndPath("mineminenomi", "dfboxes/wooden_box");
   public static final ResourceLocation IRON_BOX = ResourceLocation.fromNamespaceAndPath("mineminenomi", "dfboxes/iron_box");
   public static final ResourceLocation GOLDEN_BOX = ResourceLocation.fromNamespaceAndPath("mineminenomi", "dfboxes/golden_box");
   public static final ResourceLocation AXE_DIAL_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/axe_dial");
   public static final ResourceLocation BREATH_DIAL_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/breath_dial");
   public static final ResourceLocation DEN_DEN_MUSHI_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/den_den_mushi");
   public static final ResourceLocation DESIGN_BARREL_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/design_barrel");
   public static final ResourceLocation EISEN_DIAL_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/eisen_dial");
   public static final ResourceLocation FLAG_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/flag");
   public static final ResourceLocation FLAME_DIAL_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/flame_dial");
   public static final ResourceLocation FLASH_DIAL_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/flash_dial");
   public static final ResourceLocation IMPACT_DIAL_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/impact_dial");
   public static final ResourceLocation KAIROSEKI_BARS_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/kairoseki_bars");
   public static final ResourceLocation KAIROSEKI_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/kairoseki_block");
   public static final ResourceLocation KAIROSEKI_ORE_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/kairoseki_ore");
   public static final ResourceLocation DEEPSLATE_KAIROSEKI_ORE_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/deepslate_kairoseki_ore");
   public static final ResourceLocation MANGROVE_LOG_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/mangrove_log");
   public static final ResourceLocation MANGROVE_PLANKS_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/mangrove_planks");
   public static final ResourceLocation MANGROVE_WOOD_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/mangrove_wood");
   public static final ResourceLocation MILKY_DIAL_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/milky_dial");
   public static final ResourceLocation REJECT_DIAL_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/reject_dial");
   public static final ResourceLocation SKY_BLOCK_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/sky_block");
   public static final ResourceLocation STRIPPED_MANGROVE_LOG_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/stripped_mangrove_log");
   public static final ResourceLocation STRIPPED_MANGROVE_WOOD_BLOCK = ResourceLocation.fromNamespaceAndPath("mineminenomi", "blocks/stripped_mangrove_wood");
}
