package xyz.pixelatedw.mineminenomi.init;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.PlayerModel;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.renderer.entity.EntityRenderer;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.LivingEntity;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.registries.RegistryObject;
import xyz.pixelatedw.mineminenomi.api.WyHelper;
import xyz.pixelatedw.mineminenomi.api.entities.charactercreator.Race;
import xyz.pixelatedw.mineminenomi.api.morph.MorphInfo;
import xyz.pixelatedw.mineminenomi.api.morph.RacialRenderFeature;
import xyz.pixelatedw.mineminenomi.models.entities.AwakeningSmokeModel;
import xyz.pixelatedw.mineminenomi.models.morphs.AllosaurusWalkModel;
import xyz.pixelatedw.mineminenomi.models.morphs.AxolotlHeavyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.AxolotlWalkModel;
import xyz.pixelatedw.mineminenomi.models.morphs.BisonHeavyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.BisonWalkModel;
import xyz.pixelatedw.mineminenomi.models.morphs.BrachiosaurusGuardModel;
import xyz.pixelatedw.mineminenomi.models.morphs.BrachiosaurusHeavyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.CandleChampionModel;
import xyz.pixelatedw.mineminenomi.models.morphs.DaibutsuModel;
import xyz.pixelatedw.mineminenomi.models.morphs.GearFourthModel;
import xyz.pixelatedw.mineminenomi.models.morphs.GiraffeHeavyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.GiraffeWalkModel;
import xyz.pixelatedw.mineminenomi.models.morphs.KameGuardModel;
import xyz.pixelatedw.mineminenomi.models.morphs.LeopardHeavyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.LeopardWalkModel;
import xyz.pixelatedw.mineminenomi.models.morphs.MammothGuardModel;
import xyz.pixelatedw.mineminenomi.models.morphs.MoguHeavyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.Phoenix2Model;
import xyz.pixelatedw.mineminenomi.models.morphs.PhoenixFlyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.PteranodonFlyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.SaiHeavyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.SaiWalkModel;
import xyz.pixelatedw.mineminenomi.models.morphs.ShinokuniModel;
import xyz.pixelatedw.mineminenomi.models.morphs.VenomDemonModel;
import xyz.pixelatedw.mineminenomi.models.morphs.YomiModel;
import xyz.pixelatedw.mineminenomi.models.morphs.ZouGuardModel;
import xyz.pixelatedw.mineminenomi.models.morphs.ZouHeavyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.AllosaurusHeavyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.BaraCarBodyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.BaraCarWheelsModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.DamnedPunkModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.FishmanGarfishModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.FishmanRayModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.FishmanSawsharkModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.GearFifthRunningModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.HanaCalendulaModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.HanaWingsModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.KameWalkModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.MammothHeavyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.MinkBunnyModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.MinkDogModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.MinkLionModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.PhoenixAssaultModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.PteranodonAssaultModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.PunkCornaDioModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.PunkGibsonModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.SkypieanModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.SparClawModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.SpringLegsModel;
import xyz.pixelatedw.mineminenomi.morphs.bane.SpringLegsMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.bara.BaraCarMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.bara.BaraCircusMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.bara.BaraFestivalMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.bara.BaraHoMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.bara.BaraSplitMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.deka.DekaMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.doku.VenomDemonMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.doru.CandleChampionMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.gasu.ShinokuniMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.gomu.GearFifthMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.gomu.GearFourthMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.gomu.GomuGiantMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.goro.VoltAmaruMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.hana.HanaWingsMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.hitodaibutsu.HitoDaibutsuMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.horu.GanmenSeichoMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.jiki.DamnedPunkMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.jiki.PunkCornaDioMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.jiki.PunkGibsonMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.kage.ShadowsAsgardMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.kame.KameGuardMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.kame.KameWalkMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.karu.IngaZarashiMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.mini.MiniMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.mogu.MoguHeavyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.nekoleopard.LeopardHeavyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.nekoleopard.LeopardWalkMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.ryuallosaurus.AllosaurusHeavyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.ryuallosaurus.AllosaurusWalkMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.ryubrachiosaurus.BrachiosaurusGuardMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.ryubrachiosaurus.BrachiosaurusHeavyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.ryupteranodon.PteranodonAssaultMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.ryupteranodon.PteranodonFlyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.sai.SaiHeavyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.sai.SaiWalkMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.saraaxolotl.AxolotlHeavyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.saraaxolotl.AxolotlWalkMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.supa.SparClawMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.toriphoenix.PhoenixAssaultMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.toriphoenix.PhoenixFlyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.ushibison.BisonHeavyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.ushibison.BisonWalkMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.ushigiraffe.GiraffeHeavyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.ushigiraffe.GiraffeWalkMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.yomi.YomiMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.zou.ZouGuardMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.zou.ZouHeavyMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.zoumammoth.MammothGuardMorphInfo;
import xyz.pixelatedw.mineminenomi.morphs.zoumammoth.MammothHeavyMorphInfo;
import xyz.pixelatedw.mineminenomi.renderers.morphs.FlyPointRenderer;
import xyz.pixelatedw.mineminenomi.renderers.morphs.GearFourthPointRenderer;
import xyz.pixelatedw.mineminenomi.renderers.morphs.MorphRenderer;
import xyz.pixelatedw.mineminenomi.renderers.morphs.PlayerMorphRenderer;

public class ModMorphs {
   public static final RegistryObject<MorphInfo> ALLOSAURUS_HEAVY = ModRegistry.<MorphInfo>registerMorph("allosaurus_heavy", AllosaurusHeavyMorphInfo::new);
   public static final RegistryObject<MorphInfo> ALLOSAURUS_WALK = ModRegistry.<MorphInfo>registerMorph("allosaurus_walk", AllosaurusWalkMorphInfo::new);
   public static final RegistryObject<MorphInfo> AXOLOTL_HEAVY = ModRegistry.<MorphInfo>registerMorph("axolotl_heavy", AxolotlHeavyMorphInfo::new);
   public static final RegistryObject<MorphInfo> AXOLOTL_WALK = ModRegistry.<MorphInfo>registerMorph("axolotl_walk", AxolotlWalkMorphInfo::new);
   public static final RegistryObject<MorphInfo> BISON_HEAVY = ModRegistry.<MorphInfo>registerMorph("bison_heavy", BisonHeavyMorphInfo::new);
   public static final RegistryObject<MorphInfo> BISON_WALK = ModRegistry.<MorphInfo>registerMorph("bison_walk", BisonWalkMorphInfo::new);
   public static final RegistryObject<MorphInfo> BRACHIO_HEAVY = ModRegistry.<MorphInfo>registerMorph("brachio_heavy", BrachiosaurusHeavyMorphInfo::new);
   public static final RegistryObject<MorphInfo> BRACHIO_GUARD = ModRegistry.<MorphInfo>registerMorph("brachio_guard", BrachiosaurusGuardMorphInfo::new);
   public static final RegistryObject<MorphInfo> GIRAFFE_HEAVY = ModRegistry.<MorphInfo>registerMorph("giraffe_heavy", GiraffeHeavyMorphInfo::new);
   public static final RegistryObject<MorphInfo> GIRAFFE_WALK = ModRegistry.<MorphInfo>registerMorph("giraffe_walk", GiraffeWalkMorphInfo::new);
   public static final RegistryObject<MorphInfo> KAME_GUARD = ModRegistry.<MorphInfo>registerMorph("kame_guard", KameGuardMorphInfo::new);
   public static final RegistryObject<MorphInfo> KAME_WALK = ModRegistry.<MorphInfo>registerMorph("kame_walk", KameWalkMorphInfo::new);
   public static final RegistryObject<MorphInfo> LEOPARD_HEAVY = ModRegistry.<MorphInfo>registerMorph("leopard_heavy", LeopardHeavyMorphInfo::new);
   public static final RegistryObject<MorphInfo> LEOPARD_WALK = ModRegistry.<MorphInfo>registerMorph("leopard_walk", LeopardWalkMorphInfo::new);
   public static final RegistryObject<MorphInfo> MAMMOTH_HEAVY = ModRegistry.<MorphInfo>registerMorph("mammoth_heavy", MammothHeavyMorphInfo::new);
   public static final RegistryObject<MorphInfo> MAMMOTH_GUARD = ModRegistry.<MorphInfo>registerMorph("mammoth_guard", MammothGuardMorphInfo::new);
   public static final RegistryObject<MorphInfo> ZOU_HEAVY = ModRegistry.<MorphInfo>registerMorph("zou_heavy", ZouHeavyMorphInfo::new);
   public static final RegistryObject<MorphInfo> ZOU_GUARD = ModRegistry.<MorphInfo>registerMorph("zou_guard", ZouGuardMorphInfo::new);
   public static final RegistryObject<MorphInfo> MOGU_HEAVY = ModRegistry.<MorphInfo>registerMorph("mogu_heavy", MoguHeavyMorphInfo::new);
   public static final RegistryObject<MorphInfo> PHOENIX_ASSAULT = ModRegistry.<MorphInfo>registerMorph("phoenix_assault", PhoenixAssaultMorphInfo::new);
   public static final RegistryObject<MorphInfo> PHOENIX_FLY = ModRegistry.<MorphInfo>registerMorph("phoenix_fly", PhoenixFlyMorphInfo::new);
   public static final RegistryObject<MorphInfo> PTERA_ASSAULT = ModRegistry.<MorphInfo>registerMorph("ptera_assault", PteranodonAssaultMorphInfo::new);
   public static final RegistryObject<MorphInfo> PTERA_FLY = ModRegistry.<MorphInfo>registerMorph("ptera_fly", PteranodonFlyMorphInfo::new);
   public static final RegistryObject<MorphInfo> SAI_HEAVY = ModRegistry.<MorphInfo>registerMorph("sai_heavy", SaiHeavyMorphInfo::new);
   public static final RegistryObject<MorphInfo> SAI_WALK = ModRegistry.<MorphInfo>registerMorph("sai_walk", SaiWalkMorphInfo::new);
   public static final RegistryObject<MorphInfo> CANDLE_CHAMPION = ModRegistry.<MorphInfo>registerMorph("candle_champion", CandleChampionMorphInfo::new);
   public static final RegistryObject<MorphInfo> VENOM_DEMON = ModRegistry.<MorphInfo>registerMorph("venom_demon", VenomDemonMorphInfo::new);
   public static final RegistryObject<MorphInfo> SPRING_LEGS = ModRegistry.<MorphInfo>registerMorph("spring_lengs", SpringLegsMorphInfo::new);
   public static final RegistryObject<MorphInfo> GEAR_FOURTH = ModRegistry.<MorphInfo>registerMorph("gear_fourth", GearFourthMorphInfo::new);
   public static final RegistryObject<MorphInfo> GEAR_FIFTH = ModRegistry.<MorphInfo>registerMorph("gear_fifth", GearFifthMorphInfo::new);
   public static final RegistryObject<MorphInfo> GOMU_GIGANT = ModRegistry.<MorphInfo>registerMorph("gomu_gigant", GomuGiantMorphInfo::new);
   public static final RegistryObject<MorphInfo> DAIBUTSU = ModRegistry.<MorphInfo>registerMorph("daibutsu", HitoDaibutsuMorphInfo::new);
   public static final RegistryObject<MorphInfo> INGA_ZARASHI = ModRegistry.<MorphInfo>registerMorph("inga_zarashi", IngaZarashiMorphInfo::new);
   public static final RegistryObject<MorphInfo> DEKA = ModRegistry.<MorphInfo>registerMorph("deka", DekaMorphInfo::new);
   public static final RegistryObject<MorphInfo> MINI = ModRegistry.<MorphInfo>registerMorph("mini", MiniMorphInfo::new);
   public static final RegistryObject<MorphInfo> SHINOKUNI = ModRegistry.<MorphInfo>registerMorph("shinokuni", ShinokuniMorphInfo::new);
   public static final RegistryObject<MorphInfo> SHADOWS_ASGARD = ModRegistry.<MorphInfo>registerMorph("shadows_asgard", ShadowsAsgardMorphInfo::new);
   public static final RegistryObject<MorphInfo> VOLT_AMARU = ModRegistry.<MorphInfo>registerMorph("volt_amaru", VoltAmaruMorphInfo::new);
   public static final RegistryObject<MorphInfo> YOMI_SKELETON = ModRegistry.<MorphInfo>registerMorph("yomi_skeleton", YomiMorphInfo::new);
   public static final RegistryObject<MorphInfo> BARA_CAR = ModRegistry.<MorphInfo>registerMorph("bara_car", BaraCarMorphInfo::new);
   public static final RegistryObject<MorphInfo> BARA_HO = ModRegistry.<MorphInfo>registerMorph("bara_ho", BaraHoMorphInfo::new);
   public static final RegistryObject<MorphInfo> BARA_CIRCUS = ModRegistry.<MorphInfo>registerMorph("bara_circus", BaraCircusMorphInfo::new);
   public static final RegistryObject<MorphInfo> BARA_FESTIVAL = ModRegistry.<MorphInfo>registerMorph("bara_festival", BaraFestivalMorphInfo::new);
   public static final RegistryObject<MorphInfo> BARA_SPLIT = ModRegistry.<MorphInfo>registerMorph("bara_split", BaraSplitMorphInfo::new);
   public static final RegistryObject<MorphInfo> PUNK_GIBSON = ModRegistry.<MorphInfo>registerMorph("punk_gibson", PunkGibsonMorphInfo::new);
   public static final RegistryObject<MorphInfo> DAMNED_PUNK = ModRegistry.<MorphInfo>registerMorph("damned_punk", DamnedPunkMorphInfo::new);
   public static final RegistryObject<MorphInfo> PUNK_CORNA_DIO = ModRegistry.<MorphInfo>registerMorph("punk_corna_dio", PunkCornaDioMorphInfo::new);
   public static final RegistryObject<MorphInfo> GANMEN_SEICHO = ModRegistry.<MorphInfo>registerMorph("ganmen_seicho", GanmenSeichoMorphInfo::new);
   public static final RegistryObject<MorphInfo> HANA_WINGS = ModRegistry.<MorphInfo>registerMorph("hana_wings", HanaWingsMorphInfo::new);
   public static final RegistryObject<MorphInfo> HANA_CALENDULA = ModRegistry.<MorphInfo>registerMorph("hana_calendula", HanaWingsMorphInfo::new);
   public static final RegistryObject<MorphInfo> SPAR_CLAW = ModRegistry.<MorphInfo>registerMorph("spar_claw", SparClawMorphInfo::new);

   public static void init() {
   }

   public static class Client {
      public static final Map<MorphInfo, EntityRenderer<? extends LivingEntity>> MORPH_RENDERERS = new HashMap();
      public static final Map<Race, RacialRenderFeature> RACIAL_RENDERERS = new HashMap();
      public static final Map<MorphInfo, EntityModel<? extends LivingEntity>> PARTIAL_MORPHS_RENDERERS = new HashMap();
      private static final ResourceLocation MINK_BUNNY_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/morphs/mink_bunny.png");
      private static final ResourceLocation MINK_DOG_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/morphs/mink_dog.png");
      private static final ResourceLocation MINK_LION_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/morphs/mink_lion.png");
      private static final ResourceLocation SKYPIEAN_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/morphs/skypiean.png");
      private static final ResourceLocation FISHMAN_SAWSHARK_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/morphs/fishman_sawshark.png");
      private static final ResourceLocation FISHMAN_RAY_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/morphs/fishman_ray.png");
      private static final ResourceLocation FISHMAN_GARFISH_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/morphs/fishman_garfish.png");

      public static void registerLayers(EntityRenderersEvent.RegisterLayerDefinitions event) {
         event.registerLayerDefinition(AwakeningSmokeModel.LAYER_LOCATION, AwakeningSmokeModel::createBodyLayer);
         event.registerLayerDefinition(BisonHeavyModel.LAYER_LOCATION, BisonHeavyModel::createBodyLayer);
         event.registerLayerDefinition(BisonWalkModel.LAYER_LOCATION, BisonWalkModel::createBodyLayer);
         event.registerLayerDefinition(CandleChampionModel.LAYER_LOCATION, CandleChampionModel::createBodyLayer);
         event.registerLayerDefinition(ShinokuniModel.LAYER_LOCATION, ShinokuniModel::createBodyLayer);
         event.registerLayerDefinition(YomiModel.LAYER_LOCATION, YomiModel::createBodyLayer);
         event.registerLayerDefinition(KameGuardModel.LAYER_LOCATION, KameGuardModel::createBodyLayer);
         event.registerLayerDefinition(AllosaurusWalkModel.LAYER_LOCATION, AllosaurusWalkModel::createBodyLayer);
         event.registerLayerDefinition(AxolotlHeavyModel.LAYER_LOCATION, AxolotlHeavyModel::createBodyLayer);
         event.registerLayerDefinition(AxolotlWalkModel.LAYER_LOCATION, AxolotlWalkModel::createBodyLayer);
         event.registerLayerDefinition(SaiHeavyModel.LAYER_LOCATION, SaiHeavyModel::createBodyLayer);
         event.registerLayerDefinition(SaiWalkModel.LAYER_LOCATION, SaiWalkModel::createBodyLayer);
         event.registerLayerDefinition(GiraffeHeavyModel.LAYER_LOCATION, GiraffeHeavyModel::createBodyLayer);
         event.registerLayerDefinition(GiraffeWalkModel.LAYER_LOCATION, GiraffeWalkModel::createBodyLayer);
         event.registerLayerDefinition(ZouHeavyModel.LAYER_LOCATION, ZouHeavyModel::createBodyLayer);
         event.registerLayerDefinition(ZouGuardModel.LAYER_LOCATION, ZouGuardModel::createBodyLayer);
         event.registerLayerDefinition(DaibutsuModel.LAYER_LOCATION, DaibutsuModel::createBodyLayer);
         event.registerLayerDefinition(VenomDemonModel.LAYER_LOCATION, VenomDemonModel::createBodyLayer);
         event.registerLayerDefinition(PteranodonFlyModel.LAYER_LOCATION, PteranodonFlyModel::createBodyLayer);
         event.registerLayerDefinition(PhoenixFlyModel.LAYER_LOCATION, PhoenixFlyModel::createBodyLayer);
         event.registerLayerDefinition(MoguHeavyModel.LAYER_LOCATION, MoguHeavyModel::createBodyLayer);
         event.registerLayerDefinition(LeopardHeavyModel.LAYER_LOCATION, LeopardHeavyModel::createBodyLayer);
         event.registerLayerDefinition(LeopardWalkModel.LAYER_LOCATION, LeopardWalkModel::createBodyLayer);
         event.registerLayerDefinition(MammothGuardModel.LAYER_LOCATION, MammothGuardModel::createBodyLayer);
         event.registerLayerDefinition(BrachiosaurusGuardModel.LAYER_LOCATION, BrachiosaurusGuardModel::createBodyLayer);
         event.registerLayerDefinition(BrachiosaurusHeavyModel.LAYER_LOCATION, BrachiosaurusHeavyModel::createBodyLayer);
         event.registerLayerDefinition(Phoenix2Model.LAYER_LOCATION, Phoenix2Model::createBodyLayer);
         event.registerLayerDefinition(GearFourthModel.LAYER_LOCATION, GearFourthModel::createBodyLayer);
         event.registerLayerDefinition(SpringLegsModel.LAYER_LOCATION, SpringLegsModel::createBodyLayer);
         event.registerLayerDefinition(HanaWingsModel.WIDE_LAYER_LOCATION, HanaWingsModel::createWideBodyLayer);
         event.registerLayerDefinition(HanaWingsModel.SLIM_LAYER_LOCATION, HanaWingsModel::createSlimBodyLayer);
         event.registerLayerDefinition(HanaCalendulaModel.WIDE_LAYER_LOCATION, HanaCalendulaModel::createWideBodyLayer);
         event.registerLayerDefinition(HanaCalendulaModel.SLIM_LAYER_LOCATION, HanaCalendulaModel::createSlimBodyLayer);
         event.registerLayerDefinition(SparClawModel.WIDE_LAYER_LOCATION, SparClawModel::createWideBodyLayer);
         event.registerLayerDefinition(SparClawModel.SLIM_LAYER_LOCATION, SparClawModel::createSlimBodyLayer);
         event.registerLayerDefinition(KameWalkModel.LAYER_LOCATION, KameWalkModel::createBodyLayer);
         event.registerLayerDefinition(AllosaurusHeavyModel.LAYER_LOCATION, AllosaurusHeavyModel::createBodyLayer);
         event.registerLayerDefinition(GearFifthRunningModel.LAYER_LOCATION, GearFifthRunningModel::createBodyLayer);
         event.registerLayerDefinition(PunkGibsonModel.LAYER_LOCATION, PunkGibsonModel::createBodyLayer);
         event.registerLayerDefinition(DamnedPunkModel.LAYER_LOCATION, DamnedPunkModel::createBodyLayer);
         event.registerLayerDefinition(PunkCornaDioModel.LAYER_LOCATION, PunkCornaDioModel::createBodyLayer);
         event.registerLayerDefinition(PteranodonAssaultModel.LAYER_LOCATION, PteranodonAssaultModel::createBodyLayer);
         event.registerLayerDefinition(BaraCarWheelsModel.LAYER_LOCATION, BaraCarWheelsModel::createBodyLayer);
         event.registerLayerDefinition(BaraCarBodyModel.LAYER_LOCATION, BaraCarBodyModel::createBodyLayer);
         event.registerLayerDefinition(PhoenixAssaultModel.LAYER_LOCATION, PhoenixAssaultModel::createBodyLayer);
         event.registerLayerDefinition(MammothHeavyModel.LAYER_LOCATION, MammothHeavyModel::createBodyLayer);
         event.registerLayerDefinition(MinkBunnyModel.LAYER_LOCATION, MinkBunnyModel::createLayer);
         event.registerLayerDefinition(MinkDogModel.LAYER_LOCATION, MinkDogModel::createLayer);
         event.registerLayerDefinition(MinkLionModel.LAYER_LOCATION, MinkLionModel::createLayer);
         event.registerLayerDefinition(SkypieanModel.LAYER_LOCATION, SkypieanModel::createLayer);
         event.registerLayerDefinition(FishmanSawsharkModel.LAYER_LOCATION, FishmanSawsharkModel::createLayer);
         event.registerLayerDefinition(FishmanRayModel.LAYER_LOCATION, FishmanRayModel::createLayer);
         event.registerLayerDefinition(FishmanGarfishModel.LAYER_LOCATION, FishmanGarfishModel::createLayer);
      }

      public static void addLayers(EntityRenderersEvent.AddLayers event, EntityRendererProvider.Context ctx) {
         boolean isAprilFirst = WyHelper.isAprilFirst();
         BisonHeavyModel<LivingEntity> bisonHeavyModel = new BisonHeavyModel<LivingEntity>(ctx.m_174023_(BisonHeavyModel.LAYER_LOCATION));
         BisonWalkModel<LivingEntity> bisonWalkModel = new BisonWalkModel<LivingEntity>(ctx.m_174023_(BisonWalkModel.LAYER_LOCATION));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.BISON_HEAVY.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.BISON_HEAVY.get(), bisonHeavyModel)).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.BISON_WALK.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.BISON_WALK.get(), bisonWalkModel)).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.CANDLE_CHAMPION.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.CANDLE_CHAMPION.get(), new CandleChampionModel(ctx.m_174023_(CandleChampionModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.SHINOKUNI.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.SHINOKUNI.get(), new ShinokuniModel(ctx.m_174023_(ShinokuniModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.YOMI_SKELETON.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.YOMI_SKELETON.get(), new YomiModel(ctx.m_174023_(YomiModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.KAME_GUARD.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.KAME_GUARD.get(), new KameGuardModel(ctx.m_174023_(KameGuardModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.ALLOSAURUS_WALK.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.ALLOSAURUS_WALK.get(), new AllosaurusWalkModel(ctx.m_174023_(AllosaurusWalkModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.AXOLOTL_HEAVY.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.AXOLOTL_HEAVY.get(), new AxolotlHeavyModel(ctx.m_174023_(AxolotlHeavyModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.AXOLOTL_WALK.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.AXOLOTL_WALK.get(), new AxolotlWalkModel(ctx.m_174023_(AxolotlWalkModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.SAI_HEAVY.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.SAI_HEAVY.get(), new SaiHeavyModel(ctx.m_174023_(SaiHeavyModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.SAI_WALK.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.SAI_WALK.get(), new SaiWalkModel(ctx.m_174023_(SaiWalkModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.GIRAFFE_HEAVY.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.GIRAFFE_HEAVY.get(), new GiraffeHeavyModel(ctx.m_174023_(GiraffeHeavyModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.GIRAFFE_WALK.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.GIRAFFE_WALK.get(), new GiraffeWalkModel(ctx.m_174023_(GiraffeWalkModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.ZOU_HEAVY.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.ZOU_HEAVY.get(), new ZouHeavyModel(ctx.m_174023_(ZouHeavyModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.ZOU_GUARD.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.ZOU_GUARD.get(), new ZouGuardModel(ctx.m_174023_(ZouGuardModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.VENOM_DEMON.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.VENOM_DEMON.get(), new VenomDemonModel(ctx.m_174023_(VenomDemonModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.PTERA_FLY.get(), (new FlyPointRenderer.Factory((MorphInfo)ModMorphs.PTERA_FLY.get(), new PteranodonFlyModel(ctx.m_174023_(PteranodonFlyModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.PHOENIX_FLY.get(), (new FlyPointRenderer.Factory((MorphInfo)ModMorphs.PHOENIX_FLY.get(), (EntityModel)(isAprilFirst ? new Phoenix2Model(ctx.m_174023_(Phoenix2Model.LAYER_LOCATION)) : new PhoenixFlyModel(ctx.m_174023_(PhoenixFlyModel.LAYER_LOCATION))))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.MOGU_HEAVY.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.MOGU_HEAVY.get(), new MoguHeavyModel(ctx.m_174023_(MoguHeavyModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.LEOPARD_HEAVY.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.LEOPARD_HEAVY.get(), new LeopardHeavyModel(ctx.m_174023_(LeopardHeavyModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.LEOPARD_WALK.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.LEOPARD_WALK.get(), new LeopardWalkModel(ctx.m_174023_(LeopardWalkModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.MAMMOTH_GUARD.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.MAMMOTH_GUARD.get(), new MammothGuardModel(ctx.m_174023_(MammothGuardModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.BRACHIO_GUARD.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.BRACHIO_GUARD.get(), new BrachiosaurusGuardModel(ctx.m_174023_(BrachiosaurusGuardModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.BRACHIO_HEAVY.get(), (new MorphRenderer.Factory((MorphInfo)ModMorphs.BRACHIO_HEAVY.get(), new BrachiosaurusHeavyModel(ctx.m_174023_(BrachiosaurusHeavyModel.LAYER_LOCATION)))).m_174009_(ctx));
         MORPH_RENDERERS.put((MorphInfo)ModMorphs.GEAR_FOURTH.get(), (new GearFourthPointRenderer.Factory((MorphInfo)ModMorphs.GEAR_FOURTH.get(), new GearFourthModel(ctx.m_174023_(GearFourthModel.LAYER_LOCATION)))).m_174009_(ctx));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.SPRING_LEGS.get(), new SpringLegsModel(ctx.m_174023_(SpringLegsModel.LAYER_LOCATION)));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.KAME_WALK.get(), new KameWalkModel(ctx.m_174023_(KameWalkModel.LAYER_LOCATION)));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.ALLOSAURUS_HEAVY.get(), new AllosaurusHeavyModel(ctx.m_174023_(AllosaurusHeavyModel.LAYER_LOCATION)));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.PUNK_GIBSON.get(), new PunkGibsonModel(ctx.m_174023_(PunkGibsonModel.LAYER_LOCATION)));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.DAMNED_PUNK.get(), new DamnedPunkModel(ctx.m_174023_(DamnedPunkModel.LAYER_LOCATION)));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.PUNK_CORNA_DIO.get(), new PunkCornaDioModel(ctx.m_174023_(PunkCornaDioModel.LAYER_LOCATION)));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.PTERA_ASSAULT.get(), new PteranodonAssaultModel(ctx.m_174023_(PteranodonAssaultModel.LAYER_LOCATION)));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.GEAR_FIFTH.get(), new GearFifthRunningModel(ctx.m_174023_(GearFifthRunningModel.LAYER_LOCATION)));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.BARA_CAR.get(), new BaraCarWheelsModel(ctx.m_174023_(BaraCarWheelsModel.LAYER_LOCATION)));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.PHOENIX_ASSAULT.get(), new PhoenixAssaultModel(ctx.m_174023_(PhoenixAssaultModel.LAYER_LOCATION)));
         PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.MAMMOTH_HEAVY.get(), new MammothHeavyModel(ctx.m_174023_(MammothHeavyModel.LAYER_LOCATION)));

         for(String skin : event.getSkins()) {
            boolean isSlim = skin.equals("slim");
            PlayerModel<LivingEntity> playerModel = new PlayerModel(ctx.m_174023_(isSlim ? ModelLayers.f_171166_ : ModelLayers.f_171162_), isSlim);
            MORPH_RENDERERS.put((MorphInfo)ModMorphs.MINI.get(), (new PlayerMorphRenderer.Factory((MorphInfo)ModMorphs.MINI.get(), playerModel, isSlim)).m_174009_(ctx));
            MORPH_RENDERERS.put((MorphInfo)ModMorphs.DEKA.get(), (new PlayerMorphRenderer.Factory((MorphInfo)ModMorphs.DEKA.get(), playerModel, isSlim)).m_174009_(ctx));
            MORPH_RENDERERS.put((MorphInfo)ModMorphs.INGA_ZARASHI.get(), (new PlayerMorphRenderer.Factory((MorphInfo)ModMorphs.INGA_ZARASHI.get(), playerModel, isSlim)).m_174009_(ctx));
            MORPH_RENDERERS.put((MorphInfo)ModMorphs.GOMU_GIGANT.get(), (new PlayerMorphRenderer.Factory((MorphInfo)ModMorphs.GOMU_GIGANT.get(), playerModel, isSlim)).m_174009_(ctx));
            DaibutsuModel daibutsuModel = new DaibutsuModel(ctx.m_174023_(DaibutsuModel.LAYER_LOCATION), isSlim);
            MORPH_RENDERERS.put((MorphInfo)ModMorphs.DAIBUTSU.get(), (new PlayerMorphRenderer.Factory((MorphInfo)ModMorphs.DAIBUTSU.get(), daibutsuModel, isSlim)).m_174009_(ctx));
            MORPH_RENDERERS.put((MorphInfo)ModMorphs.VOLT_AMARU.get(), (new PlayerMorphRenderer.Factory((MorphInfo)ModMorphs.VOLT_AMARU.get(), daibutsuModel, isSlim)).m_174009_(ctx));
            PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.HANA_WINGS.get(), new HanaWingsModel(ctx.m_174023_(isSlim ? HanaWingsModel.SLIM_LAYER_LOCATION : HanaWingsModel.WIDE_LAYER_LOCATION)));
            PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.HANA_CALENDULA.get(), new HanaCalendulaModel(ctx.m_174023_(isSlim ? HanaCalendulaModel.SLIM_LAYER_LOCATION : HanaCalendulaModel.WIDE_LAYER_LOCATION)));
            PARTIAL_MORPHS_RENDERERS.put((MorphInfo)ModMorphs.SPAR_CLAW.get(), new SparClawModel(ctx.m_174023_(isSlim ? SparClawModel.SLIM_LAYER_LOCATION : SparClawModel.WIDE_LAYER_LOCATION)));
         }

         MinkBunnyModel<LivingEntity> minkBunnyPartial = new MinkBunnyModel<LivingEntity>(ctx.m_174023_(MinkBunnyModel.LAYER_LOCATION));
         MinkDogModel<LivingEntity> minkDogPartial = new MinkDogModel<LivingEntity>(ctx.m_174023_(MinkDogModel.LAYER_LOCATION));
         MinkLionModel<LivingEntity> minkLionPartial = new MinkLionModel<LivingEntity>(ctx.m_174023_(MinkLionModel.LAYER_LOCATION));
         SkypieanModel<LivingEntity> skypieanPartial = new SkypieanModel<LivingEntity>(ctx.m_174023_(SkypieanModel.LAYER_LOCATION));
         RACIAL_RENDERERS.put((Race)ModRaces.MINK_BUNNY.get(), new RacialRenderFeature(minkBunnyPartial, MINK_BUNNY_TEXTURE));
         RACIAL_RENDERERS.put((Race)ModRaces.MINK_DOG.get(), new RacialRenderFeature(minkDogPartial, MINK_DOG_TEXTURE));
         RACIAL_RENDERERS.put((Race)ModRaces.MINK_LION.get(), new RacialRenderFeature(minkLionPartial, MINK_LION_TEXTURE));
         RACIAL_RENDERERS.put((Race)ModRaces.SKYPIEAN.get(), new RacialRenderFeature(skypieanPartial, SKYPIEAN_TEXTURE));
         RACIAL_RENDERERS.put((Race)ModRaces.FISHMAN_SAWSHARK.get(), new RacialRenderFeature(new FishmanSawsharkModel(ctx.m_174023_(FishmanSawsharkModel.LAYER_LOCATION)), FISHMAN_SAWSHARK_TEXTURE));
         RACIAL_RENDERERS.put((Race)ModRaces.FISHMAN_RAY.get(), new RacialRenderFeature(new FishmanRayModel(ctx.m_174023_(FishmanRayModel.LAYER_LOCATION)), FISHMAN_RAY_TEXTURE));
         RACIAL_RENDERERS.put((Race)ModRaces.FISHMAN_GARFISH.get(), new RacialRenderFeature(new FishmanGarfishModel(ctx.m_174023_(FishmanGarfishModel.LAYER_LOCATION)), FISHMAN_GARFISH_TEXTURE));
      }
   }
}
