package xyz.pixelatedw.mineminenomi.init;

import java.util.function.Supplier;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.registries.RegistryObject;
import xyz.pixelatedw.mineminenomi.api.entities.NuLightningEntityRenderer;
import xyz.pixelatedw.mineminenomi.api.entities.NuProjectileEntity;
import xyz.pixelatedw.mineminenomi.api.entities.NuProjectileRenderer;
import xyz.pixelatedw.mineminenomi.entities.LightningDischargeEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.AxeDialProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.CannonBallProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.HookEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.KairosekiBulletProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.MilkyDialProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.NormalBulletProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.PopGreenProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.artofweather.CoolBallProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.artofweather.GustSwordProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.artofweather.HeatBallProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.artofweather.ThunderBallProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.artofweather.ThunderLanceProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.artofweather.ThunderboltProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.artofweather.ThunderstormProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.artofweather.WeatherEggProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.awa.RelaxHourProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.baku.BeroCannonProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.bane.SpringDeathKnockProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.bara.BaraBaraHoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.bara.BaraFestivalEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.bara.DaiCircusProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.bari.BarrierCrashProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.bari.BarrierbilityStairsProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.beta.BetaBetaChainProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.beta.StickyProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.blackleg.ExtraHachisProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.blackleg.PoeleAFrireProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.bomu.BreezeBreathBombProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.bomu.NoseFancyCannonProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.brawler.KingPunchProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.carnivaltricks.TopEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.cyborg.CoupDeVentProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.cyborg.FreshFireProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.cyborg.RadicalBeamProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.cyborg.StrongRightProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.doku.ChloroBallProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.doku.HydraProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.doku.VenomRoadProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.doru.CandleLockProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.doru.ChampFightProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.doru.DoruDoruArtsMoriProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.electro.ElectricalLunaProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.electro.ElectricalShowerProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.electro.ElectroVisualProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.fishmankarate.MizuShuryudanProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.fishmankarate.MizuTaihoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.fishmankarate.PackOfSharksProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.fishmankarate.UchimizuProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.fishmankarate.YarinamiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gasu.GasRobeProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gasu.GastilleProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.goe.DragonsRoarProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.goe.TodorokiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gomu.GomuGomuNoBajrangGunProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gomu.GomuGomuNoBazookaProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gomu.GomuGomuNoElephantGunProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gomu.GomuGomuNoGrizzlyMagnumProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gomu.GomuGomuNoJetBazookaProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gomu.GomuGomuNoJetPistolProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gomu.GomuGomuNoKingKongGunProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gomu.GomuGomuNoLeoBazookaProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gomu.GomuGomuNoPistolProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gomu.GomuGomuNoRocketProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.goro.ElThorProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.goro.RaigoLightningProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.goro.RaigoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.goro.SangoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.gura.GekishinProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.hana.CampoDeFloresEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.hana.HanaFeetEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.hana.HanaHandsEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.hasshoken.ButoKaitenProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.hie.IceBallProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.hie.IceBlockAvalancheProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.hie.IceBlockPartisanProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.hie.IceBlockPheasantProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.hitodaibutsu.ImpactBlastProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.horo.MiniHollowProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.horo.NegativeHollowProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.horo.TokuHollowProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.ito.OverheatProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.ito.StringPillarProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.ito.TamaitoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.ittoryu.SanbyakurokujuPoundHoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.ittoryu.SanjurokuPoundHoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.ittoryu.YakkodoriProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.jiki.DamnedPunkProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.jiki.GenocideRaidEffectEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.jiki.PunkGibsonProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.jiki.PunkPistolProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.kage.BlackBoxProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.kage.BrickBatProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.kage.TsunoTokagePillarEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.magu.DaiFunkaProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.magu.MeigoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.magu.RyuseiKazanProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.mera.DaiEnkaiEnteiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.mera.DaiEnkaiOnibiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.mera.HidarumaProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.mera.HiganProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.mera.HikenProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.mera.JujikaProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.mero.MeroMeroMellowProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.mero.PistolKissProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.mero.SlaveArrowProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.moku.WhiteBlowProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.moku.WhiteBlowRushProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.moku.WhiteOutProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.moku.WhiteSnakeProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.netsu.NekkaiGyoraiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.nikyu.ChargingUrsusShockEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.nikyu.PadHoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.nikyu.PainEntity;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.nikyu.UrsusShockProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.nitoryu.NanahyakunijuPoundHoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.nitoryu.NanajuniPoundHoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.noro.NoroNoroBeamProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.ori.AwaseBaoriProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.pero.CandyEscalatorProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.pero.CandyWaveProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.pika.AmaterasuProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.pika.YasakaniNoMagatamaProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.rokushiki.RankyakuProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.rokushiki.RokuoganProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.ryupteranodon.BarizodonProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.ryupteranodon.TempuraudonProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.santoryu.HyakuhachiPoundHoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.santoryu.SenhachijuPoundHoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.santoryu.TatsuMakiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.saraaxolotl.PoisonSpitProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.sniper.HiNoToriBoshiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.sniper.KemuriBoshiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.sniper.NemuriBoshiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.sniper.RenpatsuNamariBoshiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.sniper.SakuretsuSabotenBoshiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.sniper.TetsuBoshiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.sniper.TokuyoAburaBoshiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.suke.ShishaNoTeProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.suna.DesertGrandeEspadaProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.suna.DesertSpadaProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.suna.SablesPesadoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.supa.SparklingDaisyAftereffectProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.supa.SpiralHollowProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.toriphoenix.PhoenixGoenProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.yami.BlackRoadProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.yami.DarkMatterProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.yami.LiberationProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.yuki.YukiRabiProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.zushi.MokoProjectile;
import xyz.pixelatedw.mineminenomi.entities.projectiles.abilities.zushi.SagariNoRyuseiProjectile;
import xyz.pixelatedw.mineminenomi.models.CubeModel;
import xyz.pixelatedw.mineminenomi.models.SphereModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.ArrowModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.BaraFestivalModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.BrickBatModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.CrescentModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.HeartModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.HydraModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.MiniHollowModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.NegativeHollowModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.PawModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.PheasantModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.PillarModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.PlaneModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.RingModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.SharkModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.SpearModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.TokuHollowModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.TopModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.TridentModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.YukiRabiModel;
import xyz.pixelatedw.mineminenomi.models.entities.projectiles.effects.SpiralEffectModel;
import xyz.pixelatedw.mineminenomi.models.morphs.partials.PunkGibsonModel;
import xyz.pixelatedw.mineminenomi.renderers.entities.HookRenderer;
import xyz.pixelatedw.mineminenomi.renderers.entities.LightningDischargeRenderer;
import xyz.pixelatedw.mineminenomi.renderers.entities.PopGreenRenderer;
import xyz.pixelatedw.mineminenomi.renderers.entities.abilities.BaraFestivalRenderer;
import xyz.pixelatedw.mineminenomi.renderers.entities.abilities.CampoDeFloresRenderer;
import xyz.pixelatedw.mineminenomi.renderers.entities.abilities.ChargingUrsusShockRenderer;
import xyz.pixelatedw.mineminenomi.renderers.entities.abilities.ChloroBallRenderer;
import xyz.pixelatedw.mineminenomi.renderers.entities.abilities.GenocideRaidRenderer;
import xyz.pixelatedw.mineminenomi.renderers.entities.abilities.HanaHandsRenderer;
import xyz.pixelatedw.mineminenomi.renderers.entities.abilities.HydraRenderer;

public class ModProjectiles {
   public static final RegistryObject<EntityType<RelaxHourProjectile>> RELAX_HOUR = ModRegistry.<EntityType<RelaxHourProjectile>>registerEntityType("Relax Hour", () -> ModRegistry.createProjectileType(RelaxHourProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:relax_hour"));
   public static final RegistryObject<EntityType<BeroCannonProjectile>> BERO_CANNON = ModRegistry.<EntityType<BeroCannonProjectile>>registerEntityType("Bero Cannon", () -> ModRegistry.createProjectileType(BeroCannonProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:bero_cannon"));
   public static final RegistryObject<EntityType<BarrierCrashProjectile>> BARRIER_CRASH = ModRegistry.<EntityType<BarrierCrashProjectile>>registerEntityType("Barrier Crash", () -> ModRegistry.createProjectileType(BarrierCrashProjectile::new).m_20699_(4.0F, 5.0F).m_20712_("mineminenomi:barrier_crash"));
   public static final RegistryObject<EntityType<BarrierbilityStairsProjectile>> BARRIERBILITY_STAIRS = ModRegistry.<EntityType<BarrierbilityStairsProjectile>>registerEntityType("Barrierbility Stairs", () -> ModRegistry.createProjectileType(BarrierbilityStairsProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:barrierbility_stairs"));
   public static final RegistryObject<EntityType<StickyProjectile>> STICKY_PROJECTILE = ModRegistry.<EntityType<StickyProjectile>>registerEntityType("Mucus Bomb", () -> ModRegistry.createProjectileType(StickyProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:sticky"));
   public static final RegistryObject<EntityType<BetaBetaChainProjectile>> BETA_BETA_CHAIN = ModRegistry.<EntityType<BetaBetaChainProjectile>>registerEntityType("Beta Chain", () -> ModRegistry.createProjectileType(BetaBetaChainProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:beta_beta_chain"));
   public static final RegistryObject<EntityType<NoseFancyCannonProjectile>> NOSE_FANCY_CANNON = ModRegistry.<EntityType<NoseFancyCannonProjectile>>registerEntityType("Nose Fancy Cannon", () -> ModRegistry.createProjectileType(NoseFancyCannonProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:nose_fancy_cannon"));
   public static final RegistryObject<EntityType<BreezeBreathBombProjectile>> BREEZE_BREATH_BOMB = ModRegistry.<EntityType<BreezeBreathBombProjectile>>registerEntityType("Breeze Breath Bomb", () -> ModRegistry.createProjectileType(BreezeBreathBombProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:breeze_breath_bomb"));
   public static final RegistryObject<EntityType<HikenProjectile>> HIKEN = ModRegistry.<EntityType<HikenProjectile>>registerEntityType("Hiken", () -> ModRegistry.createProjectileType(HikenProjectile::new).m_20719_().m_20699_(1.2F, 1.2F).m_20712_("mineminenomi:hiken"));
   public static final RegistryObject<EntityType<HiganProjectile>> HIGAN = ModRegistry.<EntityType<HiganProjectile>>registerEntityType("Higan", () -> ModRegistry.createProjectileType(HiganProjectile::new).m_20719_().m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:higan"));
   public static final RegistryObject<EntityType<DaiEnkaiEnteiProjectile>> DAI_ENKAI_ENTEI = ModRegistry.<EntityType<DaiEnkaiEnteiProjectile>>registerEntityType("Dai Enkai: Entei", () -> ModRegistry.createProjectileType(DaiEnkaiEnteiProjectile::new).m_20719_().m_20699_(3.0F, 3.0F).m_20712_("mineminenomi:dai_enkai_entei"));
   public static final RegistryObject<EntityType<DaiEnkaiOnibiProjectile>> DAI_ENKAI_ONIBI = ModRegistry.<EntityType<DaiEnkaiOnibiProjectile>>registerEntityType("Dai Enkai: Onibi", () -> ModRegistry.createProjectileType(DaiEnkaiOnibiProjectile::new).m_20719_().m_20699_(7.5F, 7.5F).m_20712_("mineminenomi:dai_enkai_onibi"));
   public static final RegistryObject<EntityType<HidarumaProjectile>> HIDARUMA = ModRegistry.<EntityType<HidarumaProjectile>>registerEntityType("Hidaruma", () -> ModRegistry.createProjectileType(HidarumaProjectile::new).m_20719_().m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:hidaruma"));
   public static final RegistryObject<EntityType<JujikaProjectile>> JUJIKA = ModRegistry.<EntityType<JujikaProjectile>>registerEntityType("Jujika", () -> ModRegistry.createProjectileType(JujikaProjectile::new).m_20719_().m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:jujika"));
   public static final RegistryObject<EntityType<NekkaiGyoraiProjectile>> NEKKAI_GYORAI = ModRegistry.<EntityType<NekkaiGyoraiProjectile>>registerEntityType("Nekkai Gyorai", () -> ModRegistry.createProjectileType(NekkaiGyoraiProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:nekkai_gyorai"));
   public static final RegistryObject<EntityType<ShishaNoTeProjectile>> SHISHA_NO_TE = ModRegistry.<EntityType<ShishaNoTeProjectile>>registerEntityType("Shisha no Te", () -> ModRegistry.createProjectileType(ShishaNoTeProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:shisha_no_te"));
   public static final RegistryObject<EntityType<IceBlockPartisanProjectile>> ICE_BLOCK_PARTISAN = ModRegistry.<EntityType<IceBlockPartisanProjectile>>registerEntityType("Ice Block: Partisan", () -> ModRegistry.createProjectileType(IceBlockPartisanProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:ice_block_partisan"));
   public static final RegistryObject<EntityType<IceBallProjectile>> ICE_BALL = ModRegistry.<EntityType<IceBallProjectile>>registerEntityType("Ice Ball", () -> ModRegistry.createProjectileType(IceBallProjectile::new).m_20699_(0.7F, 0.7F).m_20712_("mineminenomi:ice_ball"));
   public static final RegistryObject<EntityType<IceBlockPheasantProjectile>> ICE_BLOCK_PHEASANT = ModRegistry.<EntityType<IceBlockPheasantProjectile>>registerEntityType("Ice Block: Pheasant", () -> ModRegistry.createProjectileType(IceBlockPheasantProjectile::new).m_20699_(2.0F, 2.0F).m_20712_("mineminenomi:ice_block_pheasant"));
   public static final RegistryObject<EntityType<IceBlockAvalancheProjectile>> ICE_BLOCK_AVALANCHE = ModRegistry.<EntityType<IceBlockAvalancheProjectile>>registerEntityType("Ice Block: Avalanche", () -> ModRegistry.createProjectileType(IceBlockAvalancheProjectile::new).m_20699_(9.0F, 9.0F).m_20712_("mineminenomi:ice_block_avalanche"));
   public static final RegistryObject<EntityType<YukiRabiProjectile>> YUKI_RABI = ModRegistry.<EntityType<YukiRabiProjectile>>registerEntityType("Yuki Rabi", () -> ModRegistry.createProjectileType(YukiRabiProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:yuki_rabi"));
   public static final RegistryObject<EntityType<WhiteBlowProjectile>> WHITE_BLOW = ModRegistry.<EntityType<WhiteBlowProjectile>>registerEntityType("White Blow", () -> ModRegistry.createProjectileType(WhiteBlowProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:white_blow"));
   public static final RegistryObject<EntityType<WhiteBlowRushProjectile>> WHITE_BLOW_RUSH = ModRegistry.<EntityType<WhiteBlowRushProjectile>>registerEntityType("White Blow Rush", () -> ModRegistry.createProjectileType(WhiteBlowRushProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:white_blow_rush"));
   public static final RegistryObject<EntityType<WhiteSnakeProjectile>> WHITE_SNAKE = ModRegistry.<EntityType<WhiteSnakeProjectile>>registerEntityType("White Snake", () -> ModRegistry.createProjectileType(WhiteSnakeProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:white_snake"));
   public static final RegistryObject<EntityType<WhiteOutProjectile>> WHITE_OUT = ModRegistry.<EntityType<WhiteOutProjectile>>registerEntityType("White Out", () -> ModRegistry.createProjectileType(WhiteOutProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:white_out"));
   public static final RegistryObject<EntityType<NoroNoroBeamProjectile>> NORO_NORO_BEAM = ModRegistry.<EntityType<NoroNoroBeamProjectile>>registerEntityType("Noro Noro Beam", () -> ModRegistry.createProjectileType(NoroNoroBeamProjectile::new).m_20699_(1.5F, 1.5F).m_20712_("mineminenomi:noro_noro_beam"));
   public static final RegistryObject<EntityType<NegativeHollowProjectile>> NEGATIVE_HOLLOW = ModRegistry.<EntityType<NegativeHollowProjectile>>registerEntityType("Negative Hollow", () -> ModRegistry.createProjectileType(NegativeHollowProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:negative_hollow"));
   public static final RegistryObject<EntityType<MiniHollowProjectile>> MINI_HOLLOW = ModRegistry.<EntityType<MiniHollowProjectile>>registerEntityType("Mini Hollow", () -> ModRegistry.createProjectileType(MiniHollowProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:mini_hollow"));
   public static final RegistryObject<EntityType<TokuHollowProjectile>> TOKU_HOLLOW = ModRegistry.<EntityType<TokuHollowProjectile>>registerEntityType("Toku Hollow", () -> ModRegistry.createProjectileType(TokuHollowProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:toku_hollow"));
   public static final RegistryObject<EntityType<DragonsRoarProjectile>> DRAGONS_ROAR = ModRegistry.<EntityType<DragonsRoarProjectile>>registerEntityType("Dragon's Roar", () -> ModRegistry.createProjectileType(DragonsRoarProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:dragons_roar"));
   public static final RegistryObject<EntityType<TodorokiProjectile>> TODOROKI = ModRegistry.<EntityType<TodorokiProjectile>>registerEntityType("Todoroki", () -> ModRegistry.createProjectileType(TodorokiProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:todoroki"));
   public static final RegistryObject<EntityType<AwaseBaoriProjectile>> AWASE_BAORI = ModRegistry.<EntityType<AwaseBaoriProjectile>>registerEntityType("Awase Baori", () -> ModRegistry.createProjectileType(AwaseBaoriProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:awase_baori"));
   public static final RegistryObject<EntityType<MeroMeroMellowProjectile>> MERO_MERO_MELLOW = ModRegistry.<EntityType<MeroMeroMellowProjectile>>registerEntityType("Mero Mero Mellow", () -> ModRegistry.createProjectileType(MeroMeroMellowProjectile::new).m_20699_(3.5F, 3.5F).m_20712_("mineminenomi:mero_mero_mellow"));
   public static final RegistryObject<EntityType<PistolKissProjectile>> PISTOL_KISS = ModRegistry.<EntityType<PistolKissProjectile>>registerEntityType("Pistol Kiss", () -> ModRegistry.createProjectileType(PistolKissProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:pistol_kiss"));
   public static final RegistryObject<EntityType<SlaveArrowProjectile>> SLAVE_ARROW = ModRegistry.<EntityType<SlaveArrowProjectile>>registerEntityType("Slave Arrow", () -> ModRegistry.createProjectileType(SlaveArrowProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:slave_arrow"));
   public static final RegistryObject<EntityType<SpringDeathKnockProjectile>> SPRING_DEATH_KNOCK = ModRegistry.<EntityType<SpringDeathKnockProjectile>>registerEntityType("Spring Death Knock", () -> ModRegistry.createProjectileType(SpringDeathKnockProjectile::new).m_20699_(1.5F, 1.5F).m_20712_("mineminenomi:spring_death_knock"));
   public static final RegistryObject<EntityType<PadHoProjectile>> PAD_HO = ModRegistry.<EntityType<PadHoProjectile>>registerEntityType("Pad Ho", () -> ModRegistry.createProjectileType(PadHoProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:pad_ho"));
   public static final RegistryObject<EntityType<UrsusShockProjectile>> URSUS_SHOCK = ModRegistry.<EntityType<UrsusShockProjectile>>registerEntityType("Ursus Shock", () -> ModRegistry.createProjectileType(UrsusShockProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:ursus_shock"));
   public static final RegistryObject<EntityType<ChargingUrsusShockEntity>> CHARGING_URSUS_SHOCK = ModRegistry.<EntityType<ChargingUrsusShockEntity>>registerEntityType("Charging Ursus Shock", () -> ModRegistry.createEntityType(ChargingUrsusShockEntity::new, MobCategory.MISC).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:charging_ursus_shock"));
   public static final RegistryObject<EntityType<PainEntity>> PAIN = ModRegistry.<EntityType<PainEntity>>registerEntityType("Pain", () -> ModRegistry.createProjectileType(PainEntity::new).m_20699_(1.5F, 1.5F).m_20712_("mineminenomi:pain"));
   public static final RegistryObject<EntityType<AmaterasuProjectile>> AMATERASU = ModRegistry.<EntityType<AmaterasuProjectile>>registerEntityType("Amaterasu", () -> ModRegistry.createProjectileType(AmaterasuProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:amaterasu"));
   public static final RegistryObject<EntityType<YasakaniNoMagatamaProjectile>> YASAKANI_NO_MAGATAMA = ModRegistry.<EntityType<YasakaniNoMagatamaProjectile>>registerEntityType("Yasakani no Magatama", () -> ModRegistry.createProjectileType(YasakaniNoMagatamaProjectile::new).m_20699_(0.2F, 0.2F).m_20712_("mineminenomi:yasakani_no_magatama"));
   public static final RegistryObject<EntityType<DaiFunkaProjectile>> DAI_FUNKA = ModRegistry.<EntityType<DaiFunkaProjectile>>registerEntityType("Dai Funka", () -> ModRegistry.createProjectileType(DaiFunkaProjectile::new).m_20699_(4.5F, 4.5F).m_20712_("mineminenomi:dai_funka"));
   public static final RegistryObject<EntityType<RyuseiKazanProjectile>> RYUSEI_KAZAN = ModRegistry.<EntityType<RyuseiKazanProjectile>>registerEntityType("Ryusei Kazan", () -> ModRegistry.createProjectileType(RyuseiKazanProjectile::new).m_20699_(4.5F, 4.5F).m_20712_("mineminenomi:ryusei_kazan"));
   public static final RegistryObject<EntityType<MeigoProjectile>> MEIGO = ModRegistry.<EntityType<MeigoProjectile>>registerEntityType("Meigo", () -> ModRegistry.createProjectileType(MeigoProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:meigo"));
   public static final RegistryObject<EntityType<HanaHandsEntity>> HANA_HANDS = ModRegistry.<EntityType<HanaHandsEntity>>registerEntityType("Hana Hands", () -> ModRegistry.createProjectileType(HanaHandsEntity::new).m_20699_(0.1F, 0.1F).m_20712_("mineminenomi:hana_hands"));
   public static final RegistryObject<EntityType<HanaFeetEntity>> HANA_FEET = ModRegistry.<EntityType<HanaFeetEntity>>registerEntityType("Feet", () -> ModRegistry.createProjectileType(HanaFeetEntity::new).m_20699_(2.0F, 2.0F).m_20712_("mineminenomi:hana_feet"));
   public static final RegistryObject<EntityType<CampoDeFloresEntity>> CAMPO_DE_FLORES = ModRegistry.<EntityType<CampoDeFloresEntity>>registerEntityType("Campo de Flores", () -> ModRegistry.createProjectileType(CampoDeFloresEntity::new).m_20699_(1.0F, 0.1F).m_20712_("mineminenomi:campo_de_flores"));
   public static final RegistryObject<EntityType<DoruDoruArtsMoriProjectile>> DORU_DORU_ARTS_MORI = ModRegistry.<EntityType<DoruDoruArtsMoriProjectile>>registerEntityType("Doru Doru Arts: Mori", () -> ModRegistry.createProjectileType(DoruDoruArtsMoriProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:doru_doru_arts_mori"));
   public static final RegistryObject<EntityType<CandleLockProjectile>> CANDLE_LOCK = ModRegistry.<EntityType<CandleLockProjectile>>registerEntityType("Candle Lock", () -> ModRegistry.createProjectileType(CandleLockProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:candle_lock"));
   public static final RegistryObject<EntityType<ChampFightProjectile>> CHAMP_FIGHT = ModRegistry.<EntityType<ChampFightProjectile>>registerEntityType("Champ Fight", () -> ModRegistry.createProjectileType(ChampFightProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:champ_fight"));
   public static final RegistryObject<EntityType<GasRobeProjectile>> GAS_ROBE = ModRegistry.<EntityType<GasRobeProjectile>>registerEntityType("Gas Robe", () -> ModRegistry.createProjectileType(GasRobeProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:gas_robe"));
   public static final RegistryObject<EntityType<GastilleProjectile>> GASTILLE = ModRegistry.<EntityType<GastilleProjectile>>registerEntityType("Gastille", () -> ModRegistry.createProjectileType(GastilleProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:gastille"));
   public static final RegistryObject<EntityType<DesertSpadaProjectile>> DESERT_SPADA = ModRegistry.<EntityType<DesertSpadaProjectile>>registerEntityType("Desert Spada", () -> ModRegistry.createProjectileType(DesertSpadaProjectile::new).m_20699_(2.0F, 2.0F).m_20712_("mineminenomi:desert_spada"));
   public static final RegistryObject<EntityType<DesertGrandeEspadaProjectile>> DESERT_GRANDE_ESPADA = ModRegistry.<EntityType<DesertGrandeEspadaProjectile>>registerEntityType("Desert Grande Spada", () -> ModRegistry.createProjectileType(DesertGrandeEspadaProjectile::new).m_20699_(1.25F, 1.25F).m_20712_("mineminenomi:desert_grande_spada"));
   public static final RegistryObject<EntityType<SablesPesadoProjectile>> SABLES_PESADO = ModRegistry.<EntityType<SablesPesadoProjectile>>registerEntityType("Sables Pesado", () -> ModRegistry.createProjectileType(SablesPesadoProjectile::new).m_20699_(1.5F, 1.5F).m_20712_("mineminenomi:sables_pesado"));
   public static final RegistryObject<EntityType<GekishinProjectile>> GEKISHIN = ModRegistry.<EntityType<GekishinProjectile>>registerEntityType("Gekishin", () -> ModRegistry.createProjectileType(GekishinProjectile::new).m_20699_(1.25F, 1.25F).m_20712_("mineminenomi:gekishin"));
   public static final RegistryObject<EntityType<SpiralHollowProjectile>> SPIRAL_HOLLOW = ModRegistry.<EntityType<SpiralHollowProjectile>>registerEntityType("Spiral Hollow", () -> ModRegistry.createProjectileType(SpiralHollowProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:spiral_hollow"));
   public static final RegistryObject<EntityType<SparklingDaisyAftereffectProjectile>> SPARKLING_DAISY_AFTER = ModRegistry.<EntityType<SparklingDaisyAftereffectProjectile>>registerEntityType("Sparkling Daisy Aftereffect", () -> ModRegistry.createProjectileType(SparklingDaisyAftereffectProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:sparkling_daisy_after"));
   public static final RegistryObject<EntityType<PoisonSpitProjectile>> POISON_SPIT = ModRegistry.<EntityType<PoisonSpitProjectile>>registerEntityType("Poison Spit", () -> ModRegistry.createProjectileType(PoisonSpitProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:poison_spit"));
   public static final RegistryObject<EntityType<ImpactBlastProjectile>> IMPACT_BLAST = ModRegistry.<EntityType<ImpactBlastProjectile>>registerEntityType("Impact Blast", () -> ModRegistry.createProjectileType(ImpactBlastProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:impact_blast"));
   public static final RegistryObject<EntityType<SagariNoRyuseiProjectile>> SAGARI_NO_RYUSEI = ModRegistry.<EntityType<SagariNoRyuseiProjectile>>registerEntityType("Sagari no Ryusei", () -> ModRegistry.createProjectileType(SagariNoRyuseiProjectile::new).m_20699_(8.0F, 8.0F).m_20712_("mineminenomi:sagari_no_ryusei"));
   public static final RegistryObject<EntityType<MokoProjectile>> MOKO = ModRegistry.<EntityType<MokoProjectile>>registerEntityType("Moko", () -> ModRegistry.createProjectileType(MokoProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:moko"));
   public static final RegistryObject<EntityType<CandyEscalatorProjectile>> CANDY_ESCALATOR = ModRegistry.<EntityType<CandyEscalatorProjectile>>registerEntityType("Candy Escalator", () -> ModRegistry.createProjectileType(CandyEscalatorProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:candy_escalator"));
   public static final RegistryObject<EntityType<CandyWaveProjectile>> CANDY_WAVE = ModRegistry.<EntityType<CandyWaveProjectile>>registerEntityType("Candy Wave", () -> ModRegistry.createProjectileType(CandyWaveProjectile::new).m_20699_(3.0F, 3.0F).m_20712_("mineminenomi:candy_wave"));
   public static final RegistryObject<EntityType<TamaitoProjectile>> TAMAITO = ModRegistry.<EntityType<TamaitoProjectile>>registerEntityType("Tamaito", () -> ModRegistry.createProjectileType(TamaitoProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:tamaito"));
   public static final RegistryObject<EntityType<StringPillarProjectile>> STRING_PILLAR = ModRegistry.<EntityType<StringPillarProjectile>>registerEntityType("String Pillar", () -> ModRegistry.createProjectileType(StringPillarProjectile::new).m_20699_(1.0F, 10.0F).m_20712_("mineminenomi:string_pillar"));
   public static final RegistryObject<EntityType<OverheatProjectile>> OVERHEAT = ModRegistry.<EntityType<OverheatProjectile>>registerEntityType("Overheat", () -> ModRegistry.createProjectileType(OverheatProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:overheat"));
   public static final RegistryObject<EntityType<BrickBatProjectile>> BRICK_BAT = ModRegistry.<EntityType<BrickBatProjectile>>registerEntityType("Brick Bat", () -> ModRegistry.createProjectileType(BrickBatProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:brick_bat"));
   public static final RegistryObject<EntityType<BlackBoxProjectile>> BLACK_BOX = ModRegistry.<EntityType<BlackBoxProjectile>>registerEntityType("Brick Box", () -> ModRegistry.createProjectileType(BlackBoxProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:black_box"));
   public static final RegistryObject<EntityType<TsunoTokagePillarEntity>> TSUNO_TOKAGE = ModRegistry.<EntityType<TsunoTokagePillarEntity>>registerEntityType("Tsuno Tokage", () -> ModRegistry.createProjectileType(TsunoTokagePillarEntity::new).m_20699_(1.5F, 1.5F).m_20712_("mineminenomi:tsuno_tokage"));
   public static final RegistryObject<EntityType<HydraProjectile>> HYDRA = ModRegistry.<EntityType<HydraProjectile>>registerEntityType("Hydra", () -> ModRegistry.createProjectileType(HydraProjectile::new).m_20699_(2.0F, 2.0F).m_20712_("mineminenomi:hydra"));
   public static final RegistryObject<EntityType<ChloroBallProjectile>> CHLORO_BALL = ModRegistry.<EntityType<ChloroBallProjectile>>registerEntityType("Chloro Ball", () -> ModRegistry.createProjectileType(ChloroBallProjectile::new).m_20699_(0.75F, 0.75F).m_20712_("mineminenomi:chloro_ball"));
   public static final RegistryObject<EntityType<VenomRoadProjectile>> VENOM_ROAD = ModRegistry.<EntityType<VenomRoadProjectile>>registerEntityType("Venom Road", () -> ModRegistry.createProjectileType(VenomRoadProjectile::new).m_20699_(2.0F, 2.0F).m_20712_("mineminenomi:venom_road"));
   public static final RegistryObject<EntityType<GomuGomuNoPistolProjectile>> GOMU_GOMU_NO_PISTOL = ModRegistry.<EntityType<GomuGomuNoPistolProjectile>>registerEntityType("Gomu Gomu no Pistol", () -> ModRegistry.createProjectileType(GomuGomuNoPistolProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:gomu_gomu_no_pistol"));
   public static final RegistryObject<EntityType<GomuGomuNoJetPistolProjectile>> GOMU_GOMU_NO_JET_PISTOL = ModRegistry.<EntityType<GomuGomuNoJetPistolProjectile>>registerEntityType("Gomu Gomu no Jet Pistol", () -> ModRegistry.createProjectileType(GomuGomuNoJetPistolProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:gomu_gomu_no_jet_pistol"));
   public static final RegistryObject<EntityType<GomuGomuNoElephantGunProjectile>> GOMU_GOMU_NO_ELEPHANT_GUN = ModRegistry.<EntityType<GomuGomuNoElephantGunProjectile>>registerEntityType("Gomu Gomu no Elephant Gun", () -> ModRegistry.createProjectileType(GomuGomuNoElephantGunProjectile::new).m_20699_(5.0F, 5.0F).m_20712_("mineminenomi:gomu_gomu_no_elephant_gun"));
   public static final RegistryObject<EntityType<GomuGomuNoKingKongGunProjectile>> GOMU_GOMU_NO_KING_KONG_GUN = ModRegistry.<EntityType<GomuGomuNoKingKongGunProjectile>>registerEntityType("Gomu Gomu no King Kong Gun", () -> ModRegistry.createProjectileType(GomuGomuNoKingKongGunProjectile::new).m_20699_(5.0F, 5.0F).m_20712_("mineminenomi:gomu_gomu_no_king_kong_gun"));
   public static final RegistryObject<EntityType<GomuGomuNoBajrangGunProjectile>> GOMU_GOMU_NO_BAJRANG_GUN = ModRegistry.<EntityType<GomuGomuNoBajrangGunProjectile>>registerEntityType("Gomu Gomu no Bajrang Gun", () -> ModRegistry.createProjectileType(GomuGomuNoBajrangGunProjectile::new).m_20699_(20.0F, 20.0F).m_20712_("mineminenomi:gomu_gomu_no_bajrang_gun"));
   public static final RegistryObject<EntityType<GomuGomuNoBazookaProjectile>> GOMU_GOMU_NO_BAZOOKA = ModRegistry.<EntityType<GomuGomuNoBazookaProjectile>>registerEntityType("Gomu Gomu no Bazooka", () -> ModRegistry.createProjectileType(GomuGomuNoBazookaProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:gomu_gomu_no_bazooka"));
   public static final RegistryObject<EntityType<GomuGomuNoJetBazookaProjectile>> GOMU_GOMU_NO_JET_BAZOOKA = ModRegistry.<EntityType<GomuGomuNoJetBazookaProjectile>>registerEntityType("Gomu Gomu no Jet Bazooka", () -> ModRegistry.createProjectileType(GomuGomuNoJetBazookaProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:gomu_gomu_no_jet_bazooka"));
   public static final RegistryObject<EntityType<GomuGomuNoGrizzlyMagnumProjectile>> GOMU_GOMU_NO_GRIZZLY_MAGNUM = ModRegistry.<EntityType<GomuGomuNoGrizzlyMagnumProjectile>>registerEntityType("Gomu Gomu no Grizzly Magnum", () -> ModRegistry.createProjectileType(GomuGomuNoGrizzlyMagnumProjectile::new).m_20699_(5.0F, 5.0F).m_20712_("mineminenomi:gomu_gomu_no_grizzly_magnum"));
   public static final RegistryObject<EntityType<GomuGomuNoLeoBazookaProjectile>> GOMU_GOMU_NO_LEO_BAZOOKA = ModRegistry.<EntityType<GomuGomuNoLeoBazookaProjectile>>registerEntityType("Gomu Gomu no Leo Bazooka", () -> ModRegistry.createProjectileType(GomuGomuNoLeoBazookaProjectile::new).m_20699_(5.0F, 5.0F).m_20712_("mineminenomi:gomu_gomu_no_leo_bazooka"));
   public static final RegistryObject<EntityType<GomuGomuNoRocketProjectile>> GOMU_GOMU_NO_ROCKET = ModRegistry.<EntityType<GomuGomuNoRocketProjectile>>registerEntityType("Gomu Gomu no Rocket", () -> ModRegistry.createProjectileType(GomuGomuNoRocketProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:gomu_gomu_no_rocket"));
   public static final RegistryObject<EntityType<SangoProjectile>> SANGO = ModRegistry.<EntityType<SangoProjectile>>registerEntityType("Sango", () -> ModRegistry.createProjectileType(SangoProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:sango"));
   public static final RegistryObject<EntityType<ElThorProjectile>> EL_THOR = ModRegistry.<EntityType<ElThorProjectile>>registerEntityType("El Thor", () -> ModRegistry.createProjectileType(ElThorProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:el_thor"));
   public static final RegistryObject<EntityType<RaigoProjectile>> RAIGO = ModRegistry.<EntityType<RaigoProjectile>>registerEntityType("Raigo", () -> ModRegistry.createProjectileType(RaigoProjectile::new).m_20699_(15.0F, 15.0F).m_20712_("mineminenomi:raigo"));
   public static final RegistryObject<EntityType<RaigoLightningProjectile>> RAIGO_LIGHTNING = ModRegistry.<EntityType<RaigoLightningProjectile>>registerEntityType("Raigo Lightning", () -> ModRegistry.createProjectileType(RaigoLightningProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:raigo_lightning"));
   public static final RegistryObject<EntityType<LiberationProjectile>> LIBERATION = ModRegistry.<EntityType<LiberationProjectile>>registerEntityType("Liberation", () -> ModRegistry.createProjectileType(LiberationProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:liberation"));
   public static final RegistryObject<EntityType<DarkMatterProjectile>> DARK_MATTER = ModRegistry.<EntityType<DarkMatterProjectile>>registerEntityType("Dark Matter", () -> ModRegistry.createProjectileType(DarkMatterProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:dark_matter"));
   public static final RegistryObject<EntityType<BlackRoadProjectile>> BLACK_ROAD = ModRegistry.<EntityType<BlackRoadProjectile>>registerEntityType("Black Road", () -> ModRegistry.createProjectileType(BlackRoadProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:black_road"));
   public static final RegistryObject<EntityType<PunkGibsonProjectile>> PUNK_GIBSON = ModRegistry.<EntityType<PunkGibsonProjectile>>registerEntityType("Punk Gibson", () -> ModRegistry.createProjectileType(PunkGibsonProjectile::new).m_20699_(1.5F, 1.5F).m_20712_("mineminenomi:punk_gibson"));
   public static final RegistryObject<EntityType<PunkPistolProjectile>> PUNK_PISTOL = ModRegistry.<EntityType<PunkPistolProjectile>>registerEntityType("Punk Pistol", () -> ModRegistry.createProjectileType(PunkPistolProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:punk_pistol"));
   public static final RegistryObject<EntityType<DamnedPunkProjectile>> DAMNED_PUNK = ModRegistry.<EntityType<DamnedPunkProjectile>>registerEntityType("Damned Punk", () -> ModRegistry.createProjectileType(DamnedPunkProjectile::new).m_20699_(1.0F, 1.0F).m_20712_("mineminenomi:damned_punk"));
   public static final RegistryObject<EntityType<GenocideRaidEffectEntity>> GENOCIDE_RAID_EFFECT = ModRegistry.<EntityType<GenocideRaidEffectEntity>>registerEntityType("Genocide Raid Effect", () -> ModRegistry.createProjectileType(GenocideRaidEffectEntity::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:genocide_raid_effect"));
   public static final RegistryObject<EntityType<BarizodonProjectile>> BARIZODON = ModRegistry.<EntityType<BarizodonProjectile>>registerEntityType("Barizodon", () -> ModRegistry.createProjectileType(BarizodonProjectile::new).m_20699_(1.5F, 1.5F).m_20712_("mineminenomi:barizodon"));
   public static final RegistryObject<EntityType<TempuraudonProjectile>> TEMPURAUDON = ModRegistry.<EntityType<TempuraudonProjectile>>registerEntityType("Tempuraudon", () -> ModRegistry.createProjectileType(TempuraudonProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:tempuraudon"));
   public static final RegistryObject<EntityType<BaraBaraHoProjectile>> BARA_BARA_HO = ModRegistry.<EntityType<BaraBaraHoProjectile>>registerEntityType("Bara Bara Ho", () -> ModRegistry.createProjectileType(BaraBaraHoProjectile::new).m_20699_(1.2F, 1.2F).m_20712_("mineminenomi:bara_bara_ho"));
   public static final RegistryObject<EntityType<DaiCircusProjectile>> DAI_CIRCUS = ModRegistry.<EntityType<DaiCircusProjectile>>registerEntityType("Dai Circus", () -> ModRegistry.createProjectileType(DaiCircusProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:dai_circus"));
   public static final RegistryObject<EntityType<BaraFestivalEntity>> BARA_FESTIVAL = ModRegistry.<EntityType<BaraFestivalEntity>>registerEntityType("Bara Festival", () -> ModRegistry.createProjectileType(BaraFestivalEntity::new).m_20699_(0.1F, 0.1F).m_20712_("mineminenomi:bara_festival"));
   public static final RegistryObject<EntityType<PhoenixGoenProjectile>> PHOENIX_GOEN = ModRegistry.<EntityType<PhoenixGoenProjectile>>registerEntityType("Phoenix Goen", () -> ModRegistry.createProjectileType(PhoenixGoenProjectile::new).m_20699_(1.5F, 1.5F).m_20712_("mineminenomi:phoenix_goen"));
   public static final RegistryObject<EntityType<RankyakuProjectile>> RANKYAKU = ModRegistry.<EntityType<RankyakuProjectile>>registerEntityType("Rankyaku", () -> ModRegistry.createProjectileType(RankyakuProjectile::new).m_20699_(5.25F, 0.5F).m_20712_("mineminenomi:rankyaku"));
   public static final RegistryObject<EntityType<RokuoganProjectile>> ROKUOGAN = ModRegistry.<EntityType<RokuoganProjectile>>registerEntityType("Rokuogan", () -> ModRegistry.createProjectileType(RokuoganProjectile::new).m_20699_(3.0F, 3.0F).m_20712_("mineminenomi:rokuogan"));
   public static final RegistryObject<EntityType<UchimizuProjectile>> UCHIMIZU = ModRegistry.<EntityType<UchimizuProjectile>>registerEntityType("Uchimizu", () -> ModRegistry.createProjectileType(UchimizuProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:uchimizu"));
   public static final RegistryObject<EntityType<PackOfSharksProjectile>> PACK_OF_SHARKS = ModRegistry.<EntityType<PackOfSharksProjectile>>registerEntityType("Pack of Sharks", () -> ModRegistry.createProjectileType(PackOfSharksProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:pack_of_sharks"));
   public static final RegistryObject<EntityType<YarinamiProjectile>> YARINAMI = ModRegistry.<EntityType<YarinamiProjectile>>registerEntityType("Yarinami", () -> ModRegistry.createProjectileType(YarinamiProjectile::new).m_20699_(2.0F, 2.0F).m_20712_("mineminenomi:yarinami"));
   public static final RegistryObject<EntityType<MizuTaihoProjectile>> MIZU_TAIHO = ModRegistry.<EntityType<MizuTaihoProjectile>>registerEntityType("Mizu Taiho", () -> ModRegistry.createProjectileType(MizuTaihoProjectile::new).m_20699_(2.5F, 2.5F).m_20712_("mineminenomi:mizu_taiho"));
   public static final RegistryObject<EntityType<MizuShuryudanProjectile>> MIZU_SHURYUDAN = ModRegistry.<EntityType<MizuShuryudanProjectile>>registerEntityType("Mizu Shuryudan", () -> ModRegistry.createProjectileType(MizuShuryudanProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:mizu_shuryudan"));
   public static final RegistryObject<EntityType<FreshFireProjectile>> FRESH_FIRE = ModRegistry.<EntityType<FreshFireProjectile>>registerEntityType("Fresh Fire", () -> ModRegistry.createProjectileType(FreshFireProjectile::new).m_20699_(0.5F, 0.5F).m_20719_().m_20712_("mineminenomi:fresh_fire"));
   public static final RegistryObject<EntityType<StrongRightProjectile>> STRONG_RIGHT = ModRegistry.<EntityType<StrongRightProjectile>>registerEntityType("Strong Right", () -> ModRegistry.createProjectileType(StrongRightProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:strong_right"));
   public static final RegistryObject<EntityType<CoupDeVentProjectile>> COUP_DE_VENT = ModRegistry.<EntityType<CoupDeVentProjectile>>registerEntityType("Coup de Vent", () -> ModRegistry.createProjectileType(CoupDeVentProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:coup_de_vent"));
   public static final RegistryObject<EntityType<RadicalBeamProjectile>> RADICAL_BEAM = ModRegistry.<EntityType<RadicalBeamProjectile>>registerEntityType("Radical Beam", () -> ModRegistry.createProjectileType(RadicalBeamProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:radical_beam"));
   public static final RegistryObject<EntityType<ElectricalLunaProjectile>> ELECTRICAL_LUNA = ModRegistry.<EntityType<ElectricalLunaProjectile>>registerEntityType("Electrical Luna", () -> ModRegistry.createProjectileType(ElectricalLunaProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:electrical_luna"));
   public static final RegistryObject<EntityType<ElectricalShowerProjectile>> ELECTRICAL_SHOWER = ModRegistry.<EntityType<ElectricalShowerProjectile>>registerEntityType("Electrical Shower", () -> ModRegistry.createProjectileType(ElectricalShowerProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:electrical_shower"));
   public static final RegistryObject<EntityType<ElectroVisualProjectile>> ELECTRO_VISUAL = ModRegistry.<EntityType<ElectroVisualProjectile>>registerEntityType("Electro Visual", () -> ModRegistry.createProjectileType(ElectroVisualProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:electro_visual"));
   public static final RegistryObject<EntityType<SanbyakurokujuPoundHoProjectile>> SANBYAKUROKUJU_POUND_HO = ModRegistry.<EntityType<SanbyakurokujuPoundHoProjectile>>registerEntityType("Sanbyakurokuju Pound Ho", () -> ModRegistry.createProjectileType(SanbyakurokujuPoundHoProjectile::new).m_20699_(3.0F, 0.5F).m_20712_("mineminenomi:sanbyakurokuju_pound_ho"));
   public static final RegistryObject<EntityType<SanjurokuPoundHoProjectile>> SANJUROKU_POUND_HO = ModRegistry.<EntityType<SanjurokuPoundHoProjectile>>registerEntityType("Sanjuroku Pound Ho", () -> ModRegistry.createProjectileType(SanjurokuPoundHoProjectile::new).m_20699_(3.0F, 0.5F).m_20712_("mineminenomi:sanjuroku_pound_ho"));
   public static final RegistryObject<EntityType<YakkodoriProjectile>> YAKKODORI = ModRegistry.<EntityType<YakkodoriProjectile>>registerEntityType("Yakkodori", () -> ModRegistry.createProjectileType(YakkodoriProjectile::new).m_20699_(0.5F, 1.5F).m_20712_("mineminenomi:yakkodori"));
   public static final RegistryObject<EntityType<NanahyakunijuPoundHoProjectile>> NANAHYAKUNIJU_POUND_HO = ModRegistry.<EntityType<NanahyakunijuPoundHoProjectile>>registerEntityType("Nanahyakuniju Pound Ho", () -> ModRegistry.createProjectileType(NanahyakunijuPoundHoProjectile::new).m_20699_(3.0F, 0.5F).m_20712_("mineminenomi:nanahyakuniju_pound_ho"));
   public static final RegistryObject<EntityType<NanajuniPoundHoProjectile>> NANAJUNI_POUND_HO = ModRegistry.<EntityType<NanajuniPoundHoProjectile>>registerEntityType("Nanajuni Pound Ho", () -> ModRegistry.createProjectileType(NanajuniPoundHoProjectile::new).m_20699_(3.0F, 0.5F).m_20712_("mineminenomi:nanajuni_pound_ho"));
   public static final RegistryObject<EntityType<HyakuhachiPoundHoProjectile>> HYAKUHACHI_POUND_HO = ModRegistry.<EntityType<HyakuhachiPoundHoProjectile>>registerEntityType("Hyakuhachi Pound Ho", () -> ModRegistry.createProjectileType(HyakuhachiPoundHoProjectile::new).m_20699_(3.0F, 0.5F).m_20712_("mineminenomi:hyakuhachi_pound_ho"));
   public static final RegistryObject<EntityType<SenhachijuPoundHoProjectile>> SENHACHIJU_POUND_HO = ModRegistry.<EntityType<SenhachijuPoundHoProjectile>>registerEntityType("Senhachiju Pound Ho", () -> ModRegistry.createProjectileType(SenhachijuPoundHoProjectile::new).m_20699_(3.0F, 0.5F).m_20712_("mineminenomi:senhachiju_pound_ho"));
   public static final RegistryObject<EntityType<TatsuMakiProjectile>> TATSU_MAKI = ModRegistry.<EntityType<TatsuMakiProjectile>>registerEntityType("Tatsu Maki", () -> ModRegistry.createProjectileType(TatsuMakiProjectile::new).m_20699_(2.0F, 2.0F).m_20712_("mineminenomi:tatsu_maki"));
   public static final RegistryObject<EntityType<ButoKaitenProjectile>> BUTO_KAITEN = ModRegistry.<EntityType<ButoKaitenProjectile>>registerEntityType("Buto Kaiten", () -> ModRegistry.createProjectileType(ButoKaitenProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:buto_kaiten"));
   public static final RegistryObject<EntityType<KingPunchProjectile>> KING_PUNCH = ModRegistry.<EntityType<KingPunchProjectile>>registerEntityType("King Punch", () -> ModRegistry.createProjectileType(KingPunchProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:king_punch"));
   public static final RegistryObject<EntityType<ExtraHachisProjectile>> EXTRA_HACHIS = ModRegistry.<EntityType<ExtraHachisProjectile>>registerEntityType("Extra Hachis", () -> ModRegistry.createProjectileType(ExtraHachisProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:extra_hachis"));
   public static final RegistryObject<EntityType<PoeleAFrireProjectile>> POELE_A_FRIRE = ModRegistry.<EntityType<PoeleAFrireProjectile>>registerEntityType("Poele a Frire", () -> ModRegistry.createProjectileType(PoeleAFrireProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:poele_a_frire"));
   public static final RegistryObject<EntityType<HiNoToriBoshiProjectile>> HI_NO_TORI_BOSHI = ModRegistry.<EntityType<HiNoToriBoshiProjectile>>registerEntityType("Hi no Tori Boshi", () -> ModRegistry.createProjectileType(HiNoToriBoshiProjectile::new).m_20699_(2.25F, 2.25F).m_20712_("mineminenomi:hi_no_tori_boshi"));
   public static final RegistryObject<EntityType<KemuriBoshiProjectile>> KEMURI_BOSHI = ModRegistry.<EntityType<KemuriBoshiProjectile>>registerEntityType("Kemuri Boshi", () -> ModRegistry.createProjectileType(KemuriBoshiProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:kemuri_boshi"));
   public static final RegistryObject<EntityType<RenpatsuNamariBoshiProjectile>> RENPATSU_NAMARI_BOSHI = ModRegistry.<EntityType<RenpatsuNamariBoshiProjectile>>registerEntityType("Renpatsu Namari Boshi", () -> ModRegistry.createProjectileType(RenpatsuNamariBoshiProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:renpatsu_namari_boshi"));
   public static final RegistryObject<EntityType<SakuretsuSabotenBoshiProjectile>> SAKURETSU_SABOTEN_BOSHI = ModRegistry.<EntityType<SakuretsuSabotenBoshiProjectile>>registerEntityType("Sakuretsu Saboten Boshi", () -> ModRegistry.createProjectileType(SakuretsuSabotenBoshiProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:sakuretsu_saboten_boshi"));
   public static final RegistryObject<EntityType<TetsuBoshiProjectile>> TETSU_BOSHI = ModRegistry.<EntityType<TetsuBoshiProjectile>>registerEntityType("Tetsu Boshi", () -> ModRegistry.createProjectileType(TetsuBoshiProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:tetsu_boshi"));
   public static final RegistryObject<EntityType<TokuyoAburaBoshiProjectile>> TOKUYO_ABURA_BOSHI = ModRegistry.<EntityType<TokuyoAburaBoshiProjectile>>registerEntityType("Tokuyo Abura Boshi", () -> ModRegistry.createProjectileType(TokuyoAburaBoshiProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:tokuya_abura_boshi"));
   public static final RegistryObject<EntityType<NemuriBoshiProjectile>> NEMURI_BOSHI = ModRegistry.<EntityType<NemuriBoshiProjectile>>registerEntityType("Nemuri Boshi", () -> ModRegistry.createProjectileType(NemuriBoshiProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:nemuri_boshi"));
   public static final RegistryObject<EntityType<HiNoToriBoshiProjectile>> KAEN_BOSHI = ModRegistry.<EntityType<HiNoToriBoshiProjectile>>registerEntityType("Kaen Boshi", () -> ModRegistry.createProjectileType(HiNoToriBoshiProjectile::new).m_20699_(0.4F, 0.4F).m_20712_("mineminenomi:kaen_boshi"));
   public static final RegistryObject<EntityType<HeatBallProjectile>> HEAT_BALL = ModRegistry.<EntityType<HeatBallProjectile>>registerEntityType("Heat Ball", () -> ModRegistry.createProjectileType(HeatBallProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("heat_ball"));
   public static final RegistryObject<EntityType<CoolBallProjectile>> COOL_BALL = ModRegistry.<EntityType<CoolBallProjectile>>registerEntityType("Cool Ball", () -> ModRegistry.createProjectileType(CoolBallProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("cool_ball"));
   public static final RegistryObject<EntityType<ThunderBallProjectile>> THUNDER_BALL = ModRegistry.<EntityType<ThunderBallProjectile>>registerEntityType("Thunder Ball", () -> ModRegistry.createProjectileType(ThunderBallProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("thunder_ball"));
   public static final RegistryObject<EntityType<GustSwordProjectile>> GUST_SWORD = ModRegistry.<EntityType<GustSwordProjectile>>registerEntityType("Gust Sword", () -> ModRegistry.createProjectileType(GustSwordProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("gust_sword"));
   public static final RegistryObject<EntityType<WeatherEggProjectile>> WEATHER_EGG = ModRegistry.<EntityType<WeatherEggProjectile>>registerEntityType("Weather Egg", () -> ModRegistry.createProjectileType(WeatherEggProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("weather_egg"));
   public static final RegistryObject<EntityType<ThunderLanceProjectile>> THUNDER_LANCE = ModRegistry.<EntityType<ThunderLanceProjectile>>registerEntityType("Thunder Lance", () -> ModRegistry.createProjectileType(ThunderLanceProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:thunder_lance"));
   public static final RegistryObject<EntityType<ThunderboltProjectile>> THUNDERBOLT = ModRegistry.<EntityType<ThunderboltProjectile>>registerEntityType("Thunderbolt", () -> ModRegistry.createProjectileType(ThunderboltProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:thunderbolt"));
   public static final RegistryObject<EntityType<ThunderstormProjectile>> THUNDERSTORM = ModRegistry.<EntityType<ThunderstormProjectile>>registerEntityType("Thunderstorm", () -> ModRegistry.createProjectileType(ThunderstormProjectile::new).m_20699_(0.5F, 0.5F).m_20712_("mineminenomi:thunderstorm"));
   public static final RegistryObject<EntityType<TopEntity>> TOP = ModRegistry.<EntityType<TopEntity>>registerEntityType("Top", () -> ModRegistry.createProjectileType(TopEntity::new).m_20699_(0.25F, 0.25F).m_20712_("mineminenomi:top"));
   public static final RegistryObject<EntityType<NormalBulletProjectile>> NORMAL_BULLET = ModRegistry.<EntityType<NormalBulletProjectile>>registerEntityType("Normal Bullet", () -> ModRegistry.createProjectileType(NormalBulletProjectile::new).m_20699_(0.3F, 0.3F).m_20712_("mineminenomi:normal_bullet"));
   public static final RegistryObject<EntityType<KairosekiBulletProjectile>> KAIROSEKI_BULLET = ModRegistry.<EntityType<KairosekiBulletProjectile>>registerEntityType("Kairoseki Bullet", () -> ModRegistry.createProjectileType(KairosekiBulletProjectile::new).m_20699_(0.3F, 0.3F).m_20712_("mineminenomi:kairoseki_bullet"));
   public static final RegistryObject<EntityType<CannonBallProjectile>> CANNON_BALL = ModRegistry.<EntityType<CannonBallProjectile>>registerEntityType("Cannon Ball", () -> ModRegistry.createProjectileType(CannonBallProjectile::new).m_20699_(0.75F, 0.75F).m_20712_("mineminenomi:cannon_ball"));
   public static final RegistryObject<EntityType<PopGreenProjectile>> POP_GREEN = ModRegistry.<EntityType<PopGreenProjectile>>registerEntityType("Pop Green", () -> ModRegistry.createProjectileType(PopGreenProjectile::new).m_20699_(0.3F, 0.3F).m_20712_("mineminenomi:pop_green"));
   public static final RegistryObject<EntityType<HookEntity>> HOOK = ModRegistry.<EntityType<HookEntity>>registerEntityType("Hook", () -> ModRegistry.createProjectileType(HookEntity::new).m_20712_("mineminenomi:hook"));
   public static final RegistryObject<EntityType<AxeDialProjectile>> AXE_DIAL_PROJECTILE = ModRegistry.<EntityType<AxeDialProjectile>>registerEntityType("Axe Dial", () -> ModRegistry.createProjectileType(AxeDialProjectile::new).m_20699_(3.5F, 0.5F).m_20712_("mineminenomi:axe_dial_projectile"));
   public static final RegistryObject<EntityType<MilkyDialProjectile>> MILKY_DIAL_PROJECTILE = ModRegistry.<EntityType<MilkyDialProjectile>>registerEntityType("Milky Dial", () -> ModRegistry.createProjectileType(MilkyDialProjectile::new).m_20699_(0.3F, 0.3F).m_20712_("mineminenomi:milky_dial_projectile"));
   public static final RegistryObject<EntityType<LightningDischargeEntity>> LIGHTNING_DISCHARGE = ModRegistry.<EntityType<LightningDischargeEntity>>registerEntityType("Lightning Discharge", () -> ModRegistry.createProjectileType(LightningDischargeEntity::new).m_20699_(0.1F, 0.1F).m_20712_("mineminenomi:lightning_discharge"));

   public static void init() {
   }

   public static class Client {
      private static final ResourceLocation MAGMA_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/magma.png");
      private static final ResourceLocation MERO_MELLOW_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/mero_mero_mellow.png");
      private static final ResourceLocation BRICK_BAT_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/brick_bat.png");
      private static final ResourceLocation NORO_BEAM_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/noro_noro_beam.png");
      private static final ResourceLocation TSUNO_TOKAGE_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/tsuno_tokage.png");
      private static final ResourceLocation HIKEN_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/hiken.png");
      private static final ResourceLocation ICE_BLOCK_PARTISAN_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/ice_block_partisan.png");
      private static final ResourceLocation ICE_BLOCK_PHEASANT_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/ice_block_pheasant.png");
      private static final ResourceLocation YUKI_RABI_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/yuki_rabi.png");
      private static final ResourceLocation NEGATIVE_HOLLOW_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/negative_hollow.png");
      private static final ResourceLocation TOKU_HOLLOW_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/toku_hollow.png");
      private static final ResourceLocation DRAGON_ROAR_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/dragons_roar.png");
      private static final ResourceLocation DORU_MORI_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/doru_doru_arts_mori.png");
      private static final ResourceLocation SHARKS_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/pack_of_sharks.png");
      private static final ResourceLocation TOP_TEXTURE = ResourceLocation.fromNamespaceAndPath("mineminenomi", "textures/models/projectiles/top.png");

      public static void registerLayers(EntityRenderersEvent.RegisterLayerDefinitions event) {
         event.registerLayerDefinition(CubeModel.LAYER_LOCATION, CubeModel::createLayer);
         event.registerLayerDefinition(SphereModel.LAYER_LOCATION, SphereModel::createLayer);
         event.registerLayerDefinition(SharkModel.LAYER_LOCATION, SharkModel::createLayer);
         event.registerLayerDefinition(SpearModel.LAYER_LOCATION, SpearModel::createLayer);
         event.registerLayerDefinition(PlaneModel.LAYER_LOCATION, PlaneModel::createLayer);
         event.registerLayerDefinition(MiniHollowModel.LAYER_LOCATION, MiniHollowModel::createLayer);
         event.registerLayerDefinition(NegativeHollowModel.LAYER_LOCATION, NegativeHollowModel::createLayer);
         event.registerLayerDefinition(TokuHollowModel.LAYER_LOCATION, TokuHollowModel::createLayer);
         event.registerLayerDefinition(RingModel.LAYER_LOCATION, RingModel::createLayer);
         event.registerLayerDefinition(HeartModel.LAYER_LOCATION, HeartModel::createLayer);
         event.registerLayerDefinition(TridentModel.LAYER_LOCATION, TridentModel::createLayer);
         event.registerLayerDefinition(PawModel.LAYER_LOCATION, PawModel::createLayer);
         event.registerLayerDefinition(PheasantModel.LAYER_LOCATION, PheasantModel::createLayer);
         event.registerLayerDefinition(CrescentModel.LAYER_LOCATION, CrescentModel::createLayer);
         event.registerLayerDefinition(YukiRabiModel.LAYER_LOCATION, YukiRabiModel::createLayer);
         event.registerLayerDefinition(ArrowModel.LAYER_LOCATION, ArrowModel::createLayer);
         event.registerLayerDefinition(TopModel.LAYER_LOCATION, TopModel::createLayer);
         event.registerLayerDefinition(HydraModel.LAYER_LOCATION, HydraModel::createLayer);
         event.registerLayerDefinition(BrickBatModel.LAYER_LOCATION, BrickBatModel::createLayer);
         event.registerLayerDefinition(PillarModel.LAYER_LOCATION, PillarModel::createLayer);
         event.registerLayerDefinition(BaraFestivalModel.LAYER_LOCATION, BaraFestivalModel::createBodyLayer);
         event.registerLayerDefinition(SpiralEffectModel.LAYER_LOCATION, SpiralEffectModel::createLayer);
      }

      public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event, EntityRendererProvider.Context ctx) {
         Supplier<SphereModel<NuProjectileEntity>> sphereModel = () -> new SphereModel(ctx.m_174023_(SphereModel.LAYER_LOCATION));
         Supplier<CubeModel<NuProjectileEntity>> cubeModel = () -> new CubeModel(ctx.m_174023_(CubeModel.LAYER_LOCATION));
         Supplier<CrescentModel<NuProjectileEntity>> crescentModel = () -> new CrescentModel(ctx.m_174023_(CrescentModel.LAYER_LOCATION));
         Supplier<SharkModel<NuProjectileEntity>> sharkModel = () -> new SharkModel(ctx.m_174023_(SharkModel.LAYER_LOCATION));
         Supplier<SpearModel<NuProjectileEntity>> spearModel = () -> new SpearModel(ctx.m_174023_(SpearModel.LAYER_LOCATION));
         Supplier<TridentModel<NuProjectileEntity>> tridentModel = () -> new TridentModel(ctx.m_174023_(TridentModel.LAYER_LOCATION));
         Supplier<RingModel<NuProjectileEntity>> ringModel = () -> new RingModel(ctx.m_174023_(RingModel.LAYER_LOCATION));
         Supplier<HeartModel<NuProjectileEntity>> heartModel = () -> new HeartModel(ctx.m_174023_(HeartModel.LAYER_LOCATION));
         Supplier<PawModel<NuProjectileEntity>> pawModel = () -> new PawModel(ctx.m_174023_(PawModel.LAYER_LOCATION));
         Supplier<MiniHollowModel<NuProjectileEntity>> miniHollowModel = () -> new MiniHollowModel(ctx.m_174023_(MiniHollowModel.LAYER_LOCATION));
         Supplier<NegativeHollowModel<NuProjectileEntity>> negativeHollowModel = () -> new NegativeHollowModel(ctx.m_174023_(NegativeHollowModel.LAYER_LOCATION));
         Supplier<TokuHollowModel<NuProjectileEntity>> tokuHollowModel = () -> new TokuHollowModel(ctx.m_174023_(TokuHollowModel.LAYER_LOCATION));
         Supplier<YukiRabiModel<NuProjectileEntity>> yukiRabiModel = () -> new YukiRabiModel(ctx.m_174023_(YukiRabiModel.LAYER_LOCATION));
         Supplier<PheasantModel<NuProjectileEntity>> pheasantModel = () -> new PheasantModel(ctx.m_174023_(PheasantModel.LAYER_LOCATION));
         Supplier<ArrowModel<NuProjectileEntity>> arrowModel = () -> new ArrowModel(ctx.m_174023_(ArrowModel.LAYER_LOCATION));
         Supplier<TopModel<NuProjectileEntity>> topModel = () -> new TopModel(ctx.m_174023_(TopModel.LAYER_LOCATION));
         Supplier<BrickBatModel<NuProjectileEntity>> brickBatModel = () -> new BrickBatModel(ctx.m_174023_(BrickBatModel.LAYER_LOCATION));
         Supplier<PillarModel<NuProjectileEntity>> pillarModel = () -> new PillarModel(ctx.m_174023_(PillarModel.LAYER_LOCATION));
         Supplier<PunkGibsonModel<NuProjectileEntity>> punkGibsonModel = () -> new PunkGibsonModel(ctx.m_174023_(PunkGibsonModel.LAYER_LOCATION));
         Supplier<SpiralEffectModel<NuProjectileEntity>> spiralEffectModel = () -> new SpiralEffectModel(ctx.m_174023_(SpiralEffectModel.LAYER_LOCATION));
         event.registerEntityRenderer((EntityType)ModProjectiles.RELAX_HOUR.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#33FFFFFF").setScale((double)1.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.BERO_CANNON.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor("#989898").setScale((double)2.0F, (double)2.0F, (double)2.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.BARRIER_CRASH.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor("#87CEFAAA").setScale((double)8.0F, (double)10.0F, (double)0.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.BARRIERBILITY_STAIRS.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setScale((double)0.0F, (double)0.0F, (double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.STICKY_PROJECTILE.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setTexture(ModResources.BETA_COATING).setColor(0.0F, 1.0F, 0.0F, 0.4F).setScale((double)0.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.BETA_BETA_CHAIN.get(), (new NuLightningEntityRenderer.Factory()).setTexture(ModResources.BETA_COATING));
         event.registerEntityRenderer((EntityType)ModProjectiles.NOSE_FANCY_CANNON.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor("3D2B1F").setScale(0.4, 0.4, 0.4));
         event.registerEntityRenderer((EntityType)ModProjectiles.BREEZE_BREATH_BOMB.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("3D2B1F").setScale((double)1.0F, (double)1.0F, (double)1.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.HIKEN.get(), (new NuProjectileRenderer.Factory()).setUseArmSkin().setTexture(HIKEN_TEXTURE).setScale((double)1.5F).setGlowing());
         event.registerEntityRenderer((EntityType)ModProjectiles.HIGAN.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor(0.9F, 0.4F, 0.15F, 0.7F).setScale((double)0.5F, (double)0.5F, (double)1.5F).setGlowing());
         event.registerEntityRenderer((EntityType)ModProjectiles.DAI_ENKAI_ENTEI.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor(0.9F, 0.4F, 0.15F, 0.7F).setScale((double)15.0F).setGlowing());
         event.registerEntityRenderer((EntityType)ModProjectiles.DAI_ENKAI_ONIBI.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor(0.9F, 0.4F, 0.15F, 0.7F).setScale((double)3.75F, (double)3.75F, (double)1.875F).setGlowing());
         event.registerEntityRenderer((EntityType)ModProjectiles.HIDARUMA.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor(0.0F, 1.0F, 0.0F, 1.0F).setScale(1.2).setGlowing());
         event.registerEntityRenderer((EntityType)ModProjectiles.JUJIKA.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor(0.9F, 0.4F, 0.15F, 1.0F).setScale((double)1.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.NEKKAI_GYORAI.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor("#FF6347").setScale((double)0.25F, (double)0.25F, (double)6.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.SHISHA_NO_TE.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.ICE_BLOCK_PARTISAN.get(), (new NuProjectileRenderer.Factory()).setModel(tridentModel).setTexture(ICE_BLOCK_PARTISAN_TEXTURE).setScale((double)1.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.ICE_BALL.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#36648B").setScale((double)5.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.ICE_BLOCK_PHEASANT.get(), (new NuProjectileRenderer.Factory()).setModel(pheasantModel).setTexture(ICE_BLOCK_PHEASANT_TEXTURE).setScale((double)5.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.ICE_BLOCK_AVALANCHE.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#54f7ff").setScale((double)8.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.YUKI_RABI.get(), (new NuProjectileRenderer.Factory()).setModel(yukiRabiModel).setTexture(YUKI_RABI_TEXTURE).setScale((double)1.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.WHITE_BLOW.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.WHITE_BLOW_RUSH.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.WHITE_SNAKE.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.WHITE_OUT.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.NORO_NORO_BEAM.get(), (new NuProjectileRenderer.Factory()).setModel(ringModel).setTexture(NORO_BEAM_TEXTURE).setScale((double)5.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.NEGATIVE_HOLLOW.get(), (new NuProjectileRenderer.Factory()).setModel(negativeHollowModel).setTexture(NEGATIVE_HOLLOW_TEXTURE).setAlpha(120).setScale((double)2.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.MINI_HOLLOW.get(), (new NuProjectileRenderer.Factory()).setModel(miniHollowModel).setColor("#F8F8FF").setAlpha(120));
         event.registerEntityRenderer((EntityType)ModProjectiles.TOKU_HOLLOW.get(), (new NuProjectileRenderer.Factory()).setModel(tokuHollowModel).setTexture(TOKU_HOLLOW_TEXTURE).setAlpha(120).setScale((double)4.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.DRAGONS_ROAR.get(), (new NuProjectileRenderer.Factory()).setModel(ringModel).setTexture(DRAGON_ROAR_TEXTURE).setScale((double)5.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.TODOROKI.get(), new NuLightningEntityRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.AWASE_BAORI.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor("#524E7C").setScale((double)1.0F, (double)1.0F, (double)5.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.MERO_MERO_MELLOW.get(), (new NuProjectileRenderer.Factory()).setModel(heartModel).setTexture(MERO_MELLOW_TEXTURE).setScale((double)3.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.PISTOL_KISS.get(), (new NuProjectileRenderer.Factory()).setModel(heartModel).setTexture(MERO_MELLOW_TEXTURE).setScale((double)0.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.SLAVE_ARROW.get(), (new NuProjectileRenderer.Factory()).setModel(arrowModel).setColor("#FF69B4"));
         event.registerEntityRenderer((EntityType)ModProjectiles.SPRING_DEATH_KNOCK.get(), new NuLightningEntityRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.PAD_HO.get(), (new NuProjectileRenderer.Factory()).setModel(pawModel).setColor(871954687).setScale((double)1.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.URSUS_SHOCK.get(), (new NuProjectileRenderer.Factory()).setModel(pawModel).setColor(871954687).setScale(0.6));
         event.registerEntityRenderer((EntityType)ModProjectiles.CHARGING_URSUS_SHOCK.get(), new ChargingUrsusShockRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.PAIN.get(), (new NuProjectileRenderer.Factory()).setModel(pawModel).setColor(872393386).setScale(1.6));
         event.registerEntityRenderer((EntityType)ModProjectiles.AMATERASU.get(), (new NuLightningEntityRenderer.Factory()).setLightningMode());
         event.registerEntityRenderer((EntityType)ModProjectiles.YASAKANI_NO_MAGATAMA.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor(1.0F, 0.9F, 0.1F, 0.8F).setScale((double)0.5F, (double)0.5F, (double)0.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.DAI_FUNKA.get(), (new NuProjectileRenderer.Factory()).setUseArmSkin().setScale((double)20.0F).setTexture(MAGMA_TEXTURE).setColor(1.0F, 1.0F, 1.0F, 0.8F));
         event.registerEntityRenderer((EntityType)ModProjectiles.RYUSEI_KAZAN.get(), (new NuProjectileRenderer.Factory()).setUseArmSkin().setScale((double)15.0F).setTexture(MAGMA_TEXTURE).setColor(0.8F, 0.8F, 0.8F, 0.9F));
         event.registerEntityRenderer((EntityType)ModProjectiles.MEIGO.get(), (new NuLightningEntityRenderer.Factory()).setTexture(MAGMA_TEXTURE));
         event.registerEntityRenderer((EntityType)ModProjectiles.HANA_HANDS.get(), new HanaHandsRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.HANA_FEET.get(), (new NuProjectileRenderer.Factory()).setUseLegSkin().setScale((double)8.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.CAMPO_DE_FLORES.get(), new CampoDeFloresRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.DORU_DORU_ARTS_MORI.get(), (new NuProjectileRenderer.Factory()).setModel(spearModel).setScale((double)2.0F).setTexture(DORU_MORI_TEXTURE));
         event.registerEntityRenderer((EntityType)ModProjectiles.CANDLE_LOCK.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.CHAMP_FIGHT.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setScale((double)2.0F).setColor("#C3C3C3"));
         event.registerEntityRenderer((EntityType)ModProjectiles.GAS_ROBE.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.GASTILLE.get(), new NuLightningEntityRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.DESERT_SPADA.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.DESERT_GRANDE_ESPADA.get(), (new NuProjectileRenderer.Factory()).setModel(pillarModel).setColor("#C2B280").setScale((double)3.0F, (double)3.0F, (double)3.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.SABLES_PESADO.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor(12759680).setScale((double)6.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.GEKISHIN.get(), new NuProjectileRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.SPIRAL_HOLLOW.get(), (new NuProjectileRenderer.Factory()).setUseArmSkin().setScale((double)5.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.SPARKLING_DAISY_AFTER.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.POISON_SPIT.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#A020F0").setScale((double)1.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.IMPACT_BLAST.get(), new NuProjectileRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.SAGARI_NO_RYUSEI.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#51585B").setScale((double)30.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.MOKO.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.CANDY_ESCALATOR.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.CANDY_WAVE.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.TAMAITO.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#dee1e5").setScale((double)0.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.STRING_PILLAR.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor("#dee1e5").setScale((double)0.5F, (double)0.5F, (double)20.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.OVERHEAT.get(), new NuLightningEntityRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.BRICK_BAT.get(), (new NuProjectileRenderer.Factory()).setModel(brickBatModel).setTexture(BRICK_BAT_TEXTURE));
         event.registerEntityRenderer((EntityType)ModProjectiles.BLACK_BOX.get(), (new NuProjectileRenderer.Factory()).setModel(brickBatModel).setTexture(BRICK_BAT_TEXTURE));
         event.registerEntityRenderer((EntityType)ModProjectiles.TSUNO_TOKAGE.get(), (new NuProjectileRenderer.Factory()).setModel(pillarModel).setTexture(TSUNO_TOKAGE_TEXTURE).setScale((double)5.0F, (double)5.0F, (double)5.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.HYDRA.get(), new HydraRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.CHLORO_BALL.get(), new ChloroBallRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.VENOM_ROAD.get(), new HydraRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.GOMU_GOMU_NO_PISTOL.get(), (new NuLightningEntityRenderer.Factory()).setUseArmSkin());
         event.registerEntityRenderer((EntityType)ModProjectiles.GOMU_GOMU_NO_JET_PISTOL.get(), (new NuLightningEntityRenderer.Factory()).setUseArmSkin());
         event.registerEntityRenderer((EntityType)ModProjectiles.GOMU_GOMU_NO_ELEPHANT_GUN.get(), (new NuLightningEntityRenderer.Factory()).setUseArmSkin());
         event.registerEntityRenderer((EntityType)ModProjectiles.GOMU_GOMU_NO_KING_KONG_GUN.get(), (new NuLightningEntityRenderer.Factory()).setUseArmSkin());
         event.registerEntityRenderer((EntityType)ModProjectiles.GOMU_GOMU_NO_BAJRANG_GUN.get(), (new NuLightningEntityRenderer.Factory()).setUseArmSkin());
         event.registerEntityRenderer((EntityType)ModProjectiles.GOMU_GOMU_NO_BAZOOKA.get(), (new NuLightningEntityRenderer.Factory()).setUseArmSkin());
         event.registerEntityRenderer((EntityType)ModProjectiles.GOMU_GOMU_NO_JET_BAZOOKA.get(), (new NuLightningEntityRenderer.Factory()).setUseArmSkin());
         event.registerEntityRenderer((EntityType)ModProjectiles.GOMU_GOMU_NO_GRIZZLY_MAGNUM.get(), (new NuLightningEntityRenderer.Factory()).setUseArmSkin());
         event.registerEntityRenderer((EntityType)ModProjectiles.GOMU_GOMU_NO_LEO_BAZOOKA.get(), (new NuLightningEntityRenderer.Factory()).setUseArmSkin());
         event.registerEntityRenderer((EntityType)ModProjectiles.GOMU_GOMU_NO_ROCKET.get(), (new NuLightningEntityRenderer.Factory()).setUseArmSkin());
         event.registerEntityRenderer((EntityType)ModProjectiles.SANGO.get(), (new NuLightningEntityRenderer.Factory()).setLightningMode());
         event.registerEntityRenderer((EntityType)ModProjectiles.EL_THOR.get(), (new NuLightningEntityRenderer.Factory()).setLightningMode());
         event.registerEntityRenderer((EntityType)ModProjectiles.RAIGO.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor(-11053751).setScale((double)60.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.RAIGO_LIGHTNING.get(), (new NuLightningEntityRenderer.Factory()).setLightningMode());
         event.registerEntityRenderer((EntityType)ModProjectiles.LIBERATION.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor("#000000").setScale((double)1.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.DARK_MATTER.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#000000").setScale((double)9.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.BLACK_ROAD.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F, (double)0.0F, (double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.PUNK_GIBSON.get(), (new NuProjectileRenderer.Factory()).setModel(punkGibsonModel).setScale((double)2.0F, (double)2.0F, (double)2.0F).setTexture(ModResources.PUNK_TEXTURE));
         event.registerEntityRenderer((EntityType)ModProjectiles.PUNK_PISTOL.get(), (new NuProjectileRenderer.Factory()).setModel(spearModel).setColor("#2b2930"));
         event.registerEntityRenderer((EntityType)ModProjectiles.DAMNED_PUNK.get(), new NuLightningEntityRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.GENOCIDE_RAID_EFFECT.get(), new GenocideRaidRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.BARIZODON.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor("#fbf916").setScale((double)2.0F, 0.3, (double)2.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.TEMPURAUDON.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor("#5b5b5b").setScale((double)1.0F, (double)1.0F, (double)1.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.BARA_BARA_HO.get(), (new NuProjectileRenderer.Factory()).setUseArmSkin().setScale((double)1.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.DAI_CIRCUS.get(), (new NuProjectileRenderer.Factory()).setUseArmSkin().setScale((double)1.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.BARA_FESTIVAL.get(), new BaraFestivalRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.PHOENIX_GOEN.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale((double)0.0F, (double)0.0F, (double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.RANKYAKU.get(), (new NuProjectileRenderer.Factory()).setModel(crescentModel).setColor("#B1B1E1").setScale((double)1.0F, (double)1.5F, (double)1.0F).setRotation(0.0F, 0.0F, 90.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.ROKUOGAN.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.UCHIMIZU.get(), (new NuProjectileRenderer.Factory()).setModel(cubeModel).setColor("#00CED1").setScale((double)0.5F, (double)0.5F, (double)1.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.PACK_OF_SHARKS.get(), (new NuProjectileRenderer.Factory()).setModel(sharkModel).setTexture(SHARKS_TEXTURE).setScale(0.8, 0.8, 1.2));
         event.registerEntityRenderer((EntityType)ModProjectiles.YARINAMI.get(), (new NuProjectileRenderer.Factory()).setModel(spearModel).setColor("#00CED1").setScale((double)5.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.MIZU_TAIHO.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#00CED155").setScale((double)25.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.MIZU_SHURYUDAN.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#00CED155").setScale((double)2.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.FRESH_FIRE.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F, (double)0.0F, (double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.STRONG_RIGHT.get(), (new NuProjectileRenderer.Factory()).setUseArmSkin().setScale((double)1.5F, (double)1.5F, 1.7));
         event.registerEntityRenderer((EntityType)ModProjectiles.COUP_DE_VENT.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F, (double)0.0F, (double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.RADICAL_BEAM.get(), (new NuLightningEntityRenderer.Factory()).setLightningMode());
         event.registerEntityRenderer((EntityType)ModProjectiles.ELECTRICAL_LUNA.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F, (double)0.0F, (double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.ELECTRICAL_SHOWER.get(), (new NuProjectileRenderer.Factory()).setScale((double)0.0F, (double)0.0F, (double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.ELECTRO_VISUAL.get(), (new NuLightningEntityRenderer.Factory()).setLightningMode());
         event.registerEntityRenderer((EntityType)ModProjectiles.YAKKODORI.get(), (new NuProjectileRenderer.Factory()).setModel(crescentModel).setColor(6019066));
         event.registerEntityRenderer((EntityType)ModProjectiles.SANBYAKUROKUJU_POUND_HO.get(), (new NuProjectileRenderer.Factory()).setModel(crescentModel).setColor(6019066).setRotation(0.0F, 0.0F, 90.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.SANJUROKU_POUND_HO.get(), (new NuProjectileRenderer.Factory()).setColor(6019066).setRotation(0.0F, 0.0F, 90.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.NANAHYAKUNIJU_POUND_HO.get(), (new NuProjectileRenderer.Factory()).setColor(6019066).setRotation(0.0F, 0.0F, 90.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.NANAJUNI_POUND_HO.get(), (new NuProjectileRenderer.Factory()).setColor(6019066).setRotation(0.0F, 0.0F, 90.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.HYAKUHACHI_POUND_HO.get(), (new NuProjectileRenderer.Factory()).setColor(6019066).setRotation(0.0F, 0.0F, 90.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.SENHACHIJU_POUND_HO.get(), (new NuProjectileRenderer.Factory()).setColor(6019066).setRotation(0.0F, 0.0F, 90.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.TATSU_MAKI.get(), (new NuProjectileRenderer.Factory()).setColor(6019066).setScale((double)4.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.BUTO_KAITEN.get(), (new NuProjectileRenderer.Factory()).setUseLegSkin().setScale((double)3.0F, (double)3.0F, (double)3.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.KING_PUNCH.get(), (new NuProjectileRenderer.Factory()).setUseArmSkin().setScale((double)3.0F, (double)3.0F, (double)3.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.EXTRA_HACHIS.get(), (new NuProjectileRenderer.Factory()).setUseLegSkin().setScale((double)3.0F, (double)3.0F, (double)3.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.POELE_A_FRIRE.get(), (new NuProjectileRenderer.Factory()).setUseLegSkin().setScale((double)3.0F, (double)3.0F, (double)3.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.HI_NO_TORI_BOSHI.get(), (new NuProjectileRenderer.Factory()).setModel(pheasantModel).setScale((double)2.0F).setColor("#63110E"));
         event.registerEntityRenderer((EntityType)ModProjectiles.KEMURI_BOSHI.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale((double)0.5F).setColor("#C0C0C0"));
         event.registerEntityRenderer((EntityType)ModProjectiles.RENPATSU_NAMARI_BOSHI.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale((double)0.5F).setColor("#C0C0C0"));
         event.registerEntityRenderer((EntityType)ModProjectiles.SAKURETSU_SABOTEN_BOSHI.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale((double)0.5F).setColor("#437C17"));
         event.registerEntityRenderer((EntityType)ModProjectiles.TETSU_BOSHI.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale((double)0.5F).setColor("#C0C0C0"));
         event.registerEntityRenderer((EntityType)ModProjectiles.TOKUYO_ABURA_BOSHI.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale((double)0.5F).setColor("#C0C0C0"));
         event.registerEntityRenderer((EntityType)ModProjectiles.NEMURI_BOSHI.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale((double)0.5F).setColor("#FF88FF"));
         event.registerEntityRenderer((EntityType)ModProjectiles.KAEN_BOSHI.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale((double)2.0F).setColor("#63110E"));
         event.registerEntityRenderer((EntityType)ModProjectiles.HEAT_BALL.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#FF0000BB").setScale((double)2.0F, (double)2.0F, (double)2.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.COOL_BALL.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#0000FFBB").setScale((double)2.0F, (double)2.0F, (double)2.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.THUNDER_BALL.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#FFFF00BB").setScale((double)2.0F, (double)2.0F, (double)2.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.GUST_SWORD.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale((double)0.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.WEATHER_EGG.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#8B8B8BBB").setScale((double)2.0F, (double)2.0F, (double)2.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.THUNDER_LANCE.get(), new NuLightningEntityRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.THUNDERBOLT.get(), new NuLightningEntityRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.THUNDERSTORM.get(), new NuLightningEntityRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.TOP.get(), (new NuProjectileRenderer.Factory()).setModel(topModel).setTexture(TOP_TEXTURE));
         event.registerEntityRenderer((EntityType)ModProjectiles.NORMAL_BULLET.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#878787").setScale((double)0.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.KAIROSEKI_BULLET.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#F3F3F3").setScale((double)0.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.CANNON_BALL.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setColor("#878787").setScale((double)2.5F));
         event.registerEntityRenderer((EntityType)ModProjectiles.POP_GREEN.get(), new PopGreenRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.AXE_DIAL_PROJECTILE.get(), (new NuProjectileRenderer.Factory()).setModel(crescentModel).setColor("#B1B1E1").setScale((double)1.0F, (double)1.5F, (double)1.0F).setRotation(0.0F, 0.0F, 90.0F));
         event.registerEntityRenderer((EntityType)ModProjectiles.MILKY_DIAL_PROJECTILE.get(), (new NuProjectileRenderer.Factory()).setModel(sphereModel).setScale(0.1).setColor("#69E3FF"));
         event.registerEntityRenderer((EntityType)ModProjectiles.HOOK.get(), new HookRenderer.Factory());
         event.registerEntityRenderer((EntityType)ModProjectiles.LIGHTNING_DISCHARGE.get(), new LightningDischargeRenderer.Factory());
      }
   }
}
