package xyz.pixelatedw.mineminenomi.init;

import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.TieredItem;
import net.minecraftforge.registries.RegistryObject;
import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierbilityBatAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruArtsKenAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.IceSaberAbility;
import xyz.pixelatedw.mineminenomi.abilities.noro.NoroNoroBeamSwordAbility;
import xyz.pixelatedw.mineminenomi.abilities.ope.GammaKnifeAbility;
import xyz.pixelatedw.mineminenomi.abilities.pika.AmaNoMurakumoAbility;
import xyz.pixelatedw.mineminenomi.abilities.yuki.TabiraYukiAbility;
import xyz.pixelatedw.mineminenomi.items.weapons.AbilitySwordItem;
import xyz.pixelatedw.mineminenomi.items.weapons.BlueSwordItem;
import xyz.pixelatedw.mineminenomi.items.weapons.ChakramItem;
import xyz.pixelatedw.mineminenomi.items.weapons.ClimaTactItem;
import xyz.pixelatedw.mineminenomi.items.weapons.DoruPickaxeItem;
import xyz.pixelatedw.mineminenomi.items.weapons.KujaBowItem;
import xyz.pixelatedw.mineminenomi.items.weapons.ModGunItem;
import xyz.pixelatedw.mineminenomi.items.weapons.ModSpearItem;
import xyz.pixelatedw.mineminenomi.items.weapons.ModSwordItem;
import xyz.pixelatedw.mineminenomi.items.weapons.PopGreenBowItem;
import xyz.pixelatedw.mineminenomi.items.weapons.ScissorsItem;
import xyz.pixelatedw.mineminenomi.items.weapons.WarabideSwordItem;

public class ModWeapons {
   public static final RegistryObject<ModSwordItem> SCISSORS = ModRegistry.<ModSwordItem>registerItem("Scissors", ScissorsItem::new);
   public static final RegistryObject<ModSwordItem> KIKOKU = ModRegistry.<ModSwordItem>registerItem("Kikoku", () -> new ModSwordItem(ModTiers.KIKOKU, 7));
   public static final RegistryObject<ModSwordItem> KIRIBACHI = ModRegistry.<ModSwordItem>registerItem("Kiribachi", () -> new ModSwordItem((new ModSwordItem.ModsBuilder(ModTiers.KIRIBACHI, 6)).reach(0.25F)));
   public static final RegistryObject<ModSwordItem> YORU = ModRegistry.<ModSwordItem>registerItem("Yoru", () -> new ModSwordItem(ModTiers.YORU, 11, -2.0F));
   public static final RegistryObject<ModSwordItem> MURAKUMOGIRI = ModRegistry.<ModSwordItem>registerItem("Murakumogiri", () -> new ModSwordItem((new ModSwordItem.ModsBuilder(ModTiers.MURAKUMOGIRI, 12)).speed(-2.9F).reach(1.5F)));
   public static final RegistryObject<ModSwordItem> HOOK = ModRegistry.<ModSwordItem>registerItem("Hook", () -> (new ModSwordItem(ModTiers.HOOK, 5)).addEffect(MobEffects.f_19614_, 300));
   public static final RegistryObject<TieredItem> UMBRELLA = ModRegistry.<TieredItem>registerItem("Umbrella", () -> new TieredItem(ModTiers.UMBRELLA, new Item.Properties()));
   public static final RegistryObject<ModSwordItem> NONOSAMA_STAFF = ModRegistry.<ModSwordItem>registerItem("Nonosama Staff", () -> new ModSwordItem((new ModSwordItem.ModsBuilder(ModTiers.NONOSAMA_STAFF, 6)).speed(-2.6F).reach(1.0F)));
   public static final RegistryObject<ModSpearItem> NONOSAMA_TRIDENT = ModRegistry.<ModSpearItem>registerItem("Nonosama Trident", () -> new ModSpearItem((new ModSwordItem.ModsBuilder(ModTiers.NONOSAMA_TRIDENT, 9)).speed(-2.6F).reach(1.0F)));
   public static final RegistryObject<ModSwordItem> HAMMER_5T = ModRegistry.<ModSwordItem>registerItem("5t Hammer", () -> new ModSwordItem(ModTiers.HAMMER_5T, 1));
   public static final RegistryObject<ModSwordItem> ACES_KNIFE = ModRegistry.<ModSwordItem>registerItem("Ace's Knife", () -> new ModSwordItem(ModTiers.ACES_KNIFE, 4, -1.1F));
   public static final RegistryObject<ModSwordItem> MIHAWKS_KNIFE = ModRegistry.<ModSwordItem>registerItem("Mihawk's Knife", () -> new ModSwordItem(ModTiers.MIHAWKS_KNIFE, 4, -1.1F));
   public static final RegistryObject<ModSwordItem> SANDAI_KITETSU = ModRegistry.<ModSwordItem>registerItem("Sandai Kitetsu", () -> new ModSwordItem(ModTiers.SANDAI_KITETSU, 8, -2.0F));
   public static final RegistryObject<ModSwordItem> WADO_ICHIMONJI = ModRegistry.<ModSwordItem>registerItem("Wado Ichimonji", () -> new ModSwordItem(ModTiers.WADO_ICHIMONJI, 8, -2.0F));
   public static final RegistryObject<ModSwordItem> NIDAI_KITETSU = ModRegistry.<ModSwordItem>registerItem("Nidai Kitetsu", () -> new ModSwordItem(ModTiers.NIDAI_KITETSU, 8, -2.0F));
   public static final RegistryObject<ModSwordItem> SHUSUI = ModRegistry.<ModSwordItem>registerItem("Shusui", () -> new ModSwordItem(ModTiers.SHUSUI, 9, -2.0F));
   public static final RegistryObject<ModSwordItem> ENMA = ModRegistry.<ModSwordItem>registerItem("Enma", () -> new ModSwordItem(ModTiers.ENMA, 9, -2.0F));
   public static final RegistryObject<ModSwordItem> AME_NO_HABAKIRI = ModRegistry.<ModSwordItem>registerItem("Ame no Habakiri", () -> new ModSwordItem(ModTiers.AME_NO_HABAKIRI, 9, -2.0F));
   public static final RegistryObject<ModSwordItem> SOUL_SOLID = ModRegistry.<ModSwordItem>registerItem("Soul Solid", () -> new ModSwordItem(ModTiers.SOUL_SOLID, 6, -1.4F));
   public static final RegistryObject<ModSwordItem> DURANDAL = ModRegistry.<ModSwordItem>registerItem("Durandal", () -> new ModSwordItem(ModTiers.DURANDAL, 6, -1.5F));
   public static final RegistryObject<ModSwordItem> DAISENSO = ModRegistry.<ModSwordItem>registerItem("Daisenso", () -> new ModSwordItem((new ModSwordItem.ModsBuilder(ModTiers.DAISENSO, 5)).speed(-2.6F).reach(1.0F)));
   public static final RegistryObject<ModSwordItem> ACE = ModRegistry.<ModSwordItem>registerItem("Ace", () -> new ModSwordItem(ModTiers.ACE, 11, -1.7F));
   public static final RegistryObject<ModSpearItem> MOGURA = ModRegistry.<ModSpearItem>registerItem("Mogura", () -> new ModSpearItem((new ModSwordItem.ModsBuilder(ModTiers.MOGURA, 10)).speed(-2.6F).reach(1.0F)));
   public static final RegistryObject<ModSwordItem> DALTONS_SPADE = ModRegistry.<ModSwordItem>registerItem("Dalton's Spade", () -> new ModSwordItem(ModTiers.DALTONS_SPADE, 6, -2.0F));
   public static final RegistryObject<ModSwordItem> SAMEKIRI_BOCHO = ModRegistry.<ModSwordItem>registerItem("Samekiri Bocho", () -> new ModSwordItem((new ModSwordItem.ModsBuilder(ModTiers.SAMEKIRI_BOCHO, 7)).speed(-2.0F).reach(0.25F)));
   public static final RegistryObject<ModSwordItem> CAT_CLAWS = ModRegistry.<ModSwordItem>registerItem("Cat Claws", () -> new ModSwordItem(ModTiers.CAT_CLAWS, 7, -1.3F));
   public static final RegistryObject<ModSwordItem> HASSAIKAI = ModRegistry.<ModSwordItem>registerItem("Hassaikai", () -> new ModSwordItem((new ModSwordItem.ModsBuilder(ModTiers.HASSAIKAI, 12)).speed(-3.2F).reach(0.25F)));
   public static final RegistryObject<ModSwordItem> GRYPHON = ModRegistry.<ModSwordItem>registerItem("Gryphon", () -> new ModSwordItem(ModTiers.GRYPHON, 10, -2.0F));
   public static final RegistryObject<ModSwordItem> AXE_HAND = ModRegistry.<ModSwordItem>registerItem("Axe Hand", () -> new ModSwordItem(ModTiers.AXE_HAND, 5, -2.2F));
   public static final RegistryObject<ModSwordItem> PIPE = ModRegistry.<ModSwordItem>registerItem("Pipe", () -> new ModSwordItem(ModTiers.PIPE, 5));
   public static final RegistryObject<ModSwordItem> TONFA = ModRegistry.<ModSwordItem>registerItem("Tonfa", () -> new ModSwordItem(ModTiers.TONFA, 5));
   public static final RegistryObject<ModSwordItem> JITTE = ModRegistry.<ModSwordItem>registerItem("Jitte", () -> (new ModSwordItem(ModTiers.JITTE, 6)).setDyeable());
   public static final RegistryObject<ModSwordItem> KATANA = ModRegistry.<ModSwordItem>registerItem("Katana", () -> (new ModSwordItem(ModTiers.KATANA, 5, -2.2F)).setDyeable());
   public static final RegistryObject<ModSwordItem> CUTLASS = ModRegistry.<ModSwordItem>registerItem("Cutlass", () -> (new ModSwordItem(ModTiers.CUTLASS, 5, -2.4F)).setDyeable());
   public static final RegistryObject<ModSwordItem> BROADSWORD = ModRegistry.<ModSwordItem>registerItem("Broadsword", () -> (new ModSwordItem(ModTiers.BROADSWORD, 6, -2.5F)).setDyeable());
   public static final RegistryObject<ModSwordItem> BISENTO = ModRegistry.<ModSwordItem>registerItem("Bisento", () -> (new ModSwordItem(ModTiers.BISENTO, 6, -2.7F)).setDyeable());
   public static final RegistryObject<ModSwordItem> DAGGER = ModRegistry.<ModSwordItem>registerItem("Dagger", () -> (new ModSwordItem(ModTiers.DAGGER, 4, -1.3F)).setDyeable());
   public static final RegistryObject<ModSwordItem> AXE = ModRegistry.<ModSwordItem>registerItem("Axe", () -> (new ModSwordItem(ModTiers.AXE, 6, -2.7F)).setDyeable());
   public static final RegistryObject<ModSpearItem> SPEAR = ModRegistry.<ModSpearItem>registerItem("Spear", () -> (ModSpearItem)(new ModSpearItem((new ModSwordItem.ModsBuilder(ModTiers.SPEAR, 5)).speed(-2.5F).reach(1.0F))).setDyeable());
   public static final RegistryObject<ModSwordItem> CLEAVER = ModRegistry.<ModSwordItem>registerItem("Cleaver", () -> (new ModSwordItem((new ModSwordItem.ModsBuilder(ModTiers.CLEAVER, 6)).speed(-2.5F).reach(0.25F))).setDyeable());
   public static final RegistryObject<ModSwordItem> MACE = ModRegistry.<ModSwordItem>registerItem("Mace", () -> (new ModSwordItem((new ModSwordItem.ModsBuilder(ModTiers.MACE, 8)).speed(-3.2F).reach(0.25F))).setDyeable());
   public static final RegistryObject<ChakramItem> CHAKRAM = ModRegistry.<ChakramItem>registerItem("Chakram", ChakramItem::new);
   public static final RegistryObject<ClimaTactItem> CLIMA_TACT = ModRegistry.<ClimaTactItem>registerItem("Clima Tact", () -> new ClimaTactItem(ModTiers.CLIMA_TACT, 1));
   public static final RegistryObject<ClimaTactItem> PERFECT_CLIMA_TACT = ModRegistry.<ClimaTactItem>registerItem("Perfect Clima Tact", () -> new ClimaTactItem(ModTiers.PERFECT_CLIMA_TACT, 2));
   public static final RegistryObject<ClimaTactItem> SORCERY_CLIMA_TACT = ModRegistry.<ClimaTactItem>registerItem("Sorcery Clima Tact", () -> new ClimaTactItem(ModTiers.SORCERY_CLIMA_TACT, 4));
   public static final RegistryObject<ModGunItem> FLINTLOCK = ModRegistry.<ModGunItem>registerItem("Flintlock", () -> (new ModGunItem(200)).setShotCooldown(15).setReloadCooldown(40).setInaccuracy(1.5F).setBulletSpeed(3.0F).setDamageMultiplier(1.0F).setGunpowderLimit(5));
   public static final RegistryObject<ModGunItem> SENRIKU = ModRegistry.<ModGunItem>registerItem("Senriku", () -> (new ModGunItem(800)).setShotCooldown(20).setReloadCooldown(60).setInaccuracy(0.0F).setBulletSpeed(4.5F).setDamageMultiplier(2.5F).setGunpowderLimit(4));
   public static final RegistryObject<ModGunItem> BAZOOKA = ModRegistry.<ModGunItem>registerItem("Bazooka", () -> (new ModGunItem(800, ModGunItem.BAZOOKA_AMMO)).setShotCooldown(60).setInaccuracy(0.5F).setBulletSpeed(3.0F).setDamageMultiplier(2.0F).setGunpowderLimit(1));
   public static final RegistryObject<ModGunItem> WALKER = ModRegistry.<ModGunItem>registerItem("Walker", () -> (new ModGunItem(2500)).setShotCooldown(10).setReloadCooldown(30).setInaccuracy(0.5F).setBulletSpeed(4.0F).setDamageMultiplier(2.0F).setGunpowderLimit(7));
   public static final RegistryObject<KujaBowItem> KUJA_BOW = ModRegistry.<KujaBowItem>registerItem("Kuja Bow", KujaBowItem::new);
   public static final RegistryObject<PopGreenBowItem> KABUTO = ModRegistry.<PopGreenBowItem>registerItem("Kabuto", () -> new PopGreenBowItem(400));
   public static final RegistryObject<PopGreenBowItem> BLACK_KABUTO = ModRegistry.<PopGreenBowItem>registerItem("Kuro Kabuto", () -> new PopGreenBowItem(800));
   public static final RegistryObject<PopGreenBowItem> GINGA_PACHINKO = ModRegistry.<PopGreenBowItem>registerItem("Ginga Pachinko", () -> new PopGreenBowItem(200));
   public static final RegistryObject<AbilitySwordItem<IceSaberAbility>> ICE_SABER = ModRegistry.<AbilitySwordItem<IceSaberAbility>>registerItem("Ice Saber", () -> (AbilitySwordItem)(new AbilitySwordItem(ModTiers.ICE_SABER, IceSaberAbility.INSTANCE, 12, -1.8F)).addEffect((MobEffect)ModEffects.FROSTBITE.get(), 40, 1));
   public static final RegistryObject<AbilitySwordItem<AmaNoMurakumoAbility>> AMA_NO_MURAKUMO = ModRegistry.<AbilitySwordItem<AmaNoMurakumoAbility>>registerItem("Ama no Murakumo", () -> new AbilitySwordItem(ModTiers.AMA_NO_MURAKUMO, AmaNoMurakumoAbility.INSTANCE, 14, 0.0F));
   public static final RegistryObject<AbilitySwordItem<NoroNoroBeamSwordAbility>> NORO_NORO_BEAM_SWORD = ModRegistry.<AbilitySwordItem<NoroNoroBeamSwordAbility>>registerItem("Noro Noro Beam Sword", () -> (AbilitySwordItem)(new AbilitySwordItem(ModTiers.NORO_NORO_BEAM_SWORD, NoroNoroBeamSwordAbility.INSTANCE, 7)).addEffect((MobEffect)ModEffects.NORO_SLOWNESS.get(), 40, 1));
   public static final RegistryObject<AbilitySwordItem<DoruDoruArtsKenAbility>> DORU_DORU_ARTS_KEN = ModRegistry.<AbilitySwordItem<DoruDoruArtsKenAbility>>registerItem("Doru Doru Arts: Ken", () -> (AbilitySwordItem)(new AbilitySwordItem(ModTiers.DORU_DORU_ARTS_KEN, DoruDoruArtsKenAbility.INSTANCE, 7)).setDyeable());
   public static final RegistryObject<DoruPickaxeItem> DORU_PICKAXE = ModRegistry.<DoruPickaxeItem>registerItem("Doru Doru Arts: Pickaxe", () -> new DoruPickaxeItem(ModTiers.DORU_DORU_ARTS_KEN, 1, -2.8F));
   public static final RegistryObject<BlueSwordItem> BLUE_SWORD = ModRegistry.<BlueSwordItem>registerItem("Blue Sword", BlueSwordItem::new);
   public static final RegistryObject<AbilitySwordItem<TabiraYukiAbility>> TABIRA_YUKI = ModRegistry.<AbilitySwordItem<TabiraYukiAbility>>registerItem("Tabira Yuki", () -> (AbilitySwordItem)(new AbilitySwordItem(ModTiers.TABIRA_YUKI, TabiraYukiAbility.INSTANCE, 9, -1.9F)).addEffect((MobEffect)ModEffects.FROSTBITE.get(), 20, 1));
   public static final RegistryObject<WarabideSwordItem> WARABIDE_SWORD = ModRegistry.<WarabideSwordItem>registerItem("Warabide Sword", WarabideSwordItem::new);
   public static final RegistryObject<AbilitySwordItem<BarrierbilityBatAbility>> BARRIERBILITY_BAT = ModRegistry.<AbilitySwordItem<BarrierbilityBatAbility>>registerItem("Barrierbility Bat", () -> new AbilitySwordItem(ModTiers.BARRIERBILITY_BAT, BarrierbilityBatAbility.INSTANCE, 7));
   public static final RegistryObject<AbilitySwordItem<GammaKnifeAbility>> GAMMA_KNIFE = ModRegistry.<AbilitySwordItem<GammaKnifeAbility>>registerItem("Gamma Knife", () -> new AbilitySwordItem(ModTiers.GAMMA_KNIFE, GammaKnifeAbility.INSTANCE, 1, 0.0F));

   public static void init() {
   }
}
