package xyz.pixelatedw.mineminenomi.init;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.HumanoidArm;
import xyz.pixelatedw.mineminenomi.animations.BackflipAnimation;
import xyz.pixelatedw.mineminenomi.animations.BattoStrikeAnimation;
import xyz.pixelatedw.mineminenomi.animations.BellyFlopAnimation;
import xyz.pixelatedw.mineminenomi.animations.BodyRotateAnimation;
import xyz.pixelatedw.mineminenomi.animations.BodyRotateWideArmsAnimation;
import xyz.pixelatedw.mineminenomi.animations.CannonHandlingAnimation;
import xyz.pixelatedw.mineminenomi.animations.CartwheelAnimation;
import xyz.pixelatedw.mineminenomi.animations.CaughtInNetAnimation;
import xyz.pixelatedw.mineminenomi.animations.ChargeCleaveAnimation;
import xyz.pixelatedw.mineminenomi.animations.ChargeNetThrowAnimation;
import xyz.pixelatedw.mineminenomi.animations.ChargePunchAnimation;
import xyz.pixelatedw.mineminenomi.animations.CrossedArmAnimation;
import xyz.pixelatedw.mineminenomi.animations.CrossedArmsAnimation;
import xyz.pixelatedw.mineminenomi.animations.CrossedAttackAnimation;
import xyz.pixelatedw.mineminenomi.animations.DodgeAnimation;
import xyz.pixelatedw.mineminenomi.animations.GeppoAnimation;
import xyz.pixelatedw.mineminenomi.animations.HandStandSpinAnimation;
import xyz.pixelatedw.mineminenomi.animations.HandcuffedAnimation;
import xyz.pixelatedw.mineminenomi.animations.HeadStandSpinAnimation;
import xyz.pixelatedw.mineminenomi.animations.LowSwingArmsAnimation;
import xyz.pixelatedw.mineminenomi.animations.LoweringArmAnimation;
import xyz.pixelatedw.mineminenomi.animations.OneTwoJangoAnimation;
import xyz.pixelatedw.mineminenomi.animations.PitchSpinAnimation;
import xyz.pixelatedw.mineminenomi.animations.PlayDeadAnimation;
import xyz.pixelatedw.mineminenomi.animations.PointArmAnimation;
import xyz.pixelatedw.mineminenomi.animations.PointArmsAnimation;
import xyz.pixelatedw.mineminenomi.animations.PointWeaponAnimation;
import xyz.pixelatedw.mineminenomi.animations.PowerupAnimation;
import xyz.pixelatedw.mineminenomi.animations.PunchRushAnimation;
import xyz.pixelatedw.mineminenomi.animations.RaiseArmAnimation;
import xyz.pixelatedw.mineminenomi.animations.RaiseArmsAnimation;
import xyz.pixelatedw.mineminenomi.animations.RideStrikerAnimation;
import xyz.pixelatedw.mineminenomi.animations.ScratchingAnimation;
import xyz.pixelatedw.mineminenomi.animations.ScreamAnimation;
import xyz.pixelatedw.mineminenomi.animations.ShootSelfForwardAnimation;
import xyz.pixelatedw.mineminenomi.animations.SpecialFlyAnimation;
import xyz.pixelatedw.mineminenomi.animations.SpinToWinAnimation;
import xyz.pixelatedw.mineminenomi.animations.TackleAnimation;
import xyz.pixelatedw.mineminenomi.animations.TakedownKickAnimation;
import xyz.pixelatedw.mineminenomi.animations.TestAnimation;
import xyz.pixelatedw.mineminenomi.animations.ThrowChakramAnimation;
import xyz.pixelatedw.mineminenomi.animations.ThrowSpearAnimation;
import xyz.pixelatedw.mineminenomi.animations.UnconsciousAnimation;
import xyz.pixelatedw.mineminenomi.animations.UnconsciousYamchaAnimation;
import xyz.pixelatedw.mineminenomi.animations.UnicycleRidingAnimation;
import xyz.pixelatedw.mineminenomi.animations.WeaponSlamAnimation;
import xyz.pixelatedw.mineminenomi.animations.WeaponStabDownAnimation;
import xyz.pixelatedw.mineminenomi.animations.bara.BaraCarAnimation;
import xyz.pixelatedw.mineminenomi.animations.blackleg.AntiMannerKickCourseAnimation;
import xyz.pixelatedw.mineminenomi.animations.brawler.RyuNoIbukiAnimation;
import xyz.pixelatedw.mineminenomi.animations.donkrieg.MH5Animation;
import xyz.pixelatedw.mineminenomi.animations.fishmen.SharkOnToothAnimation;
import xyz.pixelatedw.mineminenomi.animations.gomu.GomuBazookaAnimation;
import xyz.pixelatedw.mineminenomi.animations.gomu.GomuDawnWhipAnimation;
import xyz.pixelatedw.mineminenomi.animations.gura.KaishinAnimation;
import xyz.pixelatedw.mineminenomi.animations.hasshoken.ButoAnimation;
import xyz.pixelatedw.mineminenomi.animations.kilo.KiloPressAnimation;
import xyz.pixelatedw.mineminenomi.animations.mandemontactics.DemonicDanceChargeAnimation;
import xyz.pixelatedw.mineminenomi.animations.mandemontactics.DemonicDanceLeapAnimation;
import xyz.pixelatedw.mineminenomi.animations.mandemontactics.DemonicDashAnimation;
import xyz.pixelatedw.mineminenomi.animations.mandemontactics.DemonicSmashAnimation;
import xyz.pixelatedw.mineminenomi.animations.oto.BonAnimation;
import xyz.pixelatedw.mineminenomi.animations.oto.DonAnimation;
import xyz.pixelatedw.mineminenomi.animations.oto.ShanAnimation;
import xyz.pixelatedw.mineminenomi.animations.pacifista.HeadLaserChargeAnimation;
import xyz.pixelatedw.mineminenomi.animations.pteranodon.PteraAssaultFlyAnimation;
import xyz.pixelatedw.mineminenomi.animations.pteranodon.PteraOpenMouthAnimation;
import xyz.pixelatedw.mineminenomi.animations.sniper.AimSniperAnimation;
import xyz.pixelatedw.mineminenomi.animations.suna.BarjanAnimation;
import xyz.pixelatedw.mineminenomi.animations.supa.SparklingDaisyChargeAnimation;
import xyz.pixelatedw.mineminenomi.animations.supa.SpiderAnimation;
import xyz.pixelatedw.mineminenomi.animations.swordsman.DownwardSlashAnimation;
import xyz.pixelatedw.mineminenomi.animations.swordsman.IttoryuChargeAnimation;
import xyz.pixelatedw.mineminenomi.animations.swordsman.OverShoulderSlashAnimation;
import xyz.pixelatedw.mineminenomi.animations.tori.PhoenixAssaultFlyAnimation;
import xyz.pixelatedw.mineminenomi.animations.tori.PhoenixKickAnimation;
import xyz.pixelatedw.mineminenomi.animations.yami.BlackHoleAnimation;
import xyz.pixelatedw.mineminenomi.api.animations.Animation;
import xyz.pixelatedw.mineminenomi.api.animations.AnimationId;

public class ModAnimations {
   public static final AnimationId<CrossedArmsAnimation> CROSSED_ARMS = register("crossed_arms", CrossedArmsAnimation::new);
   public static final AnimationId<CrossedArmAnimation> CROSSED_LEFT_ARM = register("crossed_left_arm", (id) -> new CrossedArmAnimation(id, HumanoidArm.LEFT));
   public static final AnimationId<CrossedArmAnimation> CROSSED_RIGHT_ARM = register("crossed_right_arm", (id) -> new CrossedArmAnimation(id, HumanoidArm.RIGHT));
   public static final AnimationId<HandStandSpinAnimation> HAND_STAND_SPIN = register("hand_stand_spin", HandStandSpinAnimation::new);
   public static final AnimationId<PitchSpinAnimation> PITCH_SPIN = register("pitch_spin", PitchSpinAnimation::new);
   public static final AnimationId<BodyRotateAnimation> YAW_SPIN = register("yaw_spin", (id) -> new BodyRotateAnimation(id, 40.0F));
   public static final AnimationId<PlayDeadAnimation> PLAY_DEAD = register("play_dead", PlayDeadAnimation::new);
   public static final AnimationId<AimSniperAnimation> AIM_SNIPER = register("aim_sniper", AimSniperAnimation::new);
   public static final AnimationId<PunchRushAnimation> PUNCH_RUSH = register("punch_rush", PunchRushAnimation::new);
   public static final AnimationId<GomuBazookaAnimation> GOMU_BAZOOKA = register("gomu_bazooka", GomuBazookaAnimation::new);
   public static final AnimationId<CannonHandlingAnimation> CANNON_HANDLING = register("cannon_handling", CannonHandlingAnimation::new);
   public static final AnimationId<BodyRotateWideArmsAnimation> BODY_ROTATION_WIDE_ARMS = register("body_rotation_wide_arms", (id) -> new BodyRotateWideArmsAnimation(id, -40.0F));
   public static final AnimationId<ChargeCleaveAnimation> CHARGE_CLEAVE = register("charge_cleave", ChargeCleaveAnimation::new);
   public static final AnimationId<ChargePunchAnimation> CHARGE_PUNCH = register("charge_punch", ChargePunchAnimation::new);
   public static final AnimationId<HandcuffedAnimation> HANDCUFFED = register("handcuffed", HandcuffedAnimation::new);
   public static final AnimationId<PointArmsAnimation> POINT_ARMS = register("point_arms", PointArmsAnimation::new);
   public static final AnimationId<PointArmAnimation> POINT_LEFT_ARM = register("point_left_arm", (id) -> new PointArmAnimation(id, HumanoidArm.LEFT));
   public static final AnimationId<PointArmAnimation> POINT_RIGHT_ARM = register("point_right_arm", (id) -> new PointArmAnimation(id, HumanoidArm.RIGHT));
   public static final AnimationId<RaiseArmsAnimation> RAISE_ARMS = register("raise_arms", RaiseArmsAnimation::new);
   public static final AnimationId<RaiseArmAnimation> RAISE_LEFT_ARM = register("raise_left_arm", (id) -> new RaiseArmAnimation(id, HumanoidArm.LEFT));
   public static final AnimationId<RaiseArmAnimation> RAISE_RIGHT_ARM = register("raise_right_arm", (id) -> new RaiseArmAnimation(id, HumanoidArm.RIGHT));
   public static final AnimationId<LowSwingArmsAnimation> LOW_SWING_ARMS = register("low_swing_arms", LowSwingArmsAnimation::new);
   public static final AnimationId<SpecialFlyAnimation> SPECIAL_FLY = register("special_fly", SpecialFlyAnimation::new);
   public static final AnimationId<RideStrikerAnimation> RIDE_STRIKER = register("ride_striker", RideStrikerAnimation::new);
   public static final AnimationId<ThrowSpearAnimation> THROW_SPEAR = register("throw_spear", ThrowSpearAnimation::new);
   public static final AnimationId<PointWeaponAnimation> POINT_WEAPON = register("point_weapon", PointWeaponAnimation::new);
   public static final AnimationId<PteraAssaultFlyAnimation> PTERA_ASSAULT_FLY = register("ptera_assault_fly", PteraAssaultFlyAnimation::new);
   public static final AnimationId<PteraOpenMouthAnimation> PTERA_OPEN_MOUTH = register("ptera_open_mouth", PteraOpenMouthAnimation::new);
   public static final AnimationId<OverShoulderSlashAnimation> OVER_SHOULDER_SLASH = register("over_shoulder_slash", OverShoulderSlashAnimation::new);
   public static final AnimationId<IttoryuChargeAnimation> ITTORYU_CHARGE = register("ittoryu_charge", IttoryuChargeAnimation::new);
   public static final AnimationId<DownwardSlashAnimation> DOWNWARD_SLASH = register("downward_slash", DownwardSlashAnimation::new);
   public static final AnimationId<SparklingDaisyChargeAnimation> SPARKLING_DAISY_CHARGE = register("sparkling_daisy_charge", SparklingDaisyChargeAnimation::new);
   public static final AnimationId<KaishinAnimation> KAISHIN = register("kaishin", KaishinAnimation::new);
   public static final AnimationId<BonAnimation> BON = register("bon", BonAnimation::new);
   public static final AnimationId<DonAnimation> DON = register("don", DonAnimation::new);
   public static final AnimationId<ShanAnimation> SHAN = register("shan", ShanAnimation::new);
   public static final AnimationId<PhoenixAssaultFlyAnimation> PHOENIX_ASSAULT_FLY = register("phoenix_assault_fly", PhoenixAssaultFlyAnimation::new);
   public static final AnimationId<PhoenixKickAnimation> PHOENIX_KICK = register("phoenix_kick", PhoenixKickAnimation::new);
   public static final AnimationId<KiloPressAnimation> KILO_PRESS = register("kilo_press", KiloPressAnimation::new);
   public static final AnimationId<LoweringArmAnimation> LOWERING_RIGHT_ARM = register("lowering_right_arm", LoweringArmAnimation::new);
   public static final AnimationId<TackleAnimation> TACKLE = register("tackle", (id) -> new TackleAnimation(id, HumanoidArm.RIGHT));
   public static final AnimationId<BellyFlopAnimation> BELLY_FLOP = register("belly_flop", BellyFlopAnimation::new);
   public static final AnimationId<WeaponSlamAnimation> WEAPON_SLAM = register("weapon_slam", WeaponSlamAnimation::new);
   public static final AnimationId<SpinToWinAnimation> SPIN_TO_WIN = register("spin_to_win", (id) -> new SpinToWinAnimation(id, -40.0F));
   public static final AnimationId<TakedownKickAnimation> TAKEDOWN_KICK = register("takedown_kick", TakedownKickAnimation::new);
   public static final AnimationId<HeadLaserChargeAnimation> HEAD_LASER_CHARGE = register("head_laser_charge", HeadLaserChargeAnimation::new);
   public static final AnimationId<SharkOnToothAnimation> SHARK_ON_TOOTH = register("shark_on_tooth", SharkOnToothAnimation::new);
   public static final AnimationId<BarjanAnimation> BARJAN = register("barjan", BarjanAnimation::new);
   public static final AnimationId<DemonicDanceChargeAnimation> DEMONIC_DANCE_CHARGE = register("demonic_dance_charge", DemonicDanceChargeAnimation::new);
   public static final AnimationId<DemonicDanceLeapAnimation> DEMONIC_DANCE_LEAP = register("demonic_dance_leap", DemonicDanceLeapAnimation::new);
   public static final AnimationId<DemonicSmashAnimation> DEMONIC_SMASH = register("demonic_smash", DemonicSmashAnimation::new);
   public static final AnimationId<DemonicDashAnimation> DEMONIC_DASH = register("demonic_dash", DemonicDashAnimation::new);
   public static final AnimationId<CrossedAttackAnimation> CROSSED_ATTACK = register("crossed_attack", CrossedAttackAnimation::new);
   public static final AnimationId<ShootSelfForwardAnimation> SHOOT_SELF_FORWARD = register("shoot_self_forward", ShootSelfForwardAnimation::new);
   public static final AnimationId<MH5Animation> MH5_CHARGING = register("mh5_charging", MH5Animation::new);
   public static final AnimationId<CaughtInNetAnimation> CAUGHT_IN_NET = register("caught_in_net", CaughtInNetAnimation::new);
   public static final AnimationId<GomuDawnWhipAnimation> GOMU_DAWN_WHIP = register("gomu_dawn_whip", GomuDawnWhipAnimation::new);
   public static final AnimationId<ChargeNetThrowAnimation> CHARGE_NET_THROW = register("charge_net_throw", ChargeNetThrowAnimation::new);
   public static final AnimationId<UnconsciousAnimation> UNCONSCIOUS = register("unconscious", UnconsciousAnimation::new);
   public static final AnimationId<UnconsciousYamchaAnimation> UNCONSCIOUS_YAMCHA = register("unconscious_yamcha", UnconsciousYamchaAnimation::new);
   public static final AnimationId<UnicycleRidingAnimation> RIDE_UNICYCLE = register("ride_unicycle", UnicycleRidingAnimation::new);
   public static final AnimationId<WeaponStabDownAnimation> STAB_DOWN = register("stab_down", WeaponStabDownAnimation::new);
   public static final AnimationId<ScratchingAnimation> SCRATCHING = register("scratching", ScratchingAnimation::new);
   public static final AnimationId<PowerupAnimation> POWERUP = register("powerup", PowerupAnimation::new);
   public static final AnimationId<BlackHoleAnimation> BLACK_HOLE = register("black_hole", BlackHoleAnimation::new);
   public static final AnimationId<OneTwoJangoAnimation> ONE_TWO_JANGO = register("one_two_jango", OneTwoJangoAnimation::new);
   public static final AnimationId<RyuNoIbukiAnimation> RYU_NO_IBUKI = register("ryu_no_ibuki", RyuNoIbukiAnimation::new);
   public static final AnimationId<BattoStrikeAnimation> BATTO_STRIKE = register("batto_strike", BattoStrikeAnimation::new);
   public static final AnimationId<ThrowChakramAnimation> THROW_CHAKRAM = register("throw_chakram", ThrowChakramAnimation::new);
   public static final AnimationId<SpiderAnimation> SPIDER = register("spider", SpiderAnimation::new);
   public static final AnimationId<AntiMannerKickCourseAnimation> ANTI_MANNER = register("anti_manner", AntiMannerKickCourseAnimation::new);
   public static final AnimationId<ButoAnimation> BUTO = register("buto", ButoAnimation::new);
   public static final AnimationId<HeadStandSpinAnimation> HEAD_STAND_SPIN = register("head_stand_spin", HeadStandSpinAnimation::new);
   public static final AnimationId<DodgeAnimation> DODGE = register("dodge", DodgeAnimation::new);
   public static final AnimationId<ScreamAnimation> SCREAM = register("scream", ScreamAnimation::new);
   public static final AnimationId<TestAnimation> TEST = register("test", TestAnimation::new);
   public static final AnimationId<GeppoAnimation> GEPPO = register("geppo", GeppoAnimation::new);
   public static final AnimationId<BaraCarAnimation> BARA_CAR = register("bara_car", BaraCarAnimation::new);
   public static final AnimationId<CartwheelAnimation> CARTWHEEL = register("cartwheel", CartwheelAnimation::new);
   public static final AnimationId<BackflipAnimation> BACKFLIP = register("backflip", BackflipAnimation::new);

   private static <A extends Animation<?, ?>> AnimationId<A> register(String name, AnimationId.IAnimationFactory<A> factory) {
      return new AnimationId<A>(ResourceLocation.fromNamespaceAndPath("mineminenomi", name), factory);
   }

   public static void init() {
   }
}
