package xyz.pixelatedw.mineminenomi.init;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ArmorItem.Type;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.client.event.EntityRenderersEvent;
import net.minecraftforge.registries.RegistryObject;
import xyz.pixelatedw.mineminenomi.items.armors.BigRedNoseItem;
import xyz.pixelatedw.mineminenomi.items.armors.ColaBackpackItem;
import xyz.pixelatedw.mineminenomi.items.armors.IronJawItem;
import xyz.pixelatedw.mineminenomi.items.armors.Mod3DArmorItem;
import xyz.pixelatedw.mineminenomi.items.armors.ModArmorItem;
import xyz.pixelatedw.mineminenomi.items.armors.PearlArmorItem;
import xyz.pixelatedw.mineminenomi.items.armors.SenorPinkBonnetItem;
import xyz.pixelatedw.mineminenomi.items.armors.SniperGogglesItem;
import xyz.pixelatedw.mineminenomi.items.armors.WootzArmorItem;
import xyz.pixelatedw.mineminenomi.models.armors.AceHatModel;
import xyz.pixelatedw.mineminenomi.models.armors.BicorneModel;
import xyz.pixelatedw.mineminenomi.models.armors.BigNoseModel;
import xyz.pixelatedw.mineminenomi.models.armors.CabajiScarfModel;
import xyz.pixelatedw.mineminenomi.models.armors.CaptainCapeModel;
import xyz.pixelatedw.mineminenomi.models.armors.CelestialDragonBubbleModel;
import xyz.pixelatedw.mineminenomi.models.armors.ChopperHatModel;
import xyz.pixelatedw.mineminenomi.models.armors.ColaBackpackModel;
import xyz.pixelatedw.mineminenomi.models.armors.FluffyCapeModel;
import xyz.pixelatedw.mineminenomi.models.armors.HeartGlassesModel;
import xyz.pixelatedw.mineminenomi.models.armors.IronJawModel;
import xyz.pixelatedw.mineminenomi.models.armors.JangoMushroomModel;
import xyz.pixelatedw.mineminenomi.models.armors.KillerMaskModel;
import xyz.pixelatedw.mineminenomi.models.armors.LawHatModel;
import xyz.pixelatedw.mineminenomi.models.armors.MH5GasMaskModel;
import xyz.pixelatedw.mineminenomi.models.armors.MedicBagModel;
import xyz.pixelatedw.mineminenomi.models.armors.MihawkHatModel;
import xyz.pixelatedw.mineminenomi.models.armors.PearlArmorModel;
import xyz.pixelatedw.mineminenomi.models.armors.PlumeHatModel;
import xyz.pixelatedw.mineminenomi.models.armors.SaboHatModel;
import xyz.pixelatedw.mineminenomi.models.armors.SengokuHatModel;
import xyz.pixelatedw.mineminenomi.models.armors.SniperGogglesModel;
import xyz.pixelatedw.mineminenomi.models.armors.StrawHatModel;
import xyz.pixelatedw.mineminenomi.models.armors.TomoeDrumsModel;
import xyz.pixelatedw.mineminenomi.models.armors.TricorneModel;
import xyz.pixelatedw.mineminenomi.models.armors.WideBrimHatModel;
import xyz.pixelatedw.mineminenomi.models.armors.WizardHatModel;
import xyz.pixelatedw.mineminenomi.models.armors.WootzArmorModel;

public class ModArmors {
   public static final RegistryObject<Item> PIRATE_CHEST = ModRegistry.<Item>registerItem("Pirate Shirt", () -> new ModArmorItem("pirate", Type.CHESTPLATE));
   public static final RegistryObject<Item> PIRATE_LEGS = ModRegistry.<Item>registerItem("Pirate Pants", () -> new ModArmorItem("pirate", Type.LEGGINGS));
   public static final RegistryObject<Item> PIRATE_FEET = ModRegistry.<Item>registerItem("Pirate Boots", () -> new ModArmorItem("pirate", Type.BOOTS));
   public static final RegistryObject<Item> MARINE_HEAD = ModRegistry.<Item>registerItem("Marine Hat", () -> new ModArmorItem("marine", Type.HELMET));
   public static final RegistryObject<Item> MARINE_CHEST = ModRegistry.<Item>registerItem("Marine Shirt", () -> new ModArmorItem("marine", Type.CHESTPLATE));
   public static final RegistryObject<Item> MARINE_LEGS = ModRegistry.<Item>registerItem("Marine Pants", () -> new ModArmorItem("marine", Type.LEGGINGS));
   public static final RegistryObject<Item> MARINE_FEET = ModRegistry.<Item>registerItem("Marine Boots", () -> new ModArmorItem("marine", Type.BOOTS));
   public static final RegistryObject<Mod3DArmorItem> STRAW_HAT = ModRegistry.<Mod3DArmorItem>registerItem("Straw Hat", () -> (Mod3DArmorItem)(new Mod3DArmorItem(ModMaterials.STRAW_HAT_MATERIAL, "straw_hat", Type.HELMET)).setDyeable().setDefaultColor(16722731));
   public static final RegistryObject<Item> LUFFY_SHIRT = ModRegistry.<Item>registerItem("Luffy's Shirt", () -> new ModArmorItem("luffy", Type.CHESTPLATE));
   public static final RegistryObject<Item> LUFFY_PANTS = ModRegistry.<Item>registerItem("Luffy's Pants", () -> new ModArmorItem("luffy", Type.LEGGINGS));
   public static final RegistryObject<Item> LUFFY_SANDALS = ModRegistry.<Item>registerItem("Luffy's Sandals", () -> new ModArmorItem(ModMaterials.SANDALS_MATERIAL, "luffy", Type.BOOTS));
   public static final RegistryObject<Item> ZORO_CHEST = ModRegistry.<Item>registerItem("Zoro's Shirt", () -> new ModArmorItem("zoro", Type.CHESTPLATE));
   public static final RegistryObject<Item> ZORO_LEGS = ModRegistry.<Item>registerItem("Zoro's Pants", () -> new ModArmorItem("zoro", Type.LEGGINGS));
   public static final RegistryObject<Item> ZORO_FEET = ModRegistry.<Item>registerItem("Zoro's Boots", () -> new ModArmorItem("zoro", Type.BOOTS));
   public static final RegistryObject<Item> FRANKY_GLASSES = ModRegistry.<Item>registerItem("Franky's Glasses", () -> new ModArmorItem("franky", Type.HELMET));
   public static final RegistryObject<Item> FRANKY_CHEST = ModRegistry.<Item>registerItem("Franky's Shirt", () -> new ModArmorItem("franky", Type.CHESTPLATE));
   public static final RegistryObject<Item> SANJI_CHEST = ModRegistry.<Item>registerItem("Sanji's Shirt", () -> new ModArmorItem("sanji", Type.CHESTPLATE));
   public static final RegistryObject<Item> SANJI_LEGS = ModRegistry.<Item>registerItem("Sanji's Pants", () -> new ModArmorItem("sanji", Type.LEGGINGS));
   public static final RegistryObject<Item> SANJI_FEET = ModRegistry.<Item>registerItem("Sanji's Shoes", () -> new ModArmorItem("sanji", Type.BOOTS));
   public static final RegistryObject<Item> SENOR_PINK_HEAD = ModRegistry.<Item>registerItem("Senior Pink's Bonnet", SenorPinkBonnetItem::new);
   public static final RegistryObject<Item> SENOR_PINK_CHEST = ModRegistry.<Item>registerItem("Senior Pink's Shirt", () -> new ModArmorItem("senorpink", Type.CHESTPLATE));
   public static final RegistryObject<Item> USOPP_CHEST = ModRegistry.<Item>registerItem("Usopp's Overall", () -> new ModArmorItem("usopp", Type.CHESTPLATE));
   public static final RegistryObject<Item> USOPP_LEGS = ModRegistry.<Item>registerItem("Usopp's Pants", () -> new ModArmorItem("usopp", Type.LEGGINGS));
   public static final RegistryObject<Item> USOPP_FEET = ModRegistry.<Item>registerItem("Usopp's Boots", () -> new ModArmorItem("usopp", Type.BOOTS));
   public static final RegistryObject<ModArmorItem> VICE_ADMIRAL_CHEST = ModRegistry.<ModArmorItem>registerItem("Vice Admiral Jacket", () -> (new ModArmorItem("vice_admiral", Type.CHESTPLATE)).setDyeable());
   public static final RegistryObject<ModArmorItem> VICE_ADMIRAL_LEGS = ModRegistry.<ModArmorItem>registerItem("Vice Admiral Pants", () -> (new ModArmorItem("vice_admiral", Type.LEGGINGS)).setDyeable());
   public static final RegistryObject<ModArmorItem> VICE_ADMIRAL_FEET = ModRegistry.<ModArmorItem>registerItem("Vice Admiral Boots", () -> (new ModArmorItem("vice_admiral", Type.BOOTS)).setDyeable());
   public static final RegistryObject<Item> CP9_CHEST = ModRegistry.<Item>registerItem("CP9 Jacket", () -> new ModArmorItem("cp9", Type.CHESTPLATE));
   public static final RegistryObject<Item> CP9_LEGS = ModRegistry.<Item>registerItem("CP9 Pants", () -> new ModArmorItem("cp9", Type.LEGGINGS));
   public static final RegistryObject<Item> CP9_FEET = ModRegistry.<Item>registerItem("CP9 Boots", () -> new ModArmorItem("cp9", Type.BOOTS));
   public static final RegistryObject<Item> KUMA_CHEST = ModRegistry.<Item>registerItem("Kuma Shirt", () -> new ModArmorItem("kuma", Type.CHESTPLATE));
   public static final RegistryObject<Item> KUMA_LEGS = ModRegistry.<Item>registerItem("Kuma Pants", () -> new ModArmorItem("kuma", Type.LEGGINGS));
   public static final RegistryObject<Item> KUMA_FEET = ModRegistry.<Item>registerItem("Kuma Boots", () -> new ModArmorItem("kuma", Type.BOOTS));
   public static final RegistryObject<Item> SMOKER_CHEST = ModRegistry.<Item>registerItem("Smoker Jacket", () -> new ModArmorItem("smoker", Type.CHESTPLATE));
   public static final RegistryObject<Item> SMOKER_LEGS = ModRegistry.<Item>registerItem("Smoker Pants", () -> new ModArmorItem("smoker", Type.LEGGINGS));
   public static final RegistryObject<Item> SMOKER_FEET = ModRegistry.<Item>registerItem("Smoker Boots", () -> new ModArmorItem("smoker", Type.BOOTS));
   public static final RegistryObject<Item> KURO_GLASSES = ModRegistry.<Item>registerItem("Kuro's Glasses", () -> new ModArmorItem("kuro", Type.HELMET));
   public static final RegistryObject<Item> KURO_CHEST = ModRegistry.<Item>registerItem("Kuro's Suit", () -> new ModArmorItem("kuro", Type.CHESTPLATE));
   public static final RegistryObject<Item> KURO_LEGS = ModRegistry.<Item>registerItem("Kuro's Pants", () -> new ModArmorItem("kuro", Type.LEGGINGS));
   public static final RegistryObject<Item> KURO_FEET = ModRegistry.<Item>registerItem("Kuro's Shoes", () -> new ModArmorItem("kuro", Type.BOOTS));
   public static final RegistryObject<Item> PEARL_HAT = ModRegistry.<Item>registerItem("Pearl Head Armor", () -> new PearlArmorItem(Type.HELMET));
   public static final RegistryObject<Item> PEARL_ARMOR = ModRegistry.<Item>registerItem("Pearl Body Armor", () -> new PearlArmorItem(Type.CHESTPLATE));
   public static final RegistryObject<Item> PEARL_LEGS = ModRegistry.<Item>registerItem("Pearl Legs Armor", () -> new PearlArmorItem(Type.LEGGINGS));
   public static final RegistryObject<Item> ARLONG_HAT = ModRegistry.<Item>registerItem("Arlong's Hat", () -> new ModArmorItem("arlong", Type.HELMET));
   public static final RegistryObject<Item> ARLONG_CHEST = ModRegistry.<Item>registerItem("Arlong's Shirt", () -> new ModArmorItem("arlong", Type.CHESTPLATE));
   public static final RegistryObject<Item> ARLONG_LEGS = ModRegistry.<Item>registerItem("Arlong's Pants", () -> new ModArmorItem("arlong", Type.LEGGINGS));
   public static final RegistryObject<Item> ARLONG_FEET = ModRegistry.<Item>registerItem("Arlong's Shoes", () -> new ModArmorItem("arlong", Type.BOOTS));
   public static final RegistryObject<Item> CHEW_CHEST = ModRegistry.<Item>registerItem("Chew's Shirt", () -> new ModArmorItem("chew", Type.CHESTPLATE));
   public static final RegistryObject<Item> CHEW_LEGS = ModRegistry.<Item>registerItem("Chew's Pants", () -> new ModArmorItem("chew", Type.LEGGINGS));
   public static final RegistryObject<Item> CHEW_FEET = ModRegistry.<Item>registerItem("Chew's Shoes", () -> new ModArmorItem("chew", Type.BOOTS));
   public static final RegistryObject<Item> KUROOBI_CHEST = ModRegistry.<Item>registerItem("Kuroobi's Ki", () -> new ModArmorItem("kuroobi", Type.CHESTPLATE));
   public static final RegistryObject<Item> KUROOBI_LEGS = ModRegistry.<Item>registerItem("Kuroobi's Pants", () -> new ModArmorItem("kuroobi", Type.LEGGINGS));
   public static final RegistryObject<Item> KUROOBI_FEET = ModRegistry.<Item>registerItem("Kuroobi's Shoes", () -> new ModArmorItem("kuroobi", Type.BOOTS));
   public static final RegistryObject<Item> CROCODILE_CHEST = ModRegistry.<Item>registerItem("Crocodile's Suit", () -> new ModArmorItem("crocodile", Type.CHESTPLATE));
   public static final RegistryObject<Item> CROCODILE_LEGS = ModRegistry.<Item>registerItem("Crocodile's Pants", () -> new ModArmorItem("crocodile", Type.LEGGINGS));
   public static final RegistryObject<Item> CROCODILE_FEET = ModRegistry.<Item>registerItem("Crocodile's Shoes", () -> new ModArmorItem("crocodile", Type.BOOTS));
   public static final RegistryObject<Item> MR1_CHEST = ModRegistry.<Item>registerItem("Mr 1's Shirt", () -> new ModArmorItem("mr1", Type.CHESTPLATE));
   public static final RegistryObject<Item> MR1_LEGS = ModRegistry.<Item>registerItem("Mr 1's Pants", () -> new ModArmorItem("mr1", Type.LEGGINGS));
   public static final RegistryObject<Item> MR1_FEET = ModRegistry.<Item>registerItem("Mr 1's Shoes", () -> new ModArmorItem("mr1", Type.BOOTS));
   public static final RegistryObject<Item> MR3_GLASSES = ModRegistry.<Item>registerItem("Mr 3's Glasses", () -> new ModArmorItem("mr3", Type.HELMET));
   public static final RegistryObject<Item> MR3_CHEST = ModRegistry.<Item>registerItem("Mr 3's Shirt", () -> new ModArmorItem("mr3", Type.CHESTPLATE));
   public static final RegistryObject<Item> MR3_LEGS = ModRegistry.<Item>registerItem("Mr 3's Pants", () -> new ModArmorItem("mr3", Type.LEGGINGS));
   public static final RegistryObject<Item> MR3_FEET = ModRegistry.<Item>registerItem("Mr 3's Shoes", () -> new ModArmorItem("mr3", Type.BOOTS));
   public static final RegistryObject<Item> MR5_GLASSES = ModRegistry.<Item>registerItem("Mr 5's Glasses", () -> new ModArmorItem("mr5", Type.HELMET));
   public static final RegistryObject<Item> MR5_CHEST = ModRegistry.<Item>registerItem("Mr 5's Shirt", () -> new ModArmorItem("mr5", Type.CHESTPLATE));
   public static final RegistryObject<Item> MR5_LEGS = ModRegistry.<Item>registerItem("Mr 5's Pants", () -> new ModArmorItem("mr5", Type.LEGGINGS));
   public static final RegistryObject<Item> MR5_FEET = ModRegistry.<Item>registerItem("Mr 5's Shoes", () -> new ModArmorItem("mr5", Type.BOOTS));
   public static final RegistryObject<Item> BANDANA = ModRegistry.<Item>registerItem("Bandana", () -> (new ModArmorItem(ModMaterials.SIMPLE_WOOL_MATERIAL, "bandana", Type.HELMET)).setDyeable().setDefaultColor(0));
   public static final RegistryObject<Item> SNIPER_GOGGLES = ModRegistry.<Item>registerItem("Sniper Goggles", SniperGogglesItem::new);
   public static final RegistryObject<Item> MH5_GAS_MASK = ModRegistry.<Item>registerItem("MH5 Gas Mask", () -> new Mod3DArmorItem(ModMaterials.GAS_MASK_MATERIAL, "mh5_gas_mask", Type.HELMET));
   public static final RegistryObject<Item> CHOPPER_HAT = ModRegistry.<Item>registerItem("Chopper's Hat", () -> new Mod3DArmorItem(ModMaterials.SIMPLE_WOOL_MATERIAL, "chopper_hat", Type.HELMET));
   public static final RegistryObject<Item> ACE_HAT = ModRegistry.<Item>registerItem("Ace's Hat", () -> new Mod3DArmorItem(ModMaterials.SIMPLE_LEATHER_MATERIAL, "ace_hat", Type.HELMET));
   public static final RegistryObject<Item> KIZARU_GLASSES = ModRegistry.<Item>registerItem("Kizaru's Glasses", () -> new ModArmorItem(ModMaterials.GLASSES_MATERIAL, "kizaru_glasses", Type.HELMET));
   public static final RegistryObject<Item> KILLER_MASK = ModRegistry.<Item>registerItem("Killer's Mask", () -> new Mod3DArmorItem(ModMaterials.KILLER_MASK_MATERIAL, "killer_mask", Type.HELMET));
   public static final RegistryObject<Item> LAW_HAT = ModRegistry.<Item>registerItem("Law's Hat", () -> new Mod3DArmorItem(ModMaterials.SIMPLE_WOOL_MATERIAL, "law_hat", Type.HELMET));
   public static final RegistryObject<Item> TRICORNE = ModRegistry.<Item>registerItem("Tricorne", () -> (new Mod3DArmorItem(ModMaterials.SIMPLE_WOOL_MATERIAL, "tricorne", Type.HELMET)).setDyeable().setDefaultColor(8932372));
   public static final RegistryObject<Item> SABO_HAT = ModRegistry.<Item>registerItem("Sabo's Hat", () -> new Mod3DArmorItem(ModMaterials.SIMPLE_WOOL_MATERIAL, "sabo_hat", Type.HELMET));
   public static final RegistryObject<Item> DOFFY_GLASSES = ModRegistry.<Item>registerItem("Doflamingo's Glasses", () -> (new ModArmorItem(ModMaterials.GLASSES_MATERIAL, "doffy_glasses", Type.HELMET)).setDyeable().setDefaultColor(16420857));
   public static final RegistryObject<Item> MIHAWK_HAT = ModRegistry.<Item>registerItem("Mihawk's Hat", () -> (new Mod3DArmorItem(ModMaterials.SIMPLE_WOOL_MATERIAL, "mihawk_hat", Type.HELMET)).setDyeable(2).setDefaultLayerColor(0, 11202757).setDefaultLayerColor(1, 1973533));
   public static final RegistryObject<Item> FLEET_ADMIRAL_HAT = ModRegistry.<Item>registerItem("Fleet Admiral's Hat", () -> new Mod3DArmorItem(ModMaterials.SIMPLE_WOOL_MATERIAL, "fleet_admiral_hat", Type.HELMET));
   public static final RegistryObject<Item> CELESTIAL_DRAGON_BUBBLE = ModRegistry.<Item>registerItem("Celestial Dragon Bubble", () -> (new Mod3DArmorItem(ModMaterials.BUBBLE_MATERIAL, "celestial_dragon_bubble", Type.HELMET)).setDyeable());
   public static final RegistryObject<Item> PLUME_HAT = ModRegistry.<Item>registerItem("Plume Hat", () -> (new Mod3DArmorItem(ModMaterials.SIMPLE_WOOL_MATERIAL, "plume_hat", Type.HELMET)).setDyeable(2).setDefaultLayerColor(0, 12400461).setDefaultLayerColor(1, 15791090));
   public static final RegistryObject<Item> BICORNE = ModRegistry.<Item>registerItem("Bicorne", () -> (new Mod3DArmorItem(ModMaterials.SIMPLE_LEATHER_MATERIAL, "bicorne", Type.HELMET)).setDyeable(2).setDefaultLayerColor(0, 13459968));
   public static final RegistryObject<Item> WIDE_BRIM_HAT = ModRegistry.<Item>registerItem("Wide Brim Hat", () -> (new Mod3DArmorItem(ModMaterials.SIMPLE_WOOL_MATERIAL, "wide_brim_hat", Type.HELMET)).setDyeable().setDefaultColor(1581133));
   public static final RegistryObject<Item> HEART_GLASSES = ModRegistry.<Item>registerItem("Heart Glasses", () -> new Mod3DArmorItem(ModMaterials.GLASSES_MATERIAL, "heart_glasses", Type.HELMET));
   public static final RegistryObject<Item> CABAJI_SCARF = ModRegistry.<Item>registerItem("Cabaji's Scarf", () -> new Mod3DArmorItem(ModMaterials.SCARF_MATERIAL, "cabaji_scarf", Type.HELMET));
   public static final RegistryObject<Item> BIG_RED_NOSE = ModRegistry.<Item>registerItem("Big Red Nose", BigRedNoseItem::new);
   public static final RegistryObject<Item> IRON_JAW = ModRegistry.<Item>registerItem("Iron Jaw", IronJawItem::new);
   public static final RegistryObject<Item> WIZARD_HAT = ModRegistry.<Item>registerItem("Wizard Hat", () -> (new Mod3DArmorItem(ModMaterials.SIMPLE_WOOL_MATERIAL, "wizard_hat", Type.HELMET)).setDyeable().setDefaultColor(31700));
   public static final RegistryObject<Item> COLA_BACKPACK = ModRegistry.<Item>registerItem("Cola Backpack", ColaBackpackItem::new);
   public static final RegistryObject<Item> MEDIC_BAG = ModRegistry.<Item>registerItem("Medic Bag", () -> new Mod3DArmorItem(ModMaterials.MEDIC_BAG_MATERIAL, "medic_bag", Type.CHESTPLATE, (new Item.Properties()).m_41503_(2000)));
   public static final RegistryObject<Item> TOMOE_DRUMS = ModRegistry.<Item>registerItem("Tomoe Drums", () -> new Mod3DArmorItem(ModMaterials.TOMOE_DRUMS_MATERIAL, "tomoe_drums", Type.CHESTPLATE, new Item.Properties()));
   public static final RegistryObject<Item> WOOTZ_STEEL_ARMOR = ModRegistry.<Item>registerItem("Wootz Steel Armor", WootzArmorItem::new);
   public static final RegistryObject<Item> MARINE_CAPTAIN_CAPE = ModRegistry.<Item>registerItem("Marine Captain Cape", () -> (new Mod3DArmorItem(ModMaterials.CAPTAIN_CAPE_MATERIAL, "marine_captain_cape", Type.CHESTPLATE)).setDyeable().setDefaultColor(6395589));
   public static final RegistryObject<Item> PIRATE_CAPTAIN_CAPE = ModRegistry.<Item>registerItem("Pirate Captain Cape", () -> (new Mod3DArmorItem(ModMaterials.CAPTAIN_CAPE_MATERIAL, "pirate_captain_cape", Type.CHESTPLATE)).setDyeable().setDefaultColor(2949120));
   public static final RegistryObject<Item> FLUFFY_CAPE = ModRegistry.<Item>registerItem("Fluffy Cape", () -> (new Mod3DArmorItem(ModMaterials.CAPTAIN_CAPE_MATERIAL, "fluffy_cape", Type.CHESTPLATE)).setDyeable().setDefaultColor(16754169));

   public static void init() {
   }

   @OnlyIn(Dist.CLIENT)
   public static class Client {
      public static final Map<Item, HumanoidModel<LivingEntity>> ARMOR_MODELS = new HashMap();

      public static void registerLayers(EntityRenderersEvent.RegisterLayerDefinitions event) {
         event.registerLayerDefinition(PearlArmorModel.HAT_LAYER_LOCATION, () -> PearlArmorModel.createBodyLayer(Type.HELMET));
         event.registerLayerDefinition(PearlArmorModel.ARMOR_LAYER_LOCATION, () -> PearlArmorModel.createBodyLayer(Type.CHESTPLATE));
         event.registerLayerDefinition(PearlArmorModel.LEGS_LAYER_LOCATION, () -> PearlArmorModel.createBodyLayer(Type.LEGGINGS));
         event.registerLayerDefinition(StrawHatModel.LAYER_LOCATION, StrawHatModel::createBodyLayer);
         event.registerLayerDefinition(KillerMaskModel.LAYER_LOCATION, KillerMaskModel::createBodyLayer);
         event.registerLayerDefinition(BicorneModel.LAYER_LOCATION, BicorneModel::createBodyLayer);
         event.registerLayerDefinition(SniperGogglesModel.LAYER_LOCATION, SniperGogglesModel::createBodyLayer);
         event.registerLayerDefinition(MH5GasMaskModel.LAYER_LOCATION, MH5GasMaskModel::createBodyLayer);
         event.registerLayerDefinition(ChopperHatModel.LAYER_LOCATION, ChopperHatModel::createBodyLayer);
         event.registerLayerDefinition(AceHatModel.LAYER_LOCATION, AceHatModel::createBodyLayer);
         event.registerLayerDefinition(LawHatModel.LAYER_LOCATION, LawHatModel::createBodyLayer);
         event.registerLayerDefinition(CabajiScarfModel.LAYER_LOCATION, CabajiScarfModel::createBodyLayer);
         event.registerLayerDefinition(BigNoseModel.LAYER_LOCATION, BigNoseModel::createBodyLayer);
         event.registerLayerDefinition(SaboHatModel.LAYER_LOCATION, SaboHatModel::createBodyLayer);
         event.registerLayerDefinition(MihawkHatModel.LAYER_LOCATION, MihawkHatModel::createBodyLayer);
         event.registerLayerDefinition(SengokuHatModel.LAYER_LOCATION, SengokuHatModel::createBodyLayer);
         event.registerLayerDefinition(CelestialDragonBubbleModel.LAYER_LOCATION, CelestialDragonBubbleModel::createBodyLayer);
         event.registerLayerDefinition(PlumeHatModel.LAYER_LOCATION, PlumeHatModel::createBodyLayer);
         event.registerLayerDefinition(WideBrimHatModel.LAYER_LOCATION, WideBrimHatModel::createBodyLayer);
         event.registerLayerDefinition(HeartGlassesModel.LAYER_LOCATION, HeartGlassesModel::createBodyLayer);
         event.registerLayerDefinition(TricorneModel.LAYER_LOCATION, TricorneModel::createBodyLayer);
         event.registerLayerDefinition(IronJawModel.LAYER_LOCATION, IronJawModel::createBodyLayer);
         event.registerLayerDefinition(WizardHatModel.LAYER_LOCATION, WizardHatModel::createBodyLayer);
         event.registerLayerDefinition(ColaBackpackModel.LAYER_LOCATION, ColaBackpackModel::createBodyLayer);
         event.registerLayerDefinition(MedicBagModel.LAYER_LOCATION, MedicBagModel::createBodyLayer);
         event.registerLayerDefinition(TomoeDrumsModel.LAYER_LOCATION, TomoeDrumsModel::createBodyLayer);
         event.registerLayerDefinition(WootzArmorModel.LAYER_LOCATION, WootzArmorModel::createBodyLayer);
         event.registerLayerDefinition(CaptainCapeModel.LAYER_LOCATION, CaptainCapeModel::createBodyLayer);
         event.registerLayerDefinition(FluffyCapeModel.LAYER_LOCATION, FluffyCapeModel::createBodyLayer);
         event.registerLayerDefinition(JangoMushroomModel.LAYER_LOCATION, JangoMushroomModel::createBodyLayer);
      }

      public static void addLayers(EntityRenderersEvent.AddLayers event, EntityRendererProvider.Context ctx) {
         CaptainCapeModel<LivingEntity> captainCape = new CaptainCapeModel<LivingEntity>(ctx.m_174023_(CaptainCapeModel.LAYER_LOCATION));
         ARMOR_MODELS.put((Item)ModArmors.STRAW_HAT.get(), new StrawHatModel(ctx.m_174023_(StrawHatModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.PEARL_HAT.get(), new PearlArmorModel(ctx.m_174023_(PearlArmorModel.HAT_LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.PEARL_ARMOR.get(), new PearlArmorModel(ctx.m_174023_(PearlArmorModel.ARMOR_LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.PEARL_LEGS.get(), new PearlArmorModel(ctx.m_174023_(PearlArmorModel.LEGS_LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.KILLER_MASK.get(), new KillerMaskModel(ctx.m_174023_(KillerMaskModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.BICORNE.get(), new BicorneModel(ctx.m_174023_(BicorneModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.SNIPER_GOGGLES.get(), new SniperGogglesModel(ctx.m_174023_(SniperGogglesModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.MH5_GAS_MASK.get(), new MH5GasMaskModel(ctx.m_174023_(MH5GasMaskModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.CHOPPER_HAT.get(), new ChopperHatModel(ctx.m_174023_(ChopperHatModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.ACE_HAT.get(), new AceHatModel(ctx.m_174023_(AceHatModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.LAW_HAT.get(), new LawHatModel(ctx.m_174023_(LawHatModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.CABAJI_SCARF.get(), new CabajiScarfModel(ctx.m_174023_(CabajiScarfModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.BIG_RED_NOSE.get(), new BigNoseModel(ctx.m_174023_(BigNoseModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.SABO_HAT.get(), new SaboHatModel(ctx.m_174023_(SaboHatModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.MIHAWK_HAT.get(), new MihawkHatModel(ctx.m_174023_(MihawkHatModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.FLEET_ADMIRAL_HAT.get(), new SengokuHatModel(ctx.m_174023_(SengokuHatModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.CELESTIAL_DRAGON_BUBBLE.get(), new CelestialDragonBubbleModel(ctx.m_174023_(CelestialDragonBubbleModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.PLUME_HAT.get(), new PlumeHatModel(ctx.m_174023_(PlumeHatModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.WIDE_BRIM_HAT.get(), new WideBrimHatModel(ctx.m_174023_(WideBrimHatModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.HEART_GLASSES.get(), new HeartGlassesModel(ctx.m_174023_(HeartGlassesModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.TRICORNE.get(), new TricorneModel(ctx.m_174023_(TricorneModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.IRON_JAW.get(), new IronJawModel(ctx.m_174023_(IronJawModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.WIZARD_HAT.get(), new WizardHatModel(ctx.m_174023_(WizardHatModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.COLA_BACKPACK.get(), new ColaBackpackModel(ctx.m_174023_(ColaBackpackModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.MEDIC_BAG.get(), new MedicBagModel(ctx.m_174023_(MedicBagModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.TOMOE_DRUMS.get(), new TomoeDrumsModel(ctx.m_174023_(TomoeDrumsModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.WOOTZ_STEEL_ARMOR.get(), new WootzArmorModel(ctx.m_174023_(WootzArmorModel.LAYER_LOCATION)));
         ARMOR_MODELS.put((Item)ModArmors.MARINE_CAPTAIN_CAPE.get(), captainCape);
         ARMOR_MODELS.put((Item)ModArmors.PIRATE_CAPTAIN_CAPE.get(), captainCape);
         ARMOR_MODELS.put((Item)ModArmors.FLUFFY_CAPE.get(), new FluffyCapeModel(ctx.m_174023_(FluffyCapeModel.LAYER_LOCATION)));
      }
   }
}
