package xyz.pixelatedw.mineminenomi.init;

import java.util.function.Function;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.level.block.AirBlock;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockBehaviour.Properties;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;
import net.minecraft.world.level.material.MapColor;
import net.minecraftforge.registries.RegistryObject;
import xyz.pixelatedw.mineminenomi.blocks.BarrierBlock;
import xyz.pixelatedw.mineminenomi.blocks.CandyBlock;
import xyz.pixelatedw.mineminenomi.blocks.CustomSpawnerBlock;
import xyz.pixelatedw.mineminenomi.blocks.DarknessBlock;
import xyz.pixelatedw.mineminenomi.blocks.DemonPoisonBlock;
import xyz.pixelatedw.mineminenomi.blocks.DenDenMushiBlock;
import xyz.pixelatedw.mineminenomi.blocks.DesignBarrelBlock;
import xyz.pixelatedw.mineminenomi.blocks.DialBlock;
import xyz.pixelatedw.mineminenomi.blocks.FlagBlock;
import xyz.pixelatedw.mineminenomi.blocks.HardenedSnowBlock;
import xyz.pixelatedw.mineminenomi.blocks.KairosekiBarsBlock;
import xyz.pixelatedw.mineminenomi.blocks.MangroveLeavesBlock;
import xyz.pixelatedw.mineminenomi.blocks.MangroveLogBlock;
import xyz.pixelatedw.mineminenomi.blocks.MangrovePlanksBlock;
import xyz.pixelatedw.mineminenomi.blocks.MangroveWoodBlock;
import xyz.pixelatedw.mineminenomi.blocks.MucusBlock;
import xyz.pixelatedw.mineminenomi.blocks.OilSpillBlock;
import xyz.pixelatedw.mineminenomi.blocks.OpeBlock;
import xyz.pixelatedw.mineminenomi.blocks.OriBarsBlock;
import xyz.pixelatedw.mineminenomi.blocks.PoisonBlock;
import xyz.pixelatedw.mineminenomi.blocks.PoneglyphBlock;
import xyz.pixelatedw.mineminenomi.blocks.SkyBlockBlock;
import xyz.pixelatedw.mineminenomi.blocks.SpongeCakeBlock;
import xyz.pixelatedw.mineminenomi.blocks.StringWallBlock;
import xyz.pixelatedw.mineminenomi.blocks.StrippedMangroveLog;
import xyz.pixelatedw.mineminenomi.blocks.StrippedMangroveWood;
import xyz.pixelatedw.mineminenomi.blocks.SunaSandBlock;
import xyz.pixelatedw.mineminenomi.blocks.TangerineCropsBlock;
import xyz.pixelatedw.mineminenomi.blocks.WantedPosterBlock;
import xyz.pixelatedw.mineminenomi.blocks.WaxBlock;
import xyz.pixelatedw.mineminenomi.items.FlagItem;
import xyz.pixelatedw.mineminenomi.items.WantedPosterItem;
import xyz.pixelatedw.mineminenomi.items.dials.AxeDialItem;
import xyz.pixelatedw.mineminenomi.items.dials.BreathDialItem;
import xyz.pixelatedw.mineminenomi.items.dials.EisenDialItem;
import xyz.pixelatedw.mineminenomi.items.dials.FlameDialItem;
import xyz.pixelatedw.mineminenomi.items.dials.FlashDialItem;
import xyz.pixelatedw.mineminenomi.items.dials.ImpactDialItem;
import xyz.pixelatedw.mineminenomi.items.dials.MilkyDialItem;
import xyz.pixelatedw.mineminenomi.items.dials.RejectDialItem;

public class ModBlocks {
   public static final RegistryObject<Block> OPE = ModRegistry.<Block>registerBlock("Ope", OpeBlock::new);
   public static final RegistryObject<Block> SUNA_SAND = ModRegistry.<Block>registerBlock("Suna Sand", SunaSandBlock::new);
   public static final RegistryObject<Block> WAX = ModRegistry.<Block>registerBlock("Wax Block", WaxBlock::new);
   public static final RegistryObject<Block> CANDY = ModRegistry.<Block>registerBlock("Candy Block", CandyBlock::new);
   public static final RegistryObject<Block> POISON = ModRegistry.<Block>registerBlock("Poison", PoisonBlock::new);
   public static final RegistryObject<Block> DEMON_POISON = ModRegistry.<Block>registerBlock("Demon Poison", DemonPoisonBlock::new);
   public static final RegistryObject<Block> STRING_WALL = ModRegistry.<Block>registerBlock("String Wall", StringWallBlock::new);
   public static final RegistryObject<Block> BARRIER = ModRegistry.<Block>registerBlock("Barrier", BarrierBlock::new);
   public static final RegistryObject<Block> DARKNESS = ModRegistry.<Block>registerBlock("Darkness", DarknessBlock::new);
   public static final RegistryObject<Block> ORI_BARS = ModRegistry.<Block>registerBlock("Ori Bars", OriBarsBlock::new);
   public static final RegistryObject<Block> MUCUS = ModRegistry.<Block>registerBlock("Mucus", MucusBlock::new);
   public static final RegistryObject<Block> SPONGE_CAKE = ModRegistry.<Block>registerBlock("Sponge Cake", SpongeCakeBlock::new);
   public static final RegistryObject<Block> HARDENED_SNOW = ModRegistry.<Block>registerBlock("Hardened Snow", HardenedSnowBlock::new);
   public static final RegistryObject<Block> KAIROSEKI = ModRegistry.<Block>registerBlock("Kairoseki Block", () -> new Block(Properties.m_284310_().m_284180_(MapColor.f_283947_).m_60913_(50.0F, 600.0F).m_60999_()));
   public static final RegistryObject<Block> KAIROSEKI_ORE = ModRegistry.<Block>registerBlock("Kairoseki Ore", () -> new DropExperienceBlock(Properties.m_284310_().m_284180_(MapColor.f_283947_).m_280658_(NoteBlockInstrument.BASEDRUM).m_60999_().m_60913_(5.0F, 3.0F), UniformInt.m_146622_(3, 5)));
   public static final RegistryObject<Block> DEEPSLATE_KAIROSEKI_ORE = ModRegistry.<Block>registerBlock("Deepslate Kairoseki Ore", () -> new DropExperienceBlock(Properties.m_60926_((BlockBehaviour)KAIROSEKI_ORE.get()).m_284180_(MapColor.f_283875_).m_60913_(6.0F, 3.0F).m_60918_(SoundType.f_154677_), UniformInt.m_146622_(3, 5)));
   public static final RegistryObject<Block> KAIROSEKI_BARS = ModRegistry.<Block>registerBlock("Kairoseki Bars", KairosekiBarsBlock::new);
   public static final RegistryObject<Block> SKY_BLOCK = ModRegistry.<Block>registerBlock("Sky Block", SkyBlockBlock::new);
   public static final RegistryObject<Block> WANTED_POSTER = ModRegistry.registerBlock("Wanted Poster", WantedPosterBlock::new, WantedPosterItem::new);
   public static final RegistryObject<Block> CUSTOM_SPAWNER = ModRegistry.<Block>registerBlock("Custom Spawner", CustomSpawnerBlock::new);
   public static final RegistryObject<Block> DEN_DEN_MUSHI = ModRegistry.<Block>registerBlock("Den Den Mushi", DenDenMushiBlock::new);
   public static final RegistryObject<Block> OIL_SPILL = ModRegistry.<Block>registerBlock("Oil Spill", OilSpillBlock::new);
   public static final RegistryObject<Block> DESIGN_BARREL = ModRegistry.<Block>registerBlock("Design Barrel", DesignBarrelBlock::new);
   public static final RegistryObject<Block> STRUCTURE_AIR = ModRegistry.<Block>registerBlock("Structure Air", () -> new AirBlock(Properties.m_284310_().m_280170_().m_60910_().m_222994_().m_60996_()));
   public static final RegistryObject<Block> CHALLENGE_AIR = ModRegistry.<Block>registerBlock("Challenge Air", () -> new AirBlock(Properties.m_284310_().m_280170_().m_60910_().m_222994_().m_60953_((state) -> 15).m_60996_()));
   public static final RegistryObject<Block> FLAG = ModRegistry.registerBlock("Flag", FlagBlock::new, FlagItem::new);
   public static final RegistryObject<Block> AXE_DIAL = ModRegistry.registerBlock("Axe Dial", DialBlock::new, AxeDialItem::new);
   public static final RegistryObject<Block> IMPACT_DIAL = ModRegistry.registerBlock("Impact Dial", DialBlock::new, ImpactDialItem::new);
   public static final RegistryObject<Block> FLASH_DIAL = ModRegistry.registerBlock("Flash Dial", () -> new DialBlock(Properties.m_284310_().m_60978_(0.2F).m_60953_((state) -> 10)), (Function)(FlashDialItem::new));
   public static final RegistryObject<Block> BREATH_DIAL = ModRegistry.registerBlock("Breath Dial", DialBlock::new, BreathDialItem::new);
   public static final RegistryObject<Block> EISEN_DIAL = ModRegistry.registerBlock("Eisen Dial", DialBlock::new, EisenDialItem::new);
   public static final RegistryObject<Block> MILKY_DIAL = ModRegistry.registerBlock("Milky Dial", DialBlock::new, MilkyDialItem::new);
   public static final RegistryObject<Block> FLAME_DIAL = ModRegistry.registerBlock("Flame Dial", DialBlock::new, FlameDialItem::new);
   public static final RegistryObject<Block> REJECT_DIAL = ModRegistry.registerBlock("Reject Dial", DialBlock::new, RejectDialItem::new);
   public static final RegistryObject<Block> MANGROVE_LOG = ModRegistry.<Block>registerBlock("Mangrove Log", MangroveLogBlock::new);
   public static final RegistryObject<Block> MANGROVE_WOOD = ModRegistry.<Block>registerBlock("Mangrove Wood", MangroveWoodBlock::new);
   public static final RegistryObject<Block> STRIPPED_MANGROVE_LOG = ModRegistry.<Block>registerBlock("Stripped Mangrove Log", StrippedMangroveLog::new);
   public static final RegistryObject<Block> STRIPPED_MANGROVE_WOOD = ModRegistry.<Block>registerBlock("Stripped Mangrove Wood", StrippedMangroveWood::new);
   public static final RegistryObject<Block> MANGROVE_LEAVES = ModRegistry.<Block>registerBlock("Mangrove Leaves", MangroveLeavesBlock::new);
   public static final RegistryObject<Block> MANGROVE_PLANKS = ModRegistry.<Block>registerBlock("Mangrove Planks", MangrovePlanksBlock::new);
   public static final RegistryObject<Block> PONEGLYPH = ModRegistry.<Block>registerBlock("Poneglyph", PoneglyphBlock::new);
   public static final RegistryObject<Block> TANGERINE_CROP = ModRegistry.<Block>registerBlock("Tangerine Crop", TangerineCropsBlock::new);

   public static void init() {
   }
}
