package xyz.pixelatedw.mineminenomi.init;

import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.effect.MobEffectCategory;
import net.minecraft.world.entity.ai.attributes.Attribute;
import net.minecraft.world.entity.ai.attributes.AttributeModifier.Operation;
import net.minecraftforge.common.ForgeMod;
import net.minecraftforge.registries.RegistryObject;
import xyz.pixelatedw.mineminenomi.api.enums.HandcuffType;
import xyz.pixelatedw.mineminenomi.api.enums.NetType;
import xyz.pixelatedw.mineminenomi.effects.AntiBodyIceOniEffect;
import xyz.pixelatedw.mineminenomi.effects.AntiBodyMummyVirusEffect;
import xyz.pixelatedw.mineminenomi.effects.AntiKnockbackEffect;
import xyz.pixelatedw.mineminenomi.effects.AntidoteEffect;
import xyz.pixelatedw.mineminenomi.effects.BaseEffect;
import xyz.pixelatedw.mineminenomi.effects.BindEffect;
import xyz.pixelatedw.mineminenomi.effects.BlackBoxEffect;
import xyz.pixelatedw.mineminenomi.effects.BubblyCoralEffect;
import xyz.pixelatedw.mineminenomi.effects.CandleLockEffect;
import xyz.pixelatedw.mineminenomi.effects.CandyStuckEffect;
import xyz.pixelatedw.mineminenomi.effects.CarryingEffect;
import xyz.pixelatedw.mineminenomi.effects.CaughtInNetEffect;
import xyz.pixelatedw.mineminenomi.effects.ChiyuHormoneEffect;
import xyz.pixelatedw.mineminenomi.effects.ChiyupopoEffect;
import xyz.pixelatedw.mineminenomi.effects.CycloneTempoEffect;
import xyz.pixelatedw.mineminenomi.effects.DFCurseEffect;
import xyz.pixelatedw.mineminenomi.effects.DamageOverTimeEffect;
import xyz.pixelatedw.mineminenomi.effects.DehydrationEffect;
import xyz.pixelatedw.mineminenomi.effects.DizzyEffect;
import xyz.pixelatedw.mineminenomi.effects.DoaVanishEffect;
import xyz.pixelatedw.mineminenomi.effects.DokuPoisonEffect;
import xyz.pixelatedw.mineminenomi.effects.DoorHeadEffect;
import xyz.pixelatedw.mineminenomi.effects.DrunkEffect;
import xyz.pixelatedw.mineminenomi.effects.FatigueEffect;
import xyz.pixelatedw.mineminenomi.effects.FragileEffect;
import xyz.pixelatedw.mineminenomi.effects.FrostbiteEffect;
import xyz.pixelatedw.mineminenomi.effects.FrozenEffect;
import xyz.pixelatedw.mineminenomi.effects.GanmenSeichoHormoneEffect;
import xyz.pixelatedw.mineminenomi.effects.GenocideRaidEffect;
import xyz.pixelatedw.mineminenomi.effects.GrabbedEffect;
import xyz.pixelatedw.mineminenomi.effects.HakiOveruseEffect;
import xyz.pixelatedw.mineminenomi.effects.HandcuffedEffect;
import xyz.pixelatedw.mineminenomi.effects.HeatEggTempoEffect;
import xyz.pixelatedw.mineminenomi.effects.HungerOverTimeEffect;
import xyz.pixelatedw.mineminenomi.effects.IceOniEffect;
import xyz.pixelatedw.mineminenomi.effects.ImpactFrameEffect;
import xyz.pixelatedw.mineminenomi.effects.InEventEffect;
import xyz.pixelatedw.mineminenomi.effects.LookoutEffect;
import xyz.pixelatedw.mineminenomi.effects.LovestruckEffect;
import xyz.pixelatedw.mineminenomi.effects.MovementBlockedEffect;
import xyz.pixelatedw.mineminenomi.effects.MummyVirusEffect;
import xyz.pixelatedw.mineminenomi.effects.NegativeEffect;
import xyz.pixelatedw.mineminenomi.effects.NoHandsEffect;
import xyz.pixelatedw.mineminenomi.effects.NoroSlownessEffect;
import xyz.pixelatedw.mineminenomi.effects.OilCoveredEffect;
import xyz.pixelatedw.mineminenomi.effects.ParalysisEffect;
import xyz.pixelatedw.mineminenomi.effects.PlayDeadEffect;
import xyz.pixelatedw.mineminenomi.effects.PunkCrossEffect;
import xyz.pixelatedw.mineminenomi.effects.ReducedFallEffect;
import xyz.pixelatedw.mineminenomi.effects.SeismicBubbleEffect;
import xyz.pixelatedw.mineminenomi.effects.SilentEffect;
import xyz.pixelatedw.mineminenomi.effects.SmokeEffect;
import xyz.pixelatedw.mineminenomi.effects.StickyEffect;
import xyz.pixelatedw.mineminenomi.effects.TensionHormoneEffect;
import xyz.pixelatedw.mineminenomi.effects.TokudaiCandlePoisonEffect;
import xyz.pixelatedw.mineminenomi.effects.UnconsciousEffect;
import xyz.pixelatedw.mineminenomi.effects.VanishEffect;
import xyz.pixelatedw.mineminenomi.effects.WashedEffect;
import xyz.pixelatedw.mineminenomi.effects.WetEffect;

public class ModEffects {
   public static final RegistryObject<MobEffect> BUBBLY_CORAL = ModRegistry.<MobEffect>registerEffect("Bubbly Coral", BubblyCoralEffect::new);
   public static final RegistryObject<MobEffect> ANIMAL_LOOKOUT = ModRegistry.<MobEffect>registerEffect("Animal Lookout", LookoutEffect::new);
   public static final RegistryObject<MobEffect> CANDLE_LOCK = ModRegistry.<MobEffect>registerEffect("Candle Lock", CandleLockEffect::new);
   public static final RegistryObject<MobEffect> LOVESTRUCK = ModRegistry.<MobEffect>registerEffect("Lovestruck", LovestruckEffect::new);
   public static final RegistryObject<MobEffect> NEGATIVE = ModRegistry.<MobEffect>registerEffect("Negative", NegativeEffect::new);
   public static final RegistryObject<MobEffect> CHIYU_HORMONE = ModRegistry.<MobEffect>registerEffect("Chiyu Hormone", ChiyuHormoneEffect::new);
   public static final RegistryObject<MobEffect> FROSTBITE = ModRegistry.<MobEffect>registerEffect("Frostbite", FrostbiteEffect::new);
   public static final RegistryObject<MobEffect> FROZEN = ModRegistry.<MobEffect>registerEffect("Frozen", FrozenEffect::new);
   public static final RegistryObject<MobEffect> TENSION_HORMONE = ModRegistry.<MobEffect>registerEffect("Tension Hormone", TensionHormoneEffect::new);
   public static final RegistryObject<MobEffect> GANMEN_SEICHO_HORMONE = ModRegistry.<MobEffect>registerEffect("Ganmen Seicho Hormone", GanmenSeichoHormoneEffect::new);
   public static final RegistryObject<MobEffect> DRUNK = ModRegistry.<MobEffect>registerEffect("Drunk", DrunkEffect::new);
   public static final RegistryObject<MobEffect> DOOR_HEAD = ModRegistry.<MobEffect>registerEffect("Door Head", DoorHeadEffect::new);
   public static final RegistryObject<MobEffect> DIZZY = ModRegistry.<MobEffect>registerEffect("Dizzy", DizzyEffect::new);
   public static final RegistryObject<MobEffect> MOVEMENT_BLOCKED = ModRegistry.<MobEffect>registerEffect("Movement Blocked", MovementBlockedEffect::new);
   public static final RegistryObject<MobEffect> UNCONSCIOUS = ModRegistry.<MobEffect>registerEffect("Unconscious", UnconsciousEffect::new);
   public static final RegistryObject<MobEffect> WASHED = ModRegistry.<MobEffect>registerEffect("Washed", WashedEffect::new);
   public static final RegistryObject<MobEffect> STICKY = ModRegistry.<MobEffect>registerEffect("Sticky", StickyEffect::new);
   public static final RegistryObject<MobEffect> BLACK_BOX = ModRegistry.<MobEffect>registerEffect("Black Box", BlackBoxEffect::new);
   public static final RegistryObject<MobEffect> CANDY_STUCK = ModRegistry.<MobEffect>registerEffect("Candy Stuck", CandyStuckEffect::new);
   public static final RegistryObject<MobEffect> PARALYSIS = ModRegistry.<MobEffect>registerEffect("Paralysis", ParalysisEffect::new);
   public static final RegistryObject<MobEffect> HAKI_OVERUSE = ModRegistry.<MobEffect>registerEffect("Haki Overuse", HakiOveruseEffect::new);
   public static final RegistryObject<MobEffect> SMOKE = ModRegistry.<MobEffect>registerEffect("Smoke", SmokeEffect::new);
   public static final RegistryObject<MobEffect> REDUCED_FALL = ModRegistry.<MobEffect>registerEffect("Reduced Fall", ReducedFallEffect::new);
   public static final RegistryObject<MobEffect> HANDCUFFED = ModRegistry.<MobEffect>registerEffect("Handcuffed", () -> new HandcuffedEffect(HandcuffType.NORMAL));
   public static final RegistryObject<MobEffect> HANDCUFFED_KAIROSEKI = ModRegistry.<MobEffect>registerEffect("Handcuffed", "handcuffed_kairoseki", () -> new HandcuffedEffect(HandcuffType.KAIROSEKI));
   public static final RegistryObject<MobEffect> HANDCUFFED_EXPLOSIVE = ModRegistry.<MobEffect>registerEffect("Handcuffed", "handcuffed_explosive", () -> new HandcuffedEffect(HandcuffType.EXPLOSIVE));
   public static final RegistryObject<MobEffect> BIND = ModRegistry.<MobEffect>registerEffect("Bind", BindEffect::new);
   public static final RegistryObject<MobEffect> NO_HANDS = ModRegistry.<MobEffect>registerEffect("No Hands", NoHandsEffect::new);
   public static final RegistryObject<MobEffect> FATIGUE_EFFECT = ModRegistry.<MobEffect>registerEffect("Fatigue", FatigueEffect::new);
   public static final RegistryObject<MobEffect> NORO_SLOWNESS = ModRegistry.<MobEffect>registerEffect("Noro Slowness", NoroSlownessEffect::new);
   public static final RegistryObject<MobEffect> BLEEDING = ModRegistry.<MobEffect>registerEffect("Bleeding", () -> new DamageOverTimeEffect((entity) -> ModDamageSources.getInstance().bleed(), 2.0F, 20));
   public static final RegistryObject<MobEffect> SILENT = ModRegistry.<MobEffect>registerEffect("Silent", SilentEffect::new);
   public static final RegistryObject<MobEffect> SABOTEN_BOSHI = ModRegistry.<MobEffect>registerEffect("Saboten Boshi", () -> new DamageOverTimeEffect((entity) -> entity.m_269291_().m_269325_(), 2.0F, 40));
   public static final RegistryObject<MobEffect> OIL_COVERED = ModRegistry.<MobEffect>registerEffect("Oil Covered", OilCoveredEffect::new);
   public static final RegistryObject<MobEffect> DEHYDRATION = ModRegistry.<MobEffect>registerEffect("Dehydration", DehydrationEffect::new);
   public static final RegistryObject<MobEffect> GENOCIDE_RAID = ModRegistry.<MobEffect>registerEffect("Genocide Raid", GenocideRaidEffect::new);
   public static final RegistryObject<MobEffect> DOKU_POISON = ModRegistry.<MobEffect>registerEffect("Doku Poison", DokuPoisonEffect::new);
   public static final RegistryObject<MobEffect> PUNK_CROSS = ModRegistry.<MobEffect>registerEffect("Punk Cross", PunkCrossEffect::new);
   public static final RegistryObject<MobEffect> VANISH = ModRegistry.<MobEffect>registerEffect("Vanish", VanishEffect::new);
   public static final RegistryObject<MobEffect> SUKE_INVISIBILITY = ModRegistry.<MobEffect>registerEffect("Suke Invisibility", VanishEffect::new);
   public static final RegistryObject<MobEffect> DOA_INVISIBILITY = ModRegistry.<MobEffect>registerEffect("Doa Invisibility", DoaVanishEffect::new);
   public static final RegistryObject<MobEffect> SEISMIC_BUBBLE = ModRegistry.<MobEffect>registerEffect("Seismic Bubble", SeismicBubbleEffect::new);
   public static final RegistryObject<MobEffect> IN_EVENT = ModRegistry.<MobEffect>registerEffect("In Event", InEventEffect::new);
   public static final RegistryObject<MobEffect> ANTIDOTE = ModRegistry.<MobEffect>registerEffect("Antidote", AntidoteEffect::new);
   public static final RegistryObject<MobEffect> HUNGER = ModRegistry.<MobEffect>registerEffect("Hunger", HungerOverTimeEffect::new);
   public static final RegistryObject<MobEffect> MUMMY_VIRUS = ModRegistry.<MobEffect>registerEffect("Mummy", MummyVirusEffect::new);
   public static final RegistryObject<MobEffect> MUMMY_VIRUS_ANTIBODY = ModRegistry.<MobEffect>registerEffect("Mummy Antibody", AntiBodyMummyVirusEffect::new);
   public static final RegistryObject<MobEffect> ICE_ONI = ModRegistry.<MobEffect>registerEffect("Ice Oni", IceOniEffect::new);
   public static final RegistryObject<MobEffect> ICE_ONI_ANTIBODY = ModRegistry.<MobEffect>registerEffect("Ice Oni Antibody", AntiBodyIceOniEffect::new);
   public static final RegistryObject<MobEffect> ICE_ONI_FROSTBITE = ModRegistry.<MobEffect>registerEffect("Ice Oni Frostbite", () -> new FrostbiteEffect(true));
   public static final RegistryObject<MobEffect> CHIYUPOPO = ModRegistry.<MobEffect>registerEffect("Chiyupopo", ChiyupopoEffect::new);
   public static final RegistryObject<MobEffect> TOKUDAI_CANDLE_POISON = ModRegistry.<MobEffect>registerEffect("Tokudai Candle Poison", TokudaiCandlePoisonEffect::new);
   public static final RegistryObject<MobEffect> CYCLONE_TEMPO = ModRegistry.<MobEffect>registerEffect("Cyclone Tempo", CycloneTempoEffect::new);
   public static final RegistryObject<MobEffect> HEAT_EGG_TEMPO = ModRegistry.<MobEffect>registerEffect("Heat Egg Tempo", HeatEggTempoEffect::new);
   public static final RegistryObject<MobEffect> KAIROSEKI_WEAKNESS = ModRegistry.<MobEffect>registerEffect("Kairoseki Weakness", DFCurseEffect::new);
   public static final RegistryObject<MobEffect> WATER_WEAKNESS = ModRegistry.<MobEffect>registerEffect("Water Weakness", DFCurseEffect::new);
   public static final RegistryObject<MobEffect> PLAY_DEAD = ModRegistry.<MobEffect>registerEffect("Play Dead", PlayDeadEffect::new);
   public static final RegistryObject<MobEffect> CHALLENGE_FAILED = ModRegistry.<MobEffect>registerEffect("Challenge Failed", UnconsciousEffect::new);
   public static final RegistryObject<CaughtInNetEffect> CAUGHT_IN_NET = ModRegistry.<CaughtInNetEffect>registerEffect("Caught in Net", "caught_in_net", () -> new CaughtInNetEffect(NetType.NORMAL));
   public static final RegistryObject<CaughtInNetEffect> CAUGHT_IN_KAIROSEKI_NET = ModRegistry.<CaughtInNetEffect>registerEffect("Caught in Net", "caught_in_kairoseki_net", () -> new CaughtInNetEffect(NetType.KAIROSEKI));
   public static final RegistryObject<MobEffect> CARRYING = ModRegistry.<MobEffect>registerEffect("Carrying", CarryingEffect::new);
   public static final RegistryObject<MobEffect> WET = ModRegistry.<MobEffect>registerEffect("Wet", WetEffect::new);
   public static final RegistryObject<MobEffect> SWIM_SLOWDOWN = ModRegistry.<MobEffect>registerEffect("Swim Slowdown", () -> (new BaseEffect(MobEffectCategory.HARMFUL, 5926017)).m_19472_((Attribute)ForgeMod.SWIM_SPEED.get(), "d4e714aa-9792-4b12-91d6-4b46a248c9e0", -0.15, Operation.MULTIPLY_TOTAL));
   public static final RegistryObject<MobEffect> GRABBED = ModRegistry.<MobEffect>registerEffect("Grabbed", GrabbedEffect::new);
   public static final RegistryObject<MobEffect> ANTI_KNOCKBACK = ModRegistry.<MobEffect>registerEffect("Anti Knockback", AntiKnockbackEffect::new);
   public static final RegistryObject<MobEffect> LAUNCHED = ModRegistry.<MobEffect>registerEffect("Launched", () -> new BaseEffect(MobEffectCategory.NEUTRAL, 0));
   public static final RegistryObject<MobEffect> FRAGILE = ModRegistry.<MobEffect>registerEffect("Fragile", FragileEffect::new);
   public static final RegistryObject<MobEffect> IMPACT_FRAME = ModRegistry.<MobEffect>registerEffect("Impact Frame", ImpactFrameEffect::new);

   public static void init() {
   }
}
