package xyz.pixelatedw.mineminenomi.init;

import java.util.function.Supplier;
import net.minecraftforge.registries.RegistryObject;
import xyz.pixelatedw.mineminenomi.abilities.BulletReflectAbility;
import xyz.pixelatedw.mineminenomi.abilities.ExplosionImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.HandcuffsImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.HeatImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.LogiaHeatImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.LogiaImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.NegativeImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.NoFallDamageAbility;
import xyz.pixelatedw.mineminenomi.abilities.PoisonImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.SlashDamageImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.awa.GoldenHourAbility;
import xyz.pixelatedw.mineminenomi.abilities.awa.RelaxHourAbility;
import xyz.pixelatedw.mineminenomi.abilities.awa.SoapDefenseAbility;
import xyz.pixelatedw.mineminenomi.abilities.baku.BakuFactoryAbility;
import xyz.pixelatedw.mineminenomi.abilities.baku.BakuMunchAbility;
import xyz.pixelatedw.mineminenomi.abilities.baku.BakuTsuihoAbility;
import xyz.pixelatedw.mineminenomi.abilities.baku.BeroCannonAbility;
import xyz.pixelatedw.mineminenomi.abilities.bane.SpringDeathKnockAbility;
import xyz.pixelatedw.mineminenomi.abilities.bane.SpringHopperAbility;
import xyz.pixelatedw.mineminenomi.abilities.bane.SpringSnipeAbility;
import xyz.pixelatedw.mineminenomi.abilities.bara.BaraBaraCarAbility;
import xyz.pixelatedw.mineminenomi.abilities.bara.BaraBaraFestivalAbility;
import xyz.pixelatedw.mineminenomi.abilities.bara.BaraBaraHoAbility;
import xyz.pixelatedw.mineminenomi.abilities.bara.BaraSplitAbility;
import xyz.pixelatedw.mineminenomi.abilities.bara.KuchuKirimomiDaiCircusAbility;
import xyz.pixelatedw.mineminenomi.abilities.bari.BariBariNoPistolAbility;
import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierAbility;
import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierBallAbility;
import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierCrashAbility;
import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierbilityBatAbility;
import xyz.pixelatedw.mineminenomi.abilities.bari.BarrierbilityStairsAbility;
import xyz.pixelatedw.mineminenomi.abilities.beta.BetaBetaChainAbility;
import xyz.pixelatedw.mineminenomi.abilities.beta.BetaCoatingAbility;
import xyz.pixelatedw.mineminenomi.abilities.beta.BetaImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.beta.BetaLauncherAbility;
import xyz.pixelatedw.mineminenomi.abilities.beta.HanamizuShinkenAbility;
import xyz.pixelatedw.mineminenomi.abilities.bomu.BreezeBreathBombAbility;
import xyz.pixelatedw.mineminenomi.abilities.bomu.ExplosivePunchAbility;
import xyz.pixelatedw.mineminenomi.abilities.bomu.KickBombAbility;
import xyz.pixelatedw.mineminenomi.abilities.bomu.NoseFancyCannonAbility;
import xyz.pixelatedw.mineminenomi.abilities.bomu.ZenshinKibakuAbility;
import xyz.pixelatedw.mineminenomi.abilities.chiyu.ChiyupopoAbility;
import xyz.pixelatedw.mineminenomi.abilities.chiyu.HealingTouchAbility;
import xyz.pixelatedw.mineminenomi.abilities.chiyu.KenpopoAbility;
import xyz.pixelatedw.mineminenomi.abilities.chiyu.TearsAbility;
import xyz.pixelatedw.mineminenomi.abilities.deka.DekaDekaAbility;
import xyz.pixelatedw.mineminenomi.abilities.deka.DekaTrampleAbility;
import xyz.pixelatedw.mineminenomi.abilities.doa.AirDoorAbility;
import xyz.pixelatedw.mineminenomi.abilities.doa.DoorDoorAbility;
import xyz.pixelatedw.mineminenomi.abilities.doa.KaitenDoorAbility;
import xyz.pixelatedw.mineminenomi.abilities.doku.ChloroBallAbility;
import xyz.pixelatedw.mineminenomi.abilities.doku.DokuFuguAbility;
import xyz.pixelatedw.mineminenomi.abilities.doku.DokuGumoAbility;
import xyz.pixelatedw.mineminenomi.abilities.doku.HydraAbility;
import xyz.pixelatedw.mineminenomi.abilities.doku.VenomDemonAbility;
import xyz.pixelatedw.mineminenomi.abilities.doku.VenomRoadAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.CandleChampionAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.CandleHouseAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.CandleLockAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.CandleWallAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruArtsKenAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruArtsMoriAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruArtsPickaxeAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruBallAbility;
import xyz.pixelatedw.mineminenomi.abilities.doru.DoruDoruNoYakataAbility;
import xyz.pixelatedw.mineminenomi.abilities.gasu.BlueSwordAbility;
import xyz.pixelatedw.mineminenomi.abilities.gasu.GasRobeAbility;
import xyz.pixelatedw.mineminenomi.abilities.gasu.GastanetAbility;
import xyz.pixelatedw.mineminenomi.abilities.gasu.GastilleAbility;
import xyz.pixelatedw.mineminenomi.abilities.gasu.GasuFlyAbility;
import xyz.pixelatedw.mineminenomi.abilities.gasu.GasuImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.gasu.GasuLogiaAbility;
import xyz.pixelatedw.mineminenomi.abilities.gasu.KarakuniAbility;
import xyz.pixelatedw.mineminenomi.abilities.gasu.KoroAbility;
import xyz.pixelatedw.mineminenomi.abilities.gasu.ShinokuniAbility;
import xyz.pixelatedw.mineminenomi.abilities.goe.DragonsRoarAbility;
import xyz.pixelatedw.mineminenomi.abilities.goe.TodorokiAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.BouncyAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GearFifthAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GearFourthAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GearFourthFlightAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GearSecondAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GearThirdAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoBazookaAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoDawnWhipAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoGatlingAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoGigantAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoPistolAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuGomuNoRocketAbility;
import xyz.pixelatedw.mineminenomi.abilities.gomu.GomuImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.goro.ElThorAbility;
import xyz.pixelatedw.mineminenomi.abilities.goro.GoroLogiaAbility;
import xyz.pixelatedw.mineminenomi.abilities.goro.GoroTravelAbility;
import xyz.pixelatedw.mineminenomi.abilities.goro.KariAbility;
import xyz.pixelatedw.mineminenomi.abilities.goro.RaigoAbility;
import xyz.pixelatedw.mineminenomi.abilities.goro.SangoAbility;
import xyz.pixelatedw.mineminenomi.abilities.goro.SparkStepAbility;
import xyz.pixelatedw.mineminenomi.abilities.goro.VariAbility;
import xyz.pixelatedw.mineminenomi.abilities.goro.VoltAmaruAbility;
import xyz.pixelatedw.mineminenomi.abilities.goro.VoltAmaruFlightAbility;
import xyz.pixelatedw.mineminenomi.abilities.gura.GekishinAbility;
import xyz.pixelatedw.mineminenomi.abilities.gura.GuraImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.gura.KabutowariAbility;
import xyz.pixelatedw.mineminenomi.abilities.gura.ShimaYurashiAbility;
import xyz.pixelatedw.mineminenomi.abilities.gura.ShingenNoIchigekiAbility;
import xyz.pixelatedw.mineminenomi.abilities.gura.TenchiMeidoAbility;
import xyz.pixelatedw.mineminenomi.abilities.hana.CampoDeFloresAbility;
import xyz.pixelatedw.mineminenomi.abilities.hana.CienFleurStompAbility;
import xyz.pixelatedw.mineminenomi.abilities.hana.CienFleurWingAbility;
import xyz.pixelatedw.mineminenomi.abilities.hana.DosFleurClutchAbility;
import xyz.pixelatedw.mineminenomi.abilities.hana.MilFleurAbility;
import xyz.pixelatedw.mineminenomi.abilities.hana.SeisFleurSlapAbility;
import xyz.pixelatedw.mineminenomi.abilities.hana.SeisFleurTwistAbility;
import xyz.pixelatedw.mineminenomi.abilities.hana.VeinteFleurCalendulaAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.FrostWalkerAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.HieImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.HieLogiaAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.HieTravelAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.IceAgeAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.IceBallAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.IceBlockAvalancheAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.IceBlockPartisanAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.IceBlockPheasantAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.IceSaberAbility;
import xyz.pixelatedw.mineminenomi.abilities.hie.IceTimeAbility;
import xyz.pixelatedw.mineminenomi.abilities.hiso.ForewarnAbility;
import xyz.pixelatedw.mineminenomi.abilities.hiso.LookoutAbility;
import xyz.pixelatedw.mineminenomi.abilities.hitodaibutsu.HitoDaibutsuPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.hitodaibutsu.ImpactBlastAbility;
import xyz.pixelatedw.mineminenomi.abilities.horo.MiniHollowAbility;
import xyz.pixelatedw.mineminenomi.abilities.horo.NegativeHollowAbility;
import xyz.pixelatedw.mineminenomi.abilities.horo.TokuHollowAbility;
import xyz.pixelatedw.mineminenomi.abilities.horo.YutaiRidatsuAbility;
import xyz.pixelatedw.mineminenomi.abilities.horu.ChiyuHormoneAbility;
import xyz.pixelatedw.mineminenomi.abilities.horu.DeathWinkAbility;
import xyz.pixelatedw.mineminenomi.abilities.horu.GanmenSeichoHormoneAbility;
import xyz.pixelatedw.mineminenomi.abilities.horu.OnnaHormoneAbility;
import xyz.pixelatedw.mineminenomi.abilities.horu.TensionHormoneAbility;
import xyz.pixelatedw.mineminenomi.abilities.ito.BlackKnightAbility;
import xyz.pixelatedw.mineminenomi.abilities.ito.FullbrightAbility;
import xyz.pixelatedw.mineminenomi.abilities.ito.KumoNoSugakiAbility;
import xyz.pixelatedw.mineminenomi.abilities.ito.OverheatAbility;
import xyz.pixelatedw.mineminenomi.abilities.ito.ParasiteAbility;
import xyz.pixelatedw.mineminenomi.abilities.ito.SoraNoMichiAbility;
import xyz.pixelatedw.mineminenomi.abilities.ito.TamaitoAbility;
import xyz.pixelatedw.mineminenomi.abilities.ito.TorikagoAbility;
import xyz.pixelatedw.mineminenomi.abilities.jiki.AttractAbility;
import xyz.pixelatedw.mineminenomi.abilities.jiki.DamnedPunkAbility;
import xyz.pixelatedw.mineminenomi.abilities.jiki.GenocideRaidAbility;
import xyz.pixelatedw.mineminenomi.abilities.jiki.MagneticItemsAbility;
import xyz.pixelatedw.mineminenomi.abilities.jiki.PunkCornaDioAbility;
import xyz.pixelatedw.mineminenomi.abilities.jiki.PunkCrossAbility;
import xyz.pixelatedw.mineminenomi.abilities.jiki.PunkGibsonAbility;
import xyz.pixelatedw.mineminenomi.abilities.jiki.PunkPistolsAbility;
import xyz.pixelatedw.mineminenomi.abilities.jiki.RepelAbility;
import xyz.pixelatedw.mineminenomi.abilities.kachi.EvaporateAbility;
import xyz.pixelatedw.mineminenomi.abilities.kachi.HotBoilingSpecialAbility;
import xyz.pixelatedw.mineminenomi.abilities.kachi.VulcanizationAbility;
import xyz.pixelatedw.mineminenomi.abilities.kage.BlackBoxAbility;
import xyz.pixelatedw.mineminenomi.abilities.kage.BrickBatAbility;
import xyz.pixelatedw.mineminenomi.abilities.kage.DoppelmanAbility;
import xyz.pixelatedw.mineminenomi.abilities.kage.KageGiriAbility;
import xyz.pixelatedw.mineminenomi.abilities.kage.KageKakumeiAbility;
import xyz.pixelatedw.mineminenomi.abilities.kage.KagemushaAbility;
import xyz.pixelatedw.mineminenomi.abilities.kage.NightmareSoldiersAbility;
import xyz.pixelatedw.mineminenomi.abilities.kage.ShadowsAsgardAbility;
import xyz.pixelatedw.mineminenomi.abilities.kage.TsunoTokageAbility;
import xyz.pixelatedw.mineminenomi.abilities.kame.KameGuardPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.kame.KameRideableAbility;
import xyz.pixelatedw.mineminenomi.abilities.kame.KameWalkPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.karu.IngaZarashiAbility;
import xyz.pixelatedw.mineminenomi.abilities.karu.KarmaAbility;
import xyz.pixelatedw.mineminenomi.abilities.kilo.KiloPress10000Ability;
import xyz.pixelatedw.mineminenomi.abilities.kilo.KiloPress1Ability;
import xyz.pixelatedw.mineminenomi.abilities.kilo.KiloPunch5000Ability;
import xyz.pixelatedw.mineminenomi.abilities.kira.BrilliantPunkAbility;
import xyz.pixelatedw.mineminenomi.abilities.kira.CabochonKnuckleAbility;
import xyz.pixelatedw.mineminenomi.abilities.kira.DiamondBodyAbility;
import xyz.pixelatedw.mineminenomi.abilities.kobu.ShoureiAbility;
import xyz.pixelatedw.mineminenomi.abilities.kuku.GastronomorphAbility;
import xyz.pixelatedw.mineminenomi.abilities.kuku.GourmetSnipeAbility;
import xyz.pixelatedw.mineminenomi.abilities.kuku.GourmetamorphosisAbility;
import xyz.pixelatedw.mineminenomi.abilities.magu.BakuretsuKazanAbility;
import xyz.pixelatedw.mineminenomi.abilities.magu.DaiFunkaAbility;
import xyz.pixelatedw.mineminenomi.abilities.magu.LavaFlowAbility;
import xyz.pixelatedw.mineminenomi.abilities.magu.MagmaCoatingAbility;
import xyz.pixelatedw.mineminenomi.abilities.magu.MaguLogiaAbility;
import xyz.pixelatedw.mineminenomi.abilities.magu.MeigoAbility;
import xyz.pixelatedw.mineminenomi.abilities.magu.RyuseiKazanAbility;
import xyz.pixelatedw.mineminenomi.abilities.mera.DaiEnkaiAbility;
import xyz.pixelatedw.mineminenomi.abilities.mera.HeatDashAbility;
import xyz.pixelatedw.mineminenomi.abilities.mera.HibashiraAbility;
import xyz.pixelatedw.mineminenomi.abilities.mera.HidarumaAbility;
import xyz.pixelatedw.mineminenomi.abilities.mera.HiganAbility;
import xyz.pixelatedw.mineminenomi.abilities.mera.HikenAbility;
import xyz.pixelatedw.mineminenomi.abilities.mera.JujikaAbility;
import xyz.pixelatedw.mineminenomi.abilities.mera.KyokaenAbility;
import xyz.pixelatedw.mineminenomi.abilities.mera.MeraLogiaAbility;
import xyz.pixelatedw.mineminenomi.abilities.mero.MeroMeroMellowAbility;
import xyz.pixelatedw.mineminenomi.abilities.mero.PerfumeFemurAbility;
import xyz.pixelatedw.mineminenomi.abilities.mero.PistolKissAbility;
import xyz.pixelatedw.mineminenomi.abilities.mero.SlaveArrowAbility;
import xyz.pixelatedw.mineminenomi.abilities.mini.MiniMiniAbility;
import xyz.pixelatedw.mineminenomi.abilities.mini.PaperFloatAbility;
import xyz.pixelatedw.mineminenomi.abilities.mogu.MoguHeavyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.mogu.MoguraBananaAbility;
import xyz.pixelatedw.mineminenomi.abilities.mogu.MoguraTonpoAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.MokuFlyAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.MokuImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.MokuLogiaAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.SmokeLaunchAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteBlowAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteBlowRushAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteLauncherAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteOutAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.WhitePullAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteSnakeAbility;
import xyz.pixelatedw.mineminenomi.abilities.moku.WhiteStrikeAbility;
import xyz.pixelatedw.mineminenomi.abilities.nagi.SilentAbility;
import xyz.pixelatedw.mineminenomi.abilities.nekoleopard.ClawStrikeAbility;
import xyz.pixelatedw.mineminenomi.abilities.nekoleopard.FerociousLeapAbility;
import xyz.pixelatedw.mineminenomi.abilities.nekoleopard.LeopardHeavyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.nekoleopard.LeopardWalkPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.nekoleopard.NekoNightVisionAbility;
import xyz.pixelatedw.mineminenomi.abilities.netsu.HeatDenasshiAbility;
import xyz.pixelatedw.mineminenomi.abilities.netsu.NekkaiGyoraiAbility;
import xyz.pixelatedw.mineminenomi.abilities.netsu.NekkaiJigokuAbility;
import xyz.pixelatedw.mineminenomi.abilities.netsu.NetsuEnhancementAbility;
import xyz.pixelatedw.mineminenomi.abilities.nikyu.HanpatsuAbility;
import xyz.pixelatedw.mineminenomi.abilities.nikyu.NikyuPushAbility;
import xyz.pixelatedw.mineminenomi.abilities.nikyu.PadHoAbility;
import xyz.pixelatedw.mineminenomi.abilities.nikyu.PainRepelAbility;
import xyz.pixelatedw.mineminenomi.abilities.nikyu.PuniAbility;
import xyz.pixelatedw.mineminenomi.abilities.nikyu.TsuppariPadHoAbility;
import xyz.pixelatedw.mineminenomi.abilities.nikyu.UrsusShockAbility;
import xyz.pixelatedw.mineminenomi.abilities.noro.KyubiRushAbility;
import xyz.pixelatedw.mineminenomi.abilities.noro.NoroNoroBeamAbility;
import xyz.pixelatedw.mineminenomi.abilities.noro.NoroNoroBeamSwordAbility;
import xyz.pixelatedw.mineminenomi.abilities.ope.CounterShockAbility;
import xyz.pixelatedw.mineminenomi.abilities.ope.GammaKnifeAbility;
import xyz.pixelatedw.mineminenomi.abilities.ope.InjectionShotAbility;
import xyz.pixelatedw.mineminenomi.abilities.ope.MesAbility;
import xyz.pixelatedw.mineminenomi.abilities.ope.RoomAbility;
import xyz.pixelatedw.mineminenomi.abilities.ope.ShamblesAbility;
import xyz.pixelatedw.mineminenomi.abilities.ope.TaktAbility;
import xyz.pixelatedw.mineminenomi.abilities.ori.AwaseBaoriAbility;
import xyz.pixelatedw.mineminenomi.abilities.ori.BindAbility;
import xyz.pixelatedw.mineminenomi.abilities.ori.GreatCageAbility;
import xyz.pixelatedw.mineminenomi.abilities.oto.BonAbility;
import xyz.pixelatedw.mineminenomi.abilities.oto.DonAbility;
import xyz.pixelatedw.mineminenomi.abilities.oto.ShanAbility;
import xyz.pixelatedw.mineminenomi.abilities.pero.CandyArmorAbility;
import xyz.pixelatedw.mineminenomi.abilities.pero.CandyEscalatorAbility;
import xyz.pixelatedw.mineminenomi.abilities.pero.CandyManAbility;
import xyz.pixelatedw.mineminenomi.abilities.pero.CandyWallAbility;
import xyz.pixelatedw.mineminenomi.abilities.pero.CandyWaveAbility;
import xyz.pixelatedw.mineminenomi.abilities.pero.PeroImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.pika.AmaNoMurakumoAbility;
import xyz.pixelatedw.mineminenomi.abilities.pika.AmaterasuAbility;
import xyz.pixelatedw.mineminenomi.abilities.pika.FlashAbility;
import xyz.pixelatedw.mineminenomi.abilities.pika.LightAccelerationAbility;
import xyz.pixelatedw.mineminenomi.abilities.pika.PikaLogiaAbility;
import xyz.pixelatedw.mineminenomi.abilities.pika.PikaTravelAbility;
import xyz.pixelatedw.mineminenomi.abilities.pika.YasakaniNoMagatamaAbility;
import xyz.pixelatedw.mineminenomi.abilities.pika.YataNoKagamiAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryuallosaurus.AllosaurusHeavyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryuallosaurus.AllosaurusRideableAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryuallosaurus.AllosaurusWalkPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryuallosaurus.AncientBiteAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryuallosaurus.AncientTailSpinAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryubrachiosaurus.BrachioBomberAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryubrachiosaurus.BrachioGrabAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryubrachiosaurus.BrachiosaurusGuardPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryubrachiosaurus.BrachiosaurusHeavyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryubrachiosaurus.BrachiosaurusRideableAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.BarizodonAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.BeakGrabAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.PteranodonAssaultPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.PteranodonFlightAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.PteranodonFlyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.TankyudonAbility;
import xyz.pixelatedw.mineminenomi.abilities.ryupteranodon.TempuraudonAbility;
import xyz.pixelatedw.mineminenomi.abilities.sabi.RustBreakAbility;
import xyz.pixelatedw.mineminenomi.abilities.sabi.RustSkinAbility;
import xyz.pixelatedw.mineminenomi.abilities.sabi.RustTouchAbility;
import xyz.pixelatedw.mineminenomi.abilities.sai.HornDashAbility;
import xyz.pixelatedw.mineminenomi.abilities.sai.RhinoSmashAbility;
import xyz.pixelatedw.mineminenomi.abilities.sai.SaiHeavyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.sai.SaiRideableAbility;
import xyz.pixelatedw.mineminenomi.abilities.sai.SaiWalkPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.AxolotlHealAbility;
import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.AxolotlHeavyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.AxolotlWalkPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.HeartRegenAbility;
import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.PlayDeadAbility;
import xyz.pixelatedw.mineminenomi.abilities.saraaxolotl.PoisonSpitAbility;
import xyz.pixelatedw.mineminenomi.abilities.sube.SubeSubeDeflectAbility;
import xyz.pixelatedw.mineminenomi.abilities.sube.SubeSubeSpurAbility;
import xyz.pixelatedw.mineminenomi.abilities.sui.FreeSwimmingAbility;
import xyz.pixelatedw.mineminenomi.abilities.sui.NekomimiPunchAbility;
import xyz.pixelatedw.mineminenomi.abilities.sui.NyanNyanSuplexAbility;
import xyz.pixelatedw.mineminenomi.abilities.sui.NyanNyanSuplexBabyBusterAbility;
import xyz.pixelatedw.mineminenomi.abilities.suke.ShishaNoTeAbility;
import xyz.pixelatedw.mineminenomi.abilities.suke.SkattingAbility;
import xyz.pixelatedw.mineminenomi.abilities.suke.SukePunchAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.BarjanAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.DesertEncierroAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.DesertGirasoleAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.DesertGrandeEspadaAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.DesertSpadaAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.GrandeSablesAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.GroundDeathAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.SablesAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.SablesPesadoAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.SunaFlyAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.SunaLogiaAbility;
import xyz.pixelatedw.mineminenomi.abilities.suna.SunaTravelAbility;
import xyz.pixelatedw.mineminenomi.abilities.supa.AtomicSpurtAbility;
import xyz.pixelatedw.mineminenomi.abilities.supa.SparClawAbility;
import xyz.pixelatedw.mineminenomi.abilities.supa.SparklingDaisyAbility;
import xyz.pixelatedw.mineminenomi.abilities.supa.SpiderAbility;
import xyz.pixelatedw.mineminenomi.abilities.supa.SpiralHollowAbility;
import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.BlueBirdAbility;
import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.FlamesOfRegenerationAbility;
import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.FujiazamiAbility;
import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.PhoenixAssaultPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.PhoenixFlightAbility;
import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.PhoenixFlyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.PhoenixGoenAbility;
import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.SaiseiNoHonoAbility;
import xyz.pixelatedw.mineminenomi.abilities.toriphoenix.TenseiNoSoenAbility;
import xyz.pixelatedw.mineminenomi.abilities.ushibison.BisonHeavyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.ushibison.BisonRideableAbility;
import xyz.pixelatedw.mineminenomi.abilities.ushibison.BisonSmashAbility;
import xyz.pixelatedw.mineminenomi.abilities.ushibison.BisonWalkPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.ushibison.FiddleBanffAbility;
import xyz.pixelatedw.mineminenomi.abilities.ushibison.KokuteiCrossAbility;
import xyz.pixelatedw.mineminenomi.abilities.ushigiraffe.BiganAbility;
import xyz.pixelatedw.mineminenomi.abilities.ushigiraffe.GiraffeHeavyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.ushigiraffe.GiraffeRideableAbility;
import xyz.pixelatedw.mineminenomi.abilities.ushigiraffe.GiraffeWalkPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.wara.LifeMinusAbility;
import xyz.pixelatedw.mineminenomi.abilities.wara.StrawManAbility;
import xyz.pixelatedw.mineminenomi.abilities.wara.WarabideSwordAbility;
import xyz.pixelatedw.mineminenomi.abilities.yami.AbsorbedBlocksAbility;
import xyz.pixelatedw.mineminenomi.abilities.yami.BlackHoleAbility;
import xyz.pixelatedw.mineminenomi.abilities.yami.BlackRoadAbility;
import xyz.pixelatedw.mineminenomi.abilities.yami.BlackWorldAbility;
import xyz.pixelatedw.mineminenomi.abilities.yami.DarkMatterAbility;
import xyz.pixelatedw.mineminenomi.abilities.yami.KurouzuAbility;
import xyz.pixelatedw.mineminenomi.abilities.yami.LiberationAbility;
import xyz.pixelatedw.mineminenomi.abilities.yomi.KasuriutaFubukiGiriAbility;
import xyz.pixelatedw.mineminenomi.abilities.yomi.SoulParadeAbility;
import xyz.pixelatedw.mineminenomi.abilities.yomi.YomiImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.yomi.YomiNoReikiAbility;
import xyz.pixelatedw.mineminenomi.abilities.yuki.FubukiAbility;
import xyz.pixelatedw.mineminenomi.abilities.yuki.KamakuraAbility;
import xyz.pixelatedw.mineminenomi.abilities.yuki.KamakuraJussoshiAbility;
import xyz.pixelatedw.mineminenomi.abilities.yuki.TabiraYukiAbility;
import xyz.pixelatedw.mineminenomi.abilities.yuki.YukiGakiAbility;
import xyz.pixelatedw.mineminenomi.abilities.yuki.YukiImmunityAbility;
import xyz.pixelatedw.mineminenomi.abilities.yuki.YukiLogiaAbility;
import xyz.pixelatedw.mineminenomi.abilities.yuki.YukiRabiAbility;
import xyz.pixelatedw.mineminenomi.abilities.yuki.YukiTravelAbility;
import xyz.pixelatedw.mineminenomi.abilities.zou.GreatStompAbility;
import xyz.pixelatedw.mineminenomi.abilities.zou.IvoryDartAbility;
import xyz.pixelatedw.mineminenomi.abilities.zou.IvoryStompAbility;
import xyz.pixelatedw.mineminenomi.abilities.zou.TrunkShotAbility;
import xyz.pixelatedw.mineminenomi.abilities.zou.ZouGuardPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.zou.ZouHeavyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.zou.ZouRideableAbility;
import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.AncientStompAbility;
import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.AncientSweepAbility;
import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.AncientTrunkShotAbility;
import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.MammothGuardPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.MammothHeavyPointAbility;
import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.MammothRideableAbility;
import xyz.pixelatedw.mineminenomi.abilities.zoumammoth.MammothTrampleAbility;
import xyz.pixelatedw.mineminenomi.abilities.zushi.AbareHimatsuriAbility;
import xyz.pixelatedw.mineminenomi.abilities.zushi.GraviPullAbility;
import xyz.pixelatedw.mineminenomi.abilities.zushi.GraviZoneAbility;
import xyz.pixelatedw.mineminenomi.abilities.zushi.JigokuTabiAbility;
import xyz.pixelatedw.mineminenomi.abilities.zushi.MokoAbility;
import xyz.pixelatedw.mineminenomi.abilities.zushi.SagariNoRyuseiAbility;
import xyz.pixelatedw.mineminenomi.api.WyHelper;
import xyz.pixelatedw.mineminenomi.api.enums.FruitType;
import xyz.pixelatedw.mineminenomi.items.AkumaNoMiItem;

public class ModFruits {
   public static final RegistryObject<AkumaNoMiItem> RYU_RYU_NO_MI_ALLOSAURUS = ModRegistry.<AkumaNoMiItem>registerFruitItem("Ryu Ryu no Mi, Model: Allosaurus", () -> new AkumaNoMiItem(2, FruitType.ANCIENT_ZOAN, new RegistryObject[]{AllosaurusWalkPointAbility.INSTANCE, AllosaurusHeavyPointAbility.INSTANCE, AncientBiteAbility.INSTANCE, AncientTailSpinAbility.INSTANCE, AllosaurusRideableAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> SAI_SAI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Sai Sai no Mi", () -> new AkumaNoMiItem(2, FruitType.ZOAN, new RegistryObject[]{SaiWalkPointAbility.INSTANCE, SaiHeavyPointAbility.INSTANCE, RhinoSmashAbility.INSTANCE, HornDashAbility.INSTANCE, SaiRideableAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> SARA_SARA_NO_MI_AXOLOTL = ModRegistry.<AkumaNoMiItem>registerFruitItem("Sara Sara no Mi, Model: Axolotl", () -> new AkumaNoMiItem(2, FruitType.ZOAN, new RegistryObject[]{AxolotlHeavyPointAbility.INSTANCE, AxolotlWalkPointAbility.INSTANCE, PoisonSpitAbility.INSTANCE, AxolotlHealAbility.INSTANCE, PlayDeadAbility.INSTANCE, HeartRegenAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> RYU_RYU_NO_MI_BRACHIOSAURUS = ModRegistry.<AkumaNoMiItem>registerFruitItem("Ryu Ryu no Mi, Model: Brachiosaurus", () -> new AkumaNoMiItem(2, FruitType.ANCIENT_ZOAN, new RegistryObject[]{BrachiosaurusGuardPointAbility.INSTANCE, BrachiosaurusHeavyPointAbility.INSTANCE, BrachioBomberAbility.INSTANCE, BrachioGrabAbility.INSTANCE, BrachiosaurusRideableAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> RYU_RYU_NO_MI_PTERANODON = ModRegistry.<AkumaNoMiItem>registerFruitItem("Ryu Ryu no Mi, Model: Pteranodon", () -> new AkumaNoMiItem(2, FruitType.ANCIENT_ZOAN, new RegistryObject[]{PteranodonFlyPointAbility.INSTANCE, PteranodonAssaultPointAbility.INSTANCE, TempuraudonAbility.INSTANCE, TankyudonAbility.INSTANCE, BeakGrabAbility.INSTANCE, BarizodonAbility.INSTANCE, PteranodonFlightAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> KAME_KAME_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Kame Kame no Mi", () -> new AkumaNoMiItem(1, FruitType.ZOAN, new RegistryObject[]{KameGuardPointAbility.INSTANCE, KameWalkPointAbility.INSTANCE, KameRideableAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> NEKO_NEKO_NO_MI_LEOPARD = ModRegistry.<AkumaNoMiItem>registerFruitItem("Neko Neko no Mi, Model: Leopard", () -> new AkumaNoMiItem(2, FruitType.ZOAN, new RegistryObject[]{LeopardWalkPointAbility.INSTANCE, LeopardHeavyPointAbility.INSTANCE, FerociousLeapAbility.INSTANCE, ClawStrikeAbility.INSTANCE, NekoNightVisionAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> ZOU_ZOU_NO_MI_MAMMOTH = ModRegistry.<AkumaNoMiItem>registerFruitItem("Zou Zou no Mi, Model: Mammoth", () -> new AkumaNoMiItem(2, FruitType.ANCIENT_ZOAN, new RegistryObject[]{MammothGuardPointAbility.INSTANCE, MammothHeavyPointAbility.INSTANCE, MammothTrampleAbility.INSTANCE, AncientStompAbility.INSTANCE, AncientSweepAbility.INSTANCE, AncientTrunkShotAbility.INSTANCE, MammothRideableAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> HITO_HITO_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Hito Hito no Mi", () -> new AkumaNoMiItem(1, FruitType.ZOAN, new RegistryObject[0]));
   public static final RegistryObject<AkumaNoMiItem> USHI_USHI_NO_MI_GIRAFFE = ModRegistry.<AkumaNoMiItem>registerFruitItem("Ushi Ushi no Mi, Model: Giraffe", () -> new AkumaNoMiItem(1, FruitType.ZOAN, new RegistryObject[]{GiraffeHeavyPointAbility.INSTANCE, GiraffeWalkPointAbility.INSTANCE, BiganAbility.INSTANCE, GiraffeRideableAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> MOGU_MOGU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Mogu Mogu no Mi", () -> new AkumaNoMiItem(1, FruitType.ZOAN, new RegistryObject[]{MoguHeavyPointAbility.INSTANCE, MoguraBananaAbility.INSTANCE, MoguraTonpoAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> USHI_USHI_NO_MI_BISON = ModRegistry.<AkumaNoMiItem>registerFruitItem("Ushi Ushi no Mi, Model: Bison", () -> new AkumaNoMiItem(2, FruitType.ZOAN, new RegistryObject[]{BisonHeavyPointAbility.INSTANCE, BisonWalkPointAbility.INSTANCE, FiddleBanffAbility.INSTANCE, KokuteiCrossAbility.INSTANCE, BisonSmashAbility.INSTANCE, BisonRideableAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> ZOU_ZOU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Zou Zou no Mi", () -> new AkumaNoMiItem(2, FruitType.ZOAN, new RegistryObject[]{ZouGuardPointAbility.INSTANCE, ZouHeavyPointAbility.INSTANCE, TrunkShotAbility.INSTANCE, GreatStompAbility.INSTANCE, IvoryDartAbility.INSTANCE, IvoryStompAbility.INSTANCE, ZouRideableAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> HITO_HITO_NO_MI_DAIBUTSU = ModRegistry.<AkumaNoMiItem>registerFruitItem("Hito Hito no Mi, Model: Daibutsu", () -> new AkumaNoMiItem(3, FruitType.MYTHICAL_ZOAN, new RegistryObject[]{HitoDaibutsuPointAbility.INSTANCE, ImpactBlastAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> TORI_TORI_NO_MI_PHOENIX = ModRegistry.<AkumaNoMiItem>registerFruitItem("Tori Tori no Mi, Model: Phoenix", () -> new AkumaNoMiItem(3, FruitType.MYTHICAL_ZOAN, new RegistryObject[]{PhoenixAssaultPointAbility.INSTANCE, PhoenixFlyPointAbility.INSTANCE, PhoenixGoenAbility.INSTANCE, SaiseiNoHonoAbility.INSTANCE, FujiazamiAbility.INSTANCE, TenseiNoSoenAbility.INSTANCE, BlueBirdAbility.INSTANCE, FlamesOfRegenerationAbility.INSTANCE, PhoenixFlightAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> MOCHI_MOCHI_NO_MI = registerMochi("Mochi Mochi no Mi", () -> new AkumaNoMiItem(3, FruitType.PARAMECIA, new RegistryObject[0]));
   public static final RegistryObject<AkumaNoMiItem> DEKA_DEKA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Deka Deka no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{DekaDekaAbility.INSTANCE, DekaTrampleAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> KARU_KARU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Karu Karu no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{IngaZarashiAbility.INSTANCE, KarmaAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> JIKI_JIKI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Jiki Jiki no Mi", () -> new AkumaNoMiItem(3, FruitType.PARAMECIA, new RegistryObject[]{AttractAbility.INSTANCE, RepelAbility.INSTANCE, PunkGibsonAbility.INSTANCE, PunkPistolsAbility.INSTANCE, PunkCornaDioAbility.INSTANCE, DamnedPunkAbility.INSTANCE, MagneticItemsAbility.INSTANCE, GenocideRaidAbility.INSTANCE, PunkCrossAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> OTO_OTO_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Oto Oto no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{BonAbility.INSTANCE, DonAbility.INSTANCE, ShanAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> BARA_BARA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Bara Bara No Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{BaraBaraHoAbility.INSTANCE, BaraBaraFestivalAbility.INSTANCE, KuchuKirimomiDaiCircusAbility.INSTANCE, BaraBaraCarAbility.INSTANCE, BaraSplitAbility.INSTANCE, SlashDamageImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> SUBE_SUBE_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Sube Sube No Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{SubeSubeSpurAbility.INSTANCE, SubeSubeDeflectAbility.INSTANCE, HandcuffsImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> KOBU_KOBU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Kobu Kobu No Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{ShoureiAbility.INSTANCE, NegativeImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> HANA_HANA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Hana Hana No Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{DosFleurClutchAbility.INSTANCE, SeisFleurSlapAbility.INSTANCE, SeisFleurTwistAbility.INSTANCE, VeinteFleurCalendulaAbility.INSTANCE, CienFleurWingAbility.INSTANCE, CienFleurStompAbility.INSTANCE, CampoDeFloresAbility.INSTANCE, MilFleurAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> MINI_MINI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Mini Mini No Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{MiniMiniAbility.INSTANCE, PaperFloatAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> HISO_HISO_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Hiso Hiso No Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{ForewarnAbility.INSTANCE, LookoutAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> KUKU_KUKU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Kuku Kuku no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{GourmetamorphosisAbility.INSTANCE, GastronomorphAbility.INSTANCE, GourmetSnipeAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> KIRA_KIRA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Kira Kira no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{DiamondBodyAbility.INSTANCE, BrilliantPunkAbility.INSTANCE, CabochonKnuckleAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> BETA_BETA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Beta Beta no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{BetaCoatingAbility.INSTANCE, BetaLauncherAbility.INSTANCE, HanamizuShinkenAbility.INSTANCE, BetaBetaChainAbility.INSTANCE, BetaImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> NAGI_NAGI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Nagi Nagi no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{SilentAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> PERO_PERO_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Pero Pero no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{CandyManAbility.INSTANCE, CandyWallAbility.INSTANCE, CandyEscalatorAbility.INSTANCE, CandyWaveAbility.INSTANCE, CandyArmorAbility.INSTANCE, PeroImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> NETSU_NETSU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Netsu Netsu no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{NetsuEnhancementAbility.INSTANCE, NekkaiJigokuAbility.INSTANCE, NekkaiGyoraiAbility.INSTANCE, HeatDenasshiAbility.INSTANCE, HeatImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> SUI_SUI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Sui Sui no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{FreeSwimmingAbility.INSTANCE, NekomimiPunchAbility.INSTANCE, NyanNyanSuplexAbility.INSTANCE, NyanNyanSuplexBabyBusterAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> AWA_AWA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Awa Awa no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{GoldenHourAbility.INSTANCE, RelaxHourAbility.INSTANCE, SoapDefenseAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> WARA_WARA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Wara Wara no Mi", () -> new AkumaNoMiItem(3, FruitType.PARAMECIA, new RegistryObject[]{StrawManAbility.INSTANCE, WarabideSwordAbility.INSTANCE, LifeMinusAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> KACHI_KACHI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Kachi Kachi no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{EvaporateAbility.INSTANCE, HotBoilingSpecialAbility.INSTANCE, VulcanizationAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> DOA_DOA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Doa Doa no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{DoorDoorAbility.INSTANCE, KaitenDoorAbility.INSTANCE, AirDoorAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> CHIYU_CHIYU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Chiyu Chiyu no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{HealingTouchAbility.INSTANCE, ChiyupopoAbility.INSTANCE, KenpopoAbility.INSTANCE, TearsAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> SABI_SABI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Sabi Sabi no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{RustTouchAbility.INSTANCE, RustBreakAbility.INSTANCE, RustSkinAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> YOMI_YOMI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Yomi Yomi no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{SoulParadeAbility.INSTANCE, KasuriutaFubukiGiriAbility.INSTANCE, YomiNoReikiAbility.INSTANCE, YomiImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> BAKU_BAKU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Baku Baku no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{BakuMunchAbility.INSTANCE, BeroCannonAbility.INSTANCE, BakuTsuihoAbility.INSTANCE, BakuFactoryAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> HORU_HORU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Horu Horu no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{OnnaHormoneAbility.INSTANCE, ChiyuHormoneAbility.INSTANCE, TensionHormoneAbility.INSTANCE, GanmenSeichoHormoneAbility.INSTANCE, DeathWinkAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> KILO_KILO_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Kilo Kilo no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{KiloPress1Ability.INSTANCE, KiloPress10000Ability.INSTANCE, KiloPunch5000Ability.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> GOE_GOE_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Goe Goe no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{TodorokiAbility.INSTANCE, DragonsRoarAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> MERO_MERO_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Mero Mero no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{MeroMeroMellowAbility.INSTANCE, PistolKissAbility.INSTANCE, SlaveArrowAbility.INSTANCE, PerfumeFemurAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> ORI_ORI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Ori Ori no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{BindAbility.INSTANCE, GreatCageAbility.INSTANCE, AwaseBaoriAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> SUPA_SUPA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Supa Supa no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{SpiderAbility.INSTANCE, SparClawAbility.INSTANCE, SpiralHollowAbility.INSTANCE, SparklingDaisyAbility.INSTANCE, AtomicSpurtAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> HORO_HORO_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Horo Horo no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{NegativeHollowAbility.INSTANCE, MiniHollowAbility.INSTANCE, TokuHollowAbility.INSTANCE, YutaiRidatsuAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> ITO_ITO_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Ito Ito no Mi", () -> new AkumaNoMiItem(3, FruitType.PARAMECIA, new RegistryObject[]{ParasiteAbility.INSTANCE, SoraNoMichiAbility.INSTANCE, TamaitoAbility.INSTANCE, FullbrightAbility.INSTANCE, OverheatAbility.INSTANCE, KumoNoSugakiAbility.INSTANCE, TorikagoAbility.INSTANCE, BlackKnightAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> ZUSHI_ZUSHI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Zushi Zushi no Mi", () -> new AkumaNoMiItem(3, FruitType.PARAMECIA, new RegistryObject[]{JigokuTabiAbility.INSTANCE, SagariNoRyuseiAbility.INSTANCE, MokoAbility.INSTANCE, AbareHimatsuriAbility.INSTANCE, GraviZoneAbility.INSTANCE, GraviPullAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> BARI_BARI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Bari Bari no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{BarrierAbility.INSTANCE, BarrierBallAbility.INSTANCE, BarrierCrashAbility.INSTANCE, BariBariNoPistolAbility.INSTANCE, BarrierbilityStairsAbility.INSTANCE, BarrierbilityBatAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> DOKU_DOKU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Doku Doku no Mi", () -> new AkumaNoMiItem(3, FruitType.PARAMECIA, new RegistryObject[]{HydraAbility.INSTANCE, ChloroBallAbility.INSTANCE, DokuFuguAbility.INSTANCE, VenomRoadAbility.INSTANCE, DokuGumoAbility.INSTANCE, VenomDemonAbility.INSTANCE, PoisonImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> DORU_DORU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Doru Doru no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{CandleWallAbility.INSTANCE, CandleHouseAbility.INSTANCE, DoruDoruArtsMoriAbility.INSTANCE, DoruDoruArtsKenAbility.INSTANCE, CandleLockAbility.INSTANCE, DoruDoruArtsPickaxeAbility.INSTANCE, DoruDoruBallAbility.INSTANCE, DoruDoruNoYakataAbility.INSTANCE, CandleChampionAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> KAGE_KAGE_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Kage Kage no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{DoppelmanAbility.INSTANCE, KagemushaAbility.INSTANCE, BrickBatAbility.INSTANCE, BlackBoxAbility.INSTANCE, TsunoTokageAbility.INSTANCE, KageKakumeiAbility.INSTANCE, KageGiriAbility.INSTANCE, NightmareSoldiersAbility.INSTANCE, ShadowsAsgardAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> GURA_GURA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Gura Gura no Mi", () -> new AkumaNoMiItem(3, FruitType.PARAMECIA, new RegistryObject[]{GekishinAbility.INSTANCE, ShingenNoIchigekiAbility.INSTANCE, TenchiMeidoAbility.INSTANCE, ShimaYurashiAbility.INSTANCE, GuraImmunityAbility.INSTANCE, KabutowariAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> BOMU_BOMU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Bomu Bomu no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{NoseFancyCannonAbility.INSTANCE, KickBombAbility.INSTANCE, ZenshinKibakuAbility.INSTANCE, ExplosivePunchAbility.INSTANCE, BreezeBreathBombAbility.INSTANCE, ExplosionImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> NIKYU_NIKYU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Nikyu Nikyu no Mi", () -> new AkumaNoMiItem(3, FruitType.PARAMECIA, new RegistryObject[]{PadHoAbility.INSTANCE, HanpatsuAbility.INSTANCE, TsuppariPadHoAbility.INSTANCE, UrsusShockAbility.INSTANCE, PuniAbility.INSTANCE, NikyuPushAbility.INSTANCE, PainRepelAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> NORO_NORO_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Noro Noro no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{NoroNoroBeamAbility.INSTANCE, NoroNoroBeamSwordAbility.INSTANCE, KyubiRushAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> OPE_OPE_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Ope Ope no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{RoomAbility.INSTANCE, ShamblesAbility.INSTANCE, TaktAbility.INSTANCE, InjectionShotAbility.INSTANCE, CounterShockAbility.INSTANCE, MesAbility.INSTANCE, GammaKnifeAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> SUKE_SUKE_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Suke Suke no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{SkattingAbility.INSTANCE, ShishaNoTeAbility.INSTANCE, SukePunchAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> GOMU_GOMU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Gomu Gomu no Mi", () -> new AkumaNoMiItem(2, FruitType.PARAMECIA, new RegistryObject[]{GomuGomuNoPistolAbility.INSTANCE, GomuGomuNoGatlingAbility.INSTANCE, GomuGomuNoBazookaAbility.INSTANCE, GomuGomuNoRocketAbility.INSTANCE, GearSecondAbility.INSTANCE, GearThirdAbility.INSTANCE, GearFourthAbility.INSTANCE, GearFourthFlightAbility.INSTANCE, BouncyAbility.INSTANCE, BulletReflectAbility.INSTANCE, GomuImmunityAbility.INSTANCE, GearFifthAbility.INSTANCE, GomuGomuNoGigantAbility.INSTANCE, GomuGomuNoDawnWhipAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> BANE_BANE_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Bane Bane no Mi", () -> new AkumaNoMiItem(1, FruitType.PARAMECIA, new RegistryObject[]{SpringHopperAbility.INSTANCE, SpringSnipeAbility.INSTANCE, SpringDeathKnockAbility.INSTANCE, NoFallDamageAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> YUKI_YUKI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Yuki Yuki no Mi", () -> new AkumaNoMiItem(3, FruitType.LOGIA, new RegistryObject[]{KamakuraAbility.INSTANCE, YukiRabiAbility.INSTANCE, KamakuraJussoshiAbility.INSTANCE, TabiraYukiAbility.INSTANCE, YukiGakiAbility.INSTANCE, FubukiAbility.INSTANCE, YukiLogiaAbility.INSTANCE, YukiImmunityAbility.INSTANCE, YukiTravelAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> YAMI_YAMI_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Yami Yami no Mi", () -> new AkumaNoMiItem(3, FruitType.LOGIA, new RegistryObject[]{BlackHoleAbility.INSTANCE, BlackRoadAbility.INSTANCE, LiberationAbility.INSTANCE, KurouzuAbility.INSTANCE, DarkMatterAbility.INSTANCE, BlackWorldAbility.INSTANCE, AbsorbedBlocksAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> GASU_GASU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Gasu Gasu no Mi", () -> new AkumaNoMiItem(3, FruitType.LOGIA, new RegistryObject[]{GasRobeAbility.INSTANCE, GastanetAbility.INSTANCE, GastilleAbility.INSTANCE, BlueSwordAbility.INSTANCE, KarakuniAbility.INSTANCE, ShinokuniAbility.INSTANCE, KoroAbility.INSTANCE, GasuFlyAbility.INSTANCE, GasuImmunityAbility.INSTANCE, GasuLogiaAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> MAGU_MAGU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Magu Magu no Mi", () -> new AkumaNoMiItem(3, FruitType.LOGIA, new RegistryObject[]{DaiFunkaAbility.INSTANCE, RyuseiKazanAbility.INSTANCE, MeigoAbility.INSTANCE, BakuretsuKazanAbility.INSTANCE, LavaFlowAbility.INSTANCE, MagmaCoatingAbility.INSTANCE, MaguLogiaAbility.INSTANCE, LogiaHeatImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> SUNA_SUNA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Suna Suna no Mi", () -> new AkumaNoMiItem(3, FruitType.LOGIA, new RegistryObject[]{DesertSpadaAbility.INSTANCE, DesertGrandeEspadaAbility.INSTANCE, SablesAbility.INSTANCE, GrandeSablesAbility.INSTANCE, BarjanAbility.INSTANCE, DesertEncierroAbility.INSTANCE, GroundDeathAbility.INSTANCE, DesertGirasoleAbility.INSTANCE, SunaFlyAbility.INSTANCE, SablesPesadoAbility.INSTANCE, SunaLogiaAbility.INSTANCE, LogiaImmunityAbility.INSTANCE, SunaTravelAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> GORO_GORO_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Goro Goro no Mi", () -> new AkumaNoMiItem(3, FruitType.LOGIA, new RegistryObject[]{SparkStepAbility.INSTANCE, ElThorAbility.INSTANCE, VariAbility.INSTANCE, KariAbility.INSTANCE, SangoAbility.INSTANCE, VoltAmaruAbility.INSTANCE, VoltAmaruFlightAbility.INSTANCE, RaigoAbility.INSTANCE, GoroLogiaAbility.INSTANCE, LogiaHeatImmunityAbility.INSTANCE, GoroTravelAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> MOKU_MOKU_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Moku Moku no Mi", () -> new AkumaNoMiItem(3, FruitType.LOGIA, new RegistryObject[]{WhiteBlowAbility.INSTANCE, WhiteSnakeAbility.INSTANCE, WhiteLauncherAbility.INSTANCE, WhiteStrikeAbility.INSTANCE, WhiteBlowRushAbility.INSTANCE, WhiteOutAbility.INSTANCE, MokuFlyAbility.INSTANCE, WhitePullAbility.INSTANCE, SmokeLaunchAbility.INSTANCE, MokuLogiaAbility.INSTANCE, MokuImmunityAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> PIKA_PIKA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Pika Pika no Mi", () -> new AkumaNoMiItem(3, FruitType.LOGIA, new RegistryObject[]{YataNoKagamiAbility.INSTANCE, YasakaniNoMagatamaAbility.INSTANCE, AmaNoMurakumoAbility.INSTANCE, AmaterasuAbility.INSTANCE, FlashAbility.INSTANCE, PikaLogiaAbility.INSTANCE, LightAccelerationAbility.INSTANCE, LogiaImmunityAbility.INSTANCE, PikaTravelAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> HIE_HIE_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Hie Hie no Mi", () -> new AkumaNoMiItem(3, FruitType.LOGIA, new RegistryObject[]{IceBlockPartisanAbility.INSTANCE, IceAgeAbility.INSTANCE, IceBallAbility.INSTANCE, IceSaberAbility.INSTANCE, IceTimeAbility.INSTANCE, IceBlockPheasantAbility.INSTANCE, IceBlockAvalancheAbility.INSTANCE, HieLogiaAbility.INSTANCE, FrostWalkerAbility.INSTANCE, HieImmunityAbility.INSTANCE, HieTravelAbility.INSTANCE}));
   public static final RegistryObject<AkumaNoMiItem> MERA_MERA_NO_MI = ModRegistry.<AkumaNoMiItem>registerFruitItem("Mera Mera no Mi", () -> new AkumaNoMiItem(3, FruitType.LOGIA, new RegistryObject[]{HikenAbility.INSTANCE, HiganAbility.INSTANCE, DaiEnkaiAbility.INSTANCE, HidarumaAbility.INSTANCE, JujikaAbility.INSTANCE, HeatDashAbility.INSTANCE, KyokaenAbility.INSTANCE, HibashiraAbility.INSTANCE, MeraLogiaAbility.INSTANCE, LogiaHeatImmunityAbility.INSTANCE}));

   private static <T extends AkumaNoMiItem> RegistryObject<T> registerMochi(String localizedName, Supplier<T> fruit) {
      return WyHelper.isAprilFirst() ? ModRegistry.registerFruitItem(localizedName, fruit) : null;
   }

   public static void init() {
   }
}
