package xyz.pixelatedw.mineminenomi.init;

import net.minecraftforge.registries.RegistryObject;
import xyz.pixelatedw.mineminenomi.api.WyHelper;
import xyz.pixelatedw.mineminenomi.particles.effects.BerserkerPowerupParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.BreakingBlocksParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.ChargeMH5ParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.CommandMarkParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.CommonExplosionParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.GroundParticlesEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.GuardParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.HakiGuardParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.LogiaParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.ParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.SpecialFlyingParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.WaterExplosionParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.artofweather.ChargedWeatherBallParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.artofweather.FailedTempoParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.artofweather.GustSwordParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.artofweather.ThunderLanceParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.artofweather.WeatherCloudChargedParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.artofweather.WeatherCloudParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.awa.GoldenHourParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.awa.RelaxHourParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.awa.WashedParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.beta.HanamizuShinkenShirahadoriParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.blackleg.BienCuitGrillShotParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.blackleg.ConcasseDiableParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.blackleg.DiableJambeParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.blackleg.ExtraHachiDiableParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.blackleg.PartyTableKickCourseParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.brawler.KingPunchChargeParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.chiyu.ChiyupopoParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.chiyu.HealingTouchParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.common.ShockwaveParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.cyborg.ChargeRadicalBeamParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.cyborg.CoupDeBooParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.cyborg.FreshFireParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.doctor.FirstAidParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.doctor.MedicBagExplosionParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.doku.ChloroBallCloudParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.doku.ChloroBallParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.doku.DokuGumoParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.doku.VenomDemonParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.doru.CandleLockParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.doru.TokudaiCandleParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.electro.ElectricalLunaParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.electro.ElectricalTempesta2ParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.electro.ElectroChargingParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.extra.MH5GasParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.fishkarate.KarakusagawaraSeikenChargeParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.fishkarate.MizuOsuParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.fishkarate.MizuTaihoParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.fishkarate.SamehadaParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.gasu.BigGastilleParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.gasu.GasRobeParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.gasu.GastanetParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.gasu.GastilleParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.gasu.KoroParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.gasu.ShinokuniParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.gomu.GearSecondParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.goro.ElThorAimParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.goro.ElThorParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.goro.GenericUseLightningParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.goro.GenericUseYellowLightningParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.goro.KariParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.goro.LightningExplosionParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.goro.RaigoParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.goro.SangoParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.goro.SparkStepParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.gura.AirCrackParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.gura.GekishinParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.haki.EmissionBurstParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.haki.HaoshokuHakiParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.haki.InternalDestructionBurstParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.hana.BloomParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.hie.IceAgeParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.hie.IceBlockAvalancheParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.hitodaibutsu.ImpactWaveParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.horu.WinkExplosionParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.horu.WinkParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.ito.KumoNoSugakiParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.jiki.AttractParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.kachi.EvaporateParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.kage.ChargeableKageParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.kobu.ShoureiParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.mera.DaiEnkai2ParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.mera.DaiEnkaiParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.mera.HeatDashParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.mera.HibashiraParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.mera.JujikaParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.mera.KyokaenParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.mero.PerfumeFemurParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.mero.SlaveArrowParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.moku.SmokeDebuffParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.moku.WhiteLauncherParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.moku.WhiteStrikeParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.netsu.NetsuEnhancementParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.ope.CounterShockParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.pero.CandyWaveParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.pika.ChargingPikaParticleEvent;
import xyz.pixelatedw.mineminenomi.particles.effects.pika.FlashParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.pika.YataNoKagamiParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.rokushiki.GeppoParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.sabaody.BonChariPoppingParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.sabi.RustBreakParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.sabi.RustTouchParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.sniper.KemuriBoshiParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.suna.BarjanParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.suna.DesertEncierroParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.suna.DesertGirasole2ParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.suna.DesertGirasoleParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.suna.DesertSpadaParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.suna.GroundDeathParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.suna.SablesNewParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.suna.SablesParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.suna.SablesPesadoChargingParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.suna.SandBladeParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.swordsman.HiryuKaenParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.swordsman.TatsuMakiParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.toriphoenix.BlueBirdParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.toriphoenix.BlueFlamesParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.toriphoenix.FujizamiParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.toriphoenix.PhoenixGoenParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.toriphoenix.TenseiNoSoen2ParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.toriphoenix.TenseiNoSoenParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.ushibison.KokuteiCrossParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.yami.BlackHoleParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.yami.BlackWorldParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.yami.DarkMatterChargingParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.yami.DarkMatterParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.yami.KurouzuChargeParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.yami.KurouzuParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.yomi.KasuriutaFubukiGiriParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.yomi.SoulParadeParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.yuki.FubukiParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.yuki.KamakuraParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.zou.GreatStompParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.zushi.GraviPull1ParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.zushi.GraviPull2ParticleEffect;
import xyz.pixelatedw.mineminenomi.particles.effects.zushi.GraviZoneParticleEffect;

public class ModParticleEffects {
   public static final RegistryObject<ParticleEffect<?>> KYOKAEN = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Kyokaen", KyokaenParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> JUJIKA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Jujika", JujikaParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> HIBASHIRA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Hibashira", HibashiraParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> HEAT_DASH = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Heat Dash", HeatDashParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> DAI_ENKAI_1 = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Dai Enkai 1", DaiEnkaiParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> DAI_ENKAI_2 = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Dai Enkai 2", DaiEnkai2ParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> DESERT_SPADA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Desert Spada", DesertSpadaParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> DESERT_ENCIERRO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Desert Encierro", DesertEncierroParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> DESERT_GIRASOLE_1 = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Desert Girasole 1", DesertGirasoleParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> DESERT_GIRASOLE_2 = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Desert Girasole 2", DesertGirasole2ParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GROUND_DEATH = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Ground Death", GroundDeathParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SABLES = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Sables", SablesParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SABLES_NEW = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Sables New", SablesNewParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SABLES_PESADO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Sables Pesado", SablesPesadoChargingParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SAND_BLADE_IDLE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Sand Blade Idle", () -> new SandBladeParticleEffect(false));
   public static final RegistryObject<ParticleEffect<?>> SAND_BLADE_ACTIVE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Sand Blade Active", () -> new SandBladeParticleEffect(true));
   public static final RegistryObject<ParticleEffect<?>> BARJAN = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Barjan", BarjanParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> FUBUKI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Fubuki", FubukiParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KAMAKURA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Kamakura", KamakuraParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> ICE_AGE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Ice Age", IceAgeParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> ICE_BLOCK_AVALANCHE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Ice Block Avalanche", IceBlockAvalancheParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> CHLORO_BALL_CLOUD = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Chloro Ball Cloud", ChloroBallCloudParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> CHLORO_BALL = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Chloro Ball", ChloroBallParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> DOKU_GUMO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Doku Gumo", DokuGumoParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> VENOM_DEMON = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Venom Demon", VenomDemonParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> WHITE_LAUNCHER = ModRegistry.<ParticleEffect<?>>registerParticleEffect("White Launcher", WhiteLauncherParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> WHITE_STRIKE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("White Strike", WhiteStrikeParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SMOKE_DEBUFF = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Smoke Debuff", SmokeDebuffParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> PIKA_CHARGING = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Pika Charging", ChargingPikaParticleEvent::new);
   public static final RegistryObject<ParticleEffect<?>> FLASH = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Flash", FlashParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> YATA_NO_KAGAMI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Yata no Kagami", YataNoKagamiParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> BLUE_BIRD = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Blue Bird", BlueBirdParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> BLUE_FLAMES = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Blue Flames", BlueFlamesParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> FUJIZAMI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Fujizami", FujizamiParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> TENSEI_NO_SOEN_1 = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Tensei no Soen 1", TenseiNoSoenParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> TENSEI_NO_SOEN_2 = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Tensei no Soen 2", TenseiNoSoen2ParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> FLAMES_OF_REGEN = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Flames of Regen", () -> new LogiaParticleEffect(ModParticleTypes.BLUE_FLAME));
   public static final RegistryObject<ParticleEffect<?>> PHOENIX_GOEN = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Phoenix Goen", PhoenixGoenParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GRAVI_ZONE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gravi Zone", GraviZoneParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GRAVI_PULL_1 = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gravi Pull 1", GraviPull1ParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GRAVI_PULL_2 = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gravi Pull 2", GraviPull2ParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> EL_THOR = ModRegistry.<ParticleEffect<?>>registerParticleEffect("El Thor", ElThorParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> EL_THOR_AIM = ModRegistry.<ParticleEffect<?>>registerParticleEffect("El Thor Aim", ElThorAimParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GENERIC_LIGHTNING_USE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Generic Lighting Use", GenericUseLightningParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GENERIC_YELLOW_LIGHTNING_USE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Generic Yellow Lighting Use", GenericUseYellowLightningParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KARI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Kari", KariParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> LIGHTING_EXPLOSION = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Lighting Explosion", LightningExplosionParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> RAIGO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Raigo", RaigoParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SANGO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Sango", SangoParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SPARK_STEP = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Spark Step", SparkStepParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> HORU_WINK = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Horu Wink", WinkParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> WINK_EXPLOSION = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Wink Explosion", WinkExplosionParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KUMO_NO_SUGAKI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Kumo no Sugaki", KumoNoSugakiParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> IMPACT_WAVE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Impact Wave", ImpactWaveParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> NETSU_ENCHANTMENT = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Netsu Enchantment", NetsuEnhancementParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> COUNTER_SHOCK = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Counter Shock", CounterShockParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> CANDLE_LOCK = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Candle Lock", CandleLockParticleEffect::new);
   public static final RegistryObject<ParticleEffect<ParticleEffect.NoDetails>> TOKUDAI_CANDLE = ModRegistry.<ParticleEffect<ParticleEffect.NoDetails>>registerParticleEffect("Tokudai Candle", TokudaiCandleParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> CANDY_WAVE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Candy Wave", CandyWaveParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> RUST_TOUCH = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Rust Touch", RustTouchParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> RUST_SKIN = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Rust Skin", () -> new LogiaParticleEffect(ModParticleTypes.RUST));
   public static final RegistryObject<ParticleEffect<?>> RUST_BREAK = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Rust Break", RustBreakParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> BLACK_HOLE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Black Hole", BlackHoleParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> BLACK_WORLD = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Black World", BlackWorldParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> DARK_MATTER = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Dark Matter", DarkMatterParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> DARK_MATTER_CHARGING = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Dark Matter Chargingg", DarkMatterChargingParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KUROUZU = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Kurouzu", KurouzuParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KUROUZU_CHARGING = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Kurouzu Charging", KurouzuChargeParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> COOL_BALL_CHARGE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Cool Ball Charge", () -> new ChargedWeatherBallParticleEffect(WyHelper.hexToRGB("#0055FF"), ModParticleTypes.HIE));
   public static final RegistryObject<ParticleEffect<?>> HEAT_BALL_CHARGE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Heat Ball Charge", () -> new ChargedWeatherBallParticleEffect(WyHelper.hexToRGB("#FF0000"), ModParticleTypes.GASU));
   public static final RegistryObject<ParticleEffect<?>> THUNDER_BALL_CHARGE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Thunder Ball Charge", () -> new ChargedWeatherBallParticleEffect(WyHelper.hexToRGB("#FFFFFF"), ModParticleTypes.GORO_YELLOW));
   public static final RegistryObject<ParticleEffect<?>> THUNDER_LANCE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Thunder Lance", ThunderLanceParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> FAILED_TEMPO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Failed Tempo", FailedTempoParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> WEATHER_CLOUD = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Weather Cloud", WeatherCloudParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> CHARGED_WEATHER_CLOUD = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Charged Weather Cloud", WeatherCloudChargedParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GUST_SWORD = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gust Sword", GustSwordParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KEMURI_BOSHI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Kemuri Boshi", KemuriBoshiParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> HIRYU_KAEN = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Hiryu Kaen", HiryuKaenParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> TATSU_MAKI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Tatsu Maki", TatsuMakiParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> DIABLE_JAMBE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Diable Jambe", DiableJambeParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> BIEN_CUIT_GRILL_SHOT = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Bien Cuit Grill Shot", BienCuitGrillShotParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> PARTY_TABLE_KICK = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Party Table Kick", PartyTableKickCourseParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> CONCASSE_DIABLE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Concasse Diable", ConcasseDiableParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> EXTRA_HACHI_DIABLE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Extra Hachi Diable", ExtraHachiDiableParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KING_PUNCH_CHARGING = ModRegistry.<ParticleEffect<?>>registerParticleEffect("King Punch Charging", KingPunchChargeParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> FIRST_AID = ModRegistry.<ParticleEffect<?>>registerParticleEffect("First Aid", FirstAidParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> MEDIC_BAG_EXPLOSION = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Medic Bag Explosion", MedicBagExplosionParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GEPPO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Geppo", GeppoParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SAMEHADA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Samehada", SamehadaParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KARAKUSAGAWARA_SEIKEN_CHARGING = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Karakusagawara Seiken Charge", KarakusagawaraSeikenChargeParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> MIZU_TAIHO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Mizu Taiho", MizuTaihoParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> MIZU_OSU = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Mizu Osu", MizuOsuParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> COUP_DE_BOO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Coup de Boo", CoupDeBooParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> FRESH_FIRE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Fresh Fire", FreshFireParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> CHARGE_RADICAL_BEAM = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Charge Radical Beam", ChargeRadicalBeamParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> ELECTRICAL_LUNA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Electrical Luna", ElectricalLunaParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> ELECTRICAL_TEMPESTA_2 = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Electrical Tempesta 2", ElectricalTempesta2ParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> ELECTRO_CHARGING = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Electro Charging", ElectroChargingParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GASTANET = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gastanet", GastanetParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KORO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Koro", KoroParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SHINOKUNI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Shinokuni", ShinokuniParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> BIG_GASTILLE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Big Gastille", BigGastilleParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GASTILLE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gastille", GastilleParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GAS_ROBE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gas Robe", GasRobeParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GOLDEN_HOUR = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Golden Hour", GoldenHourParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> RELAX_HOUR = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Relax Hour", RelaxHourParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> WASHED = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Washed", WashedParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> BLOOM = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Bloom", BloomParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> ATTRACT = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Attract", AttractParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GEAR_SECOND = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gear Second", GearSecondParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> EVAPORATE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Evaporate", EvaporateParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SHOUREI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Shourei", ShoureiParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> CHIYUPOPO = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Chiyupopo", ChiyupopoParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> HEALING_TOUCH = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Healing Touch", HealingTouchParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> BETA_COATING = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Beta Coating", () -> new LogiaParticleEffect(ModParticleTypes.BETA));
   public static final RegistryObject<ParticleEffect<?>> HANAMIZU_SHINKEN_SHIRADORI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Hanamizu Shinken Shirahadori", HanamizuShinkenShirahadoriParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KOKUTEI_CROSS = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Kokutei Cross", KokuteiCrossParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GREAT_STOMP = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Great Stomp", GreatStompParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SOUL_PARADE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Soul Parade", SoulParadeParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> KASURIUTA_FUBUKI_GIRI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Kasuriuta Fubuki Giri", KasuriutaFubukiGiriParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SLAVE_ARROW = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Slave Arrow", SlaveArrowParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> PERFUME_FEMUR = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Perfume Femur", PerfumeFemurParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> CHARGE_KAGE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Charge Kage", ChargeableKageParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GEKISHIN = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gekishin", GekishinParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> AIR_CRACKS = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Air Cracks", AirCrackParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> HAOSHOKU_HAKI = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Haoshoku Haki", HaoshokuHakiParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> EMISSION_BURST = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Emission Burst", EmissionBurstParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> INTERNAL_DESTRUCTION_BURST = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Internal Destruction Burst", InternalDestructionBurstParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> MERA_LOGIA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Mera Logia", () -> new LogiaParticleEffect(ModParticleTypes.MERA));
   public static final RegistryObject<ParticleEffect<?>> GASU_LOGIA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gasu Logia", () -> new LogiaParticleEffect(ModParticleTypes.GASU));
   public static final RegistryObject<ParticleEffect<?>> GORO_LOGIA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Goro Logia", () -> new LogiaParticleEffect(ModParticleTypes.GORO));
   public static final RegistryObject<ParticleEffect<?>> HIE_LOGIA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Hie Logia", () -> new LogiaParticleEffect(ModParticleTypes.HIE));
   public static final RegistryObject<ParticleEffect<?>> MAGU_LOGIA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Magu Logia", () -> new LogiaParticleEffect(ModParticleTypes.MAGU));
   public static final RegistryObject<ParticleEffect<?>> MOKU_LOGIA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Moku Logia", () -> new LogiaParticleEffect(ModParticleTypes.MOKU2));
   public static final RegistryObject<ParticleEffect<?>> NUMA_LOGIA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Numa Logia", () -> new LogiaParticleEffect(ModParticleTypes.SUNA2));
   public static final RegistryObject<ParticleEffect<?>> PIKA_LOGIA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Pika Logia", () -> new LogiaParticleEffect(ModParticleTypes.PIKA));
   public static final RegistryObject<ParticleEffect<?>> SUNA_LOGIA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Suna Logia", () -> new LogiaParticleEffect(ModParticleTypes.SUNA2));
   public static final RegistryObject<ParticleEffect<?>> YUKI_LOGIA = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Yuki Logia", () -> new LogiaParticleEffect(ModParticleTypes.YUKI));
   public static final RegistryObject<ParticleEffect<?>> GASU_FLY = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Gasu Fly", () -> new SpecialFlyingParticleEffect(ModParticleTypes.GASU));
   public static final RegistryObject<ParticleEffect<?>> SUNA_FLY = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Suna Fly", () -> new SpecialFlyingParticleEffect(ModParticleTypes.SUNA2));
   public static final RegistryObject<ParticleEffect<?>> MOKU_FLY = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Moku Fly", () -> new SpecialFlyingParticleEffect(ModParticleTypes.MOKU));
   public static final RegistryObject<ParticleEffect<?>> BREAKING_BLOCKS = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Breaking Blocks", BreakingBlocksParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> SHOCKWAVE = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Shockwave", ShockwaveParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> BERSERKER_POWERUP = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Berserker Powerup", BerserkerPowerupParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GUARD = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Guard", GuardParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> HAKI_GUARD = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Haki Guard", HakiGuardParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> BON_CHARI_POPPING = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Bon Chari Popping", BonChariPoppingParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> COMMAND_MARK = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Command Mark", CommandMarkParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> MH5_GAS = ModRegistry.<ParticleEffect<?>>registerParticleEffect("MH5 Gas", MH5GasParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> CHARGE_MH5_BOMB = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Charge MH5 Bomb", ChargeMH5ParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> COMMON_EXPLOSION = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Common Explosion", CommonExplosionParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> WATER_EXPLOSION = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Water Explosion", WaterExplosionParticleEffect::new);
   public static final RegistryObject<ParticleEffect<?>> GROUND_PARTICLES = ModRegistry.<ParticleEffect<?>>registerParticleEffect("Ground Particles", GroundParticlesEffect::new);

   public static void init() {
   }
}
